In [1]:
import pandas as pd
import numpy as np

In [2]:
token = "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"
!git clone https://{token}@github.com/Raghav-Sahni/Hope_speech.git

Cloning into 'Hope_speech'...
remote: Enumerating objects: 740, done.
remote: Counting objects: 100% (301/301), done.
remote: Compressing objects: 100% (163/163), done.
remote: Total 740 (delta 178), reused 246 (delta 137), pack-reused 439
Receiving objects: 100% (740/740), 69.97 MiB | 18.63 MiB/s, done.
Resolving deltas: 100% (438/438), done.


In [3]:
from gensim.models import Word2Vec

In [4]:
eng_test = pd.read_csv("/content/Hope_speech/Data/PreprocessedData/english_test_preprocess.csv")
eng_dev = pd.read_csv("/content/Hope_speech/Data/PreprocessedData/english_dev_preprocess.csv")

In [5]:
eng_df = pd.read_csv("/content/Hope_speech/Data/PreprocessedData/english_train_preprocess.csv")

In [6]:
eng_df.head()

Unnamed: 0                                               text  \
0           0  these tiktoks radiate gay chaotic energy and i...   
1           1  @Champions Again He got killed for using false...   
2           2               It's not that all lives don't matter   
3           3  Is it really that difficult to understand? Bla...   
4           4  Whenever we say black isn't that racists?  Why...   

             label                                  preprocessed_text  
0  Non_hope_speech  these tiktoks radiate gay chaotic energy and i...  
1  Non_hope_speech   <user> again he got killed for using false money  
2  Non_hope_speech                 its not that all lives dont matter  
3  Non_hope_speech  is it really that difficult to understand blac...  
4  Non_hope_speech  whenever we say black isnt that racists why do...

In [84]:
aug_df = pd.read_csv("/content/Hope_speech/Data/AugmentedData/english_train_augmented.csv")

In [85]:
aug_df.head()

Unnamed: 0                                     augmented_text        label
0           0  engineer network here 23 presently working as ...  Hope_speech
1           1  engineer network here 23 and presently instruc...  Hope_speech
2           2  Still im hiding grammatical gender to my paren...  Hope_speech
3           3  im hide still my gender to my parents and they...  Hope_speech
4           4  all subject without lives that we never have p...  Hope_speech

In [7]:
eng_df = pd.concat([eng_df, eng_test, eng_dev], axis=0)

In [87]:
sentences = aug_df["augmented_text"].values

In [88]:
sentences = [i.split() for i in sentences]

In [89]:
from gensim.test.utils import common_texts
w2v = Word2Vec(window=2, size=300, min_count = 1)

In [90]:
w2v.build_vocab(sentences, progress_per=10000)

In [91]:
w2v.train(sentences, total_examples=w2v.corpus_count, epochs = 30)

(20734022, 26948760)

In [92]:
w2v.init_sims(replace=True)

In [93]:
embeddings_w2v_aug = [np.mean(w2v.wv.__getitem__(i), axis = 0) for i in sentences]

In [97]:
len(embeddings_w2v_aug)

42382

In [95]:
import pickle

with open('gensim_custom_w2v_embeddings_augmented_train.pickle', 'wb') as handle:
    pickle.dump(embeddings_w2v_aug, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [28]:
import os 
os.chdir("/content/Hope_speech/Models")

In [107]:
from embeddings_loader import *
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import GridSearchCV, StratifiedKFold
import matplotlib.pyplot as plt
import numpy as np
import pickle
#from utils import computeAllScores
#import eli5

In [30]:
path = "/content/drive/MyDrive/word_embeddings/computed_embeddings"

In [64]:
train_labels, dev_labels, test_labels = load_labels(path)

In [65]:
label_replacement = {
    'Hope_speech': 0,
    'Non_hope_speech': 1,
    'not-English': 2,
}

In [66]:
train_labels = [label_replacement[label] for label in train_labels]
dev_labels = [label_replacement[label] for label in dev_labels]
test_labels = [label_replacement[label] for label in test_labels]

In [67]:
len(train_labels)

22762

In [73]:
xgboost = XGBClassifier(base_estimator = DecisionTreeClassifier(max_depth = 2), n_estimators = 100)

In [78]:
x_train = np.array(embeddings_w2v_aug[:len(train_labels)])
x_test = np.array(embeddings_w2v_aug[len(train_labels):len(train_labels)+len(test_labels)])
x_dev = np.array(embeddings_w2v_aug[len(train_labels)+len(test_labels):])

In [79]:
len(x_test)

2846

In [80]:
import pickle

with open('gensim_custom_w2v_embeddings_test.pickle', 'wb') as handle:
    pickle.dump(x_test, handle, protocol=pickle.HIGHEST_PROTOCOL)

with open('gensim_custom_w2v_embeddings_train.pickle', 'wb') as handle:
    pickle.dump(x_train, handle, protocol=pickle.HIGHEST_PROTOCOL)

with open('gensim_custom_w2v_embeddings_dev.pickle', 'wb') as handle:
    pickle.dump(x_dev, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [70]:
len(x_train[0])

300

In [74]:
xgboost.fit(x_train, train_labels)

XGBClassifier(base_estimator=DecisionTreeClassifier(max_depth=2),
              objective='multi:softprob')

In [81]:
train_preds = xgboost.predict(x_train)
dev_preds = xgboost.predict(x_dev)
test_preds = xgboost.predict(x_test)

In [105]:
def computeAllScores(y_pred_train, y_pred_dev, y_pred_test, aug=False, two_class=False):
    if aug:
        if two_class:
            train_l = train_aug_labels_two_class
            dev_l = dev_labels_two_class
            test_l = test_labels_two_class
        else:
            train_l = train_aug_labels
            dev_l = dev_labels
            test_l = test_labels
    else:
        if two_class:
            train_l = train_labels_two_class
            dev_l = dev_labels_two_class
            test_l = test_labels_two_class
        else:
            train_l = train_labels
            dev_l = dev_labels
            test_l = test_labels
    print("Accuracy Train: ", accuracy_score(train_l, y_pred_train))
    print("Accuracy Dev: ", accuracy_score(dev_l, y_pred_dev))
    print("Accuracy Test: ", accuracy_score(test_l, y_pred_test))
    print("Weighted F1 Train: ", f1_score(train_l, y_pred_train, average="weighted"))
    print("Weighted F1 Dev: ", f1_score(dev_l, y_pred_dev, average="weighted"))
    print("Weighted F1 Test: ", f1_score(test_l, y_pred_test, average="weighted"))
    print("Macro F1 Train: ", f1_score(train_l, y_pred_train, average="macro"))
    print("Macro F1 Dev: ", f1_score(dev_l, y_pred_dev, average='macro'))
    print("Macro F1 Test: ", f1_score(test_l, y_pred_test, average='macro'))
    print("Micro F1 Train: ", f1_score(train_l, y_pred_train, average="micro"))
    print("Micro F1 Dev: ", f1_score(dev_l, y_pred_dev, average='micro'))
    print("Micro F1 Test: ", f1_score(test_l, y_pred_test, average='micro'))
    print("Weighted Recall Train: ", recall_score(train_l, y_pred_train, average="weighted"))
    print("Weighted Recall Dev: ", recall_score(dev_l, y_pred_dev, average='weighted'))
    print("Weighted Recall Test: ", recall_score(test_l, y_pred_test, average='weighted'))
    print("Macro Recall Train: ", recall_score(train_l, y_pred_train, average="macro"))
    print("Macro Recall Dev: ", recall_score(dev_l, y_pred_dev, average='macro'))
    print("Macro Recall Test: ", recall_score(test_l, y_pred_test, average='macro'))
    print("Micro Recall Train: ", recall_score(train_l, y_pred_train, average="micro"))
    print("Micro Recall Dev: ", recall_score(dev_l, y_pred_dev, average='micro'))
    print("Micro Recall Test: ", recall_score(test_l, y_pred_test, average='micro'))
    # Confusion Matrix
    print("Confusion Matrix Train: ")
    print(confusion_matrix(train_l, y_pred_train))
    print("Confusion Matrix Dev: ")
    print(confusion_matrix(dev_l, y_pred_dev))
    print("Confusion Matrix Test: ")
    print(confusion_matrix(test_l, y_pred_test))


In [106]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9243475968719796
Accuracy Dev:  0.9134716848399578
Accuracy Test:  0.9188334504567814
Weighted F1 Train:  0.8993429269088773
Weighted F1 Dev:  0.884460723450109
Weighted F1 Test:  0.8904998482208376
Macro F1 Train:  0.5999940749003793
Macro F1 Dev:  0.39562006608891603
Macro F1 Test:  0.3887631253385562
Micro F1 Train:  0.9243475968719796
Micro F1 Dev:  0.9134716848399578
Micro F1 Test:  0.9188334504567814
Weighted Recall Train:  0.9243475968719796
Weighted Recall Dev:  0.9134716848399578
Weighted Recall Test:  0.9188334504567814
Macro Recall Train:  0.5197575146020971
Macro Recall Dev:  0.37750870102809514
Macro Recall Test:  0.3723049235120195
Micro Recall Train:  0.9243475968719796
Micro Recall Dev:  0.9134716848399578
Micro Recall Test:  0.9188334504567814
Confusion Matrix Train: 
[[  299  1663     0]
 [   46 20732     0]
 [    0    13     9]]
Confusion Matrix Dev: 
[[  37  235    0]
 [   9 2560    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  30  220    0]
 