In [1]:
from embeddings_loader import *
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import roc_auc_score


In [2]:
train_labels, dev_labels, test_labels = load_labels()

In [3]:
def computeAllScores(y_pred_train, y_pred_dev, y_pred_test):
    print("Accuracy Train: ", accuracy_score(train_labels, y_pred_train))
    print("Accuracy Dev: ", accuracy_score(dev_labels, y_pred_dev))
    print("Accuracy Test: ", accuracy_score(test_labels, y_pred_test))
    print("F1 Train: ", f1_score(train_labels, y_pred_train, average='macro'))
    print("F1 Dev: ", f1_score(dev_labels, y_pred_dev, average='macro'))
    print("F1 Test: ", f1_score(test_labels, y_pred_test, average='macro'))
    print("Precision Train: ", precision_score(train_labels, y_pred_train, average='macro'))
    print("Precision Dev: ", precision_score(dev_labels, y_pred_dev, average='macro'))
    print("Precision Test: ", precision_score(test_labels, y_pred_test, average='macro'))
    print("Recall Train: ", recall_score(train_labels, y_pred_train, average='macro'))
    print("Recall Dev: ", recall_score(dev_labels, y_pred_dev, average='macro'))
    print("Recall Test: ", recall_score(test_labels, y_pred_test, average='macro'))
    # Confusion Matrix
    print("Confusion Matrix Train: ")
    print(confusion_matrix(train_labels, y_pred_train))
    print("Confusion Matrix Dev: ")
    print(confusion_matrix(dev_labels, y_pred_dev))
    print("Confusion Matrix Test: ")
    print(confusion_matrix(test_labels, y_pred_test))

In [4]:
label_replacement = {
    'Hope_speech': 0,
    'Non_hope_speech': 1,
    'not-English': 2,
}

In [5]:
# Replace labels with numbers
train_labels = [label_replacement[label] for label in train_labels]
dev_labels = [label_replacement[label] for label in dev_labels]
test_labels = [label_replacement[label] for label in test_labels]

In [6]:
decision_tree = DecisionTreeClassifier()
gridsearch = GridSearchCV(decision_tree, param_grid = {
    "criterion": ["gini", "entropy"],
    "max_depth": [5, 10, 15, 20],
    "max_features": ["sqrt", "log2", None],
    "splitter": ["best", "random"],
    "min_samples_split": [2, 5, 10],

}, scoring = "f1_micro")

### Glove Twitter 25

In [7]:
gt25_train, gt25_dev, gt25_test = load_glove_twitter_25()

In [8]:
# Set all NaN values to 0
gt25_train = np.nan_to_num(gt25_train)
gt25_dev = np.nan_to_num(gt25_dev)
gt25_test = np.nan_to_num(gt25_test)

In [9]:
grid_results = gridsearch.fit(gt25_train, train_labels)
best_params = grid_results.best_params_
decision_tree = grid_results.best_estimator_
print(best_params)

{'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_split': 10, 'splitter': 'random'}


In [10]:
decision_tree = decision_tree.fit(gt25_train, train_labels)

In [11]:
train_preds = decision_tree.predict(gt25_train)
dev_preds = decision_tree.predict(gt25_dev)
test_preds = decision_tree.predict(gt25_test)

In [12]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9129250505228012
Accuracy Dev:  0.9036229335209286
Accuracy Test:  0.9111033028812369
F1 Train:  0.31883773636639007
F1 Dev:  0.31645725548164577
F1 Test:  0.31782803211374644
Precision Train:  0.6376391329818395
Precision Dev:  0.3012076445069762
Precision Test:  0.3037011009604123
Recall Train:  0.3336731226639484
Recall Dev:  0.3333333333333333
Recall Test:  0.3333333333333333
Confusion Matrix Train: 
[[    2  1960     0]
 [    0 20778     0]
 [    0    22     0]]
Confusion Matrix Dev: 
[[   0  272    0]
 [   0 2569    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[   0  250    0]
 [   0 2593    0]
 [   0    3    0]]


C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision

### FastText 300 

In [13]:
ft300_train, ft300_dev, ft300_test = load_fasttext_300()

In [14]:
# Set all NaN values to 0
ft300_train = np.nan_to_num(ft300_train)
ft300_dev = np.nan_to_num(ft300_dev)
ft300_test = np.nan_to_num(ft300_test)

In [15]:
grid_results = gridsearch.fit(ft300_train, train_labels)
best_params = grid_results.best_params_
decision_tree = grid_results.best_estimator_
print(best_params)

{'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_split': 5, 'splitter': 'random'}


In [16]:
decision_tree = decision_tree.fit(ft300_train, train_labels)

In [17]:
train_preds = decision_tree.predict(ft300_train)
dev_preds = decision_tree.predict(ft300_dev)
test_preds = decision_tree.predict(ft300_test)

In [18]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9131007820050963
Accuracy Dev:  0.9036229335209286
Accuracy Test:  0.9111033028812369
F1 Train:  0.4217687836183332
F1 Dev:  0.31645725548164577
F1 Test:  0.31782803211374644
Precision Train:  0.8877047259089977
Precision Dev:  0.3012076445069762
Precision Test:  0.3037011009604123
Recall Train:  0.39443303532614654
Recall Dev:  0.3333333333333333
Recall Test:  0.3333333333333333
Confusion Matrix Train: 
[[    3  1959     0]
 [    1 20777     0]
 [    0    18     4]]
Confusion Matrix Dev: 
[[   0  272    0]
 [   0 2569    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[   0  250    0]
 [   0 2593    0]
 [   0    3    0]]


C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Word2Vec 300

In [19]:
w2v300_train, w2v300_dev, w2v300_test = load_word2vec_300()

In [20]:
# Set all NaN values to 0
w2v300_train = np.nan_to_num(w2v300_train)
w2v300_dev = np.nan_to_num(w2v300_dev)
w2v300_test = np.nan_to_num(w2v300_test)

In [21]:
grid_results = gridsearch.fit(w2v300_train, train_labels)
best_params = grid_results.best_params_
decision_tree = grid_results.best_estimator_
print(best_params)

{'criterion': 'entropy', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_split': 10, 'splitter': 'best'}


In [22]:
decision_tree = decision_tree.fit(w2v300_train, train_labels)

In [23]:
train_preds = decision_tree.predict(w2v300_train)
dev_preds = decision_tree.predict(w2v300_dev)
test_preds = decision_tree.predict(w2v300_test)

In [24]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9130129162639486
Accuracy Dev:  0.9036229335209286
Accuracy Test:  0.9104005621925509
F1 Train:  0.4344668368046411
F1 Dev:  0.31645725548164577
F1 Test:  0.3176997118508982
Precision Train:  0.7329644887671968
Precision Dev:  0.3012076445069762
Precision Test:  0.30368026254102204
Recall Train:  0.4096902747062894
Recall Dev:  0.3333333333333333
Recall Test:  0.3330762308780049
Confusion Matrix Train: 
[[    4  1958     0]
 [    3 20773     2]
 [    0    17     5]]
Confusion Matrix Dev: 
[[   0  272    0]
 [   0 2569    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[   0  250    0]
 [   1 2591    1]
 [   0    3    0]]


C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### TF-IDF PCA (1000 Dims)

In [7]:
tfidf_pca_train, tfidf_pca_dev, tfidf_pca_test = load_tfidf_pca()

In [8]:
grid_results = gridsearch.fit(tfidf_pca_train, train_labels)
best_params = grid_results.best_params_
decision_tree = grid_results.best_estimator_
print(best_params)

In [ ]:
decision_tree = decision_tree.fit(tfidf_pca_train, train_labels)

In [ ]:
train_preds = decision_tree.predict(tfidf_pca_train)
dev_preds = decision_tree.predict(tfidf_pca_dev)
test_preds = decision_tree.predict(tfidf_pca_test)

In [ ]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9260170459537826
Accuracy Dev:  0.9060851213506859
Accuracy Test:  0.9114546732255797
F1 Train:  0.495687024158139
F1 Dev:  0.46626192408040185
F1 Test:  0.4625893576809945
Precision Train:  0.5321623773425325
Precision Dev:  0.49171866798856945
Precision Test:  0.49091571794921957
Recall Train:  0.48144035138924757
Recall Dev:  0.4492940909333761
Recall Test:  0.44430183828255565
Confusion Matrix Train: 
[[  833  1090    39]
 [  471 20244    63]
 [    0    21     1]]
Confusion Matrix Dev: 
[[ 105  165    2]
 [  90 2471    8]
 [   0    2    0]]
Confusion Matrix Test: 
[[  92  154    4]
 [  81 2502   10]
 [   0    3    0]]


### Sentence Transformer Faster No PCA

In [ ]:
train, dev, test = load_sent_trans_fast_no_pca()

In [ ]:
grid_results = gridsearch.fit(train, train_labels)
best_params = grid_results.best_params_
decision_tree = grid_results.best_estimator_
print(best_params)

In [ ]:
decision_tree = decision_tree.fit(train, train_labels)

In [ ]:
train_preds = decision_tree.predict(train)
dev_preds = decision_tree.predict(dev)
test_preds = decision_tree.predict(test)

In [ ]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9169229417450137
Accuracy Dev:  0.9074920858248329
Accuracy Test:  0.9167252283907238
F1 Train:  0.3542029696889917
F1 Dev:  0.34937899054295435
F1 Test:  0.3734899506114149
Precision Train:  0.5925699491412861
Precision Dev:  0.5771755269694573
Precision Test:  0.5616635101010101
Recall Train:  0.3519028742174077
Recall Dev:  0.35010093955838467
Recall Test:  0.36310014140635044
Confusion Matrix Train: 
[[  111  1851     0]
 [   18 20760     0]
 [    0    22     0]]
Confusion Matrix Dev: 
[[  14  258    0]
 [   3 2566    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  23  227    0]
 [   7 2586    0]
 [   0    3    0]]


c:\Kyode\clg\ml\ML_Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Kyode\clg\ml\ML_Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Kyode\clg\ml\ML_Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Sentence Transformer Faster PCA

In [ ]:
train, dev, test = load_sent_trans_fast_pca()

In [ ]:
grid_results = gridsearch.fit(train, train_labels)
best_params = grid_results.best_params_
decision_tree = grid_results.best_estimator_
print(best_params)

In [ ]:
decision_tree = decision_tree.fit(train, train_labels)

In [ ]:
train_preds = decision_tree.predict(train)
dev_preds = decision_tree.predict(dev)
test_preds = decision_tree.predict(test)

In [ ]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9221509533432914
Accuracy Dev:  0.9124164614843475
Accuracy Test:  0.9223471539002108
F1 Train:  0.4077915563624817
F1 Dev:  0.40242015423112165
F1 Test:  0.4244990220535703
Precision Train:  0.5607966386905193
Precision Dev:  0.5428436911487758
Precision Test:  0.5541845834480713
Recall Train:  0.38504391210455585
Recall Dev:  0.38259813462169606
Recall Test:  0.39768607790204397
Confusion Matrix Train: 
[[  314  1636    12]
 [  101 20676     1]
 [    0    22     0]]
Confusion Matrix Dev: 
[[  42  230    0]
 [  17 2552    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  50  199    1]
 [  18 2575    0]
 [   0    3    0]]


c:\Kyode\clg\ml\ML_Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Sentence Transformer Better No PCA

In [ ]:
train, dev, test = load_sent_trans_better_no_pca()

In [ ]:
grid_results = gridsearch.fit(train, train_labels)
best_params = grid_results.best_params_
decision_tree = grid_results.best_estimator_
print(best_params)

In [ ]:
decision_tree = decision_tree.fit(train, train_labels)

In [ ]:
train_preds = decision_tree.predict(train)
dev_preds = decision_tree.predict(dev)
test_preds = decision_tree.predict(test)

In [ ]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9280379580001757
Accuracy Dev:  0.9215617305663032
Accuracy Test:  0.9244553759662685
F1 Train:  0.49062131325026287
F1 Dev:  0.491946364227066
F1 Test:  0.4961027624687639
Precision Train:  0.5259863782306411
Precision Dev:  0.5260017342095655
Precision Test:  0.5171391563803459
Recall Train:  0.4682736553178208
Recall Dev:  0.47034351887894116
Recall Test:  0.4803825684535287
Confusion Matrix Train: 
[[  841  1112     9]
 [  492 20283     3]
 [    0    22     0]]
Confusion Matrix Dev: 
[[ 119  153    0]
 [  68 2501    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 118  131    1]
 [  78 2513    2]
 [   0    3    0]]


c:\Kyode\clg\ml\ML_Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Sentence Transformer Better PCA

In [ ]:
train, dev, test = load_sent_trans_better_pca()

In [ ]:
grid_results = gridsearch.fit(train, train_labels)
best_params = grid_results.best_params_
decision_tree = grid_results.best_estimator_
print(best_params)

In [ ]:
decision_tree = decision_tree.fit(train, train_labels)

In [ ]:
train_preds = decision_tree.predict(train)
dev_preds = decision_tree.predict(dev)
test_preds = decision_tree.predict(test)

In [ ]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.8921008698708374
Accuracy Dev:  0.8793527963418923
Accuracy Test:  0.8903724525650035
F1 Train:  0.5393647762286241
F1 Dev:  0.4762443582331762
F1 Test:  0.4907040375334903
Precision Train:  0.5060246695278755
Precision Dev:  0.45801318846521805
Precision Test:  0.46707986534296103
Recall Train:  0.5983692163729094
Recall Dev:  0.5073686831680901
Recall Test:  0.5353808972875691
Confusion Matrix Train: 
[[ 1280   672    10]
 [ 1733 19021    24]
 [    0    17     5]]
Confusion Matrix Dev: 
[[ 167  104    1]
 [ 233 2333    3]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 174   74    2]
 [ 228 2360    5]
 [   0    3    0]]
