In [1]:
from embeddings_loader import *
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import roc_auc_score


In [2]:
train_labels, dev_labels, test_labels = load_labels()

In [3]:
def computeAllScores(y_pred_train, y_pred_dev, y_pred_test):
    print("Accuracy Train: ", accuracy_score(train_labels, y_pred_train))
    print("Accuracy Dev: ", accuracy_score(dev_labels, y_pred_dev))
    print("Accuracy Test: ", accuracy_score(test_labels, y_pred_test))
    print("F1 Train: ", f1_score(train_labels, y_pred_train, average='macro'))
    print("F1 Dev: ", f1_score(dev_labels, y_pred_dev, average='macro'))
    print("F1 Test: ", f1_score(test_labels, y_pred_test, average='macro'))
    print("Precision Train: ", precision_score(train_labels, y_pred_train, average='macro'))
    print("Precision Dev: ", precision_score(dev_labels, y_pred_dev, average='macro'))
    print("Precision Test: ", precision_score(test_labels, y_pred_test, average='macro'))
    print("Recall Train: ", recall_score(train_labels, y_pred_train, average='macro'))
    print("Recall Dev: ", recall_score(dev_labels, y_pred_dev, average='macro'))
    print("Recall Test: ", recall_score(test_labels, y_pred_test, average='macro'))
    # Confusion Matrix
    print("Confusion Matrix Train: ")
    print(confusion_matrix(train_labels, y_pred_train))
    print("Confusion Matrix Dev: ")
    print(confusion_matrix(dev_labels, y_pred_dev))
    print("Confusion Matrix Test: ")
    print(confusion_matrix(test_labels, y_pred_test))

In [4]:
label_replacement = {
    'Hope_speech': 0,
    'Non_hope_speech': 1,
    'not-English': 2,
}

In [5]:
# Replace labels with numbers
train_labels = [label_replacement[label] for label in train_labels]
dev_labels = [label_replacement[label] for label in dev_labels]
test_labels = [label_replacement[label] for label in test_labels]

In [6]:
decision_tree = DecisionTreeClassifier()
gridsearch = GridSearchCV(decision_tree, param_grid = {
    "criterion": ["gini", "entropy"],
    "max_depth": [5, 10, 15, 20],
    "max_features": ["sqrt", "log2", None],
    "splitter": ["best", "random"],
    "min_samples_split": [2, 5, 10],

}, scoring = "f1_micro")

### Glove Twitter 25

In [7]:
gt25_train, gt25_dev, gt25_test = load_glove_twitter_25()

In [8]:
# Set all NaN values to 0
gt25_train = np.nan_to_num(gt25_train)
gt25_dev = np.nan_to_num(gt25_dev)
gt25_test = np.nan_to_num(gt25_test)

In [9]:
grid_results = gridsearch.fit(gt25_train, train_labels)
best_params = grid_results.best_params_
decision_tree = grid_results.best_estimator_
print(best_params)

{'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_split': 10, 'splitter': 'random'}


In [10]:
decision_tree = decision_tree.fit(gt25_train, train_labels)

In [11]:
train_preds = decision_tree.predict(gt25_train)
dev_preds = decision_tree.predict(gt25_dev)
test_preds = decision_tree.predict(gt25_test)

In [12]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9129250505228012
Accuracy Dev:  0.9036229335209286
Accuracy Test:  0.9111033028812369
F1 Train:  0.31883773636639007
F1 Dev:  0.31645725548164577
F1 Test:  0.31782803211374644
Precision Train:  0.6376391329818395
Precision Dev:  0.3012076445069762
Precision Test:  0.3037011009604123
Recall Train:  0.3336731226639484
Recall Dev:  0.3333333333333333
Recall Test:  0.3333333333333333
Confusion Matrix Train: 
[[    2  1960     0]
 [    0 20778     0]
 [    0    22     0]]
Confusion Matrix Dev: 
[[   0  272    0]
 [   0 2569    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[   0  250    0]
 [   0 2593    0]
 [   0    3    0]]


C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision

### FastText 300 

In [13]:
ft300_train, ft300_dev, ft300_test = load_fasttext_300()

In [14]:
# Set all NaN values to 0
ft300_train = np.nan_to_num(ft300_train)
ft300_dev = np.nan_to_num(ft300_dev)
ft300_test = np.nan_to_num(ft300_test)

In [15]:
grid_results = gridsearch.fit(ft300_train, train_labels)
best_params = grid_results.best_params_
decision_tree = grid_results.best_estimator_
print(best_params)

{'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_split': 5, 'splitter': 'random'}


In [16]:
decision_tree = decision_tree.fit(ft300_train, train_labels)

In [17]:
train_preds = decision_tree.predict(ft300_train)
dev_preds = decision_tree.predict(ft300_dev)
test_preds = decision_tree.predict(ft300_test)

In [18]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9131007820050963
Accuracy Dev:  0.9036229335209286
Accuracy Test:  0.9111033028812369
F1 Train:  0.4217687836183332
F1 Dev:  0.31645725548164577
F1 Test:  0.31782803211374644
Precision Train:  0.8877047259089977
Precision Dev:  0.3012076445069762
Precision Test:  0.3037011009604123
Recall Train:  0.39443303532614654
Recall Dev:  0.3333333333333333
Recall Test:  0.3333333333333333
Confusion Matrix Train: 
[[    3  1959     0]
 [    1 20777     0]
 [    0    18     4]]
Confusion Matrix Dev: 
[[   0  272    0]
 [   0 2569    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[   0  250    0]
 [   0 2593    0]
 [   0    3    0]]


C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Word2Vec 300

In [19]:
w2v300_train, w2v300_dev, w2v300_test = load_word2vec_300()

In [20]:
# Set all NaN values to 0
w2v300_train = np.nan_to_num(w2v300_train)
w2v300_dev = np.nan_to_num(w2v300_dev)
w2v300_test = np.nan_to_num(w2v300_test)

In [21]:
grid_results = gridsearch.fit(w2v300_train, train_labels)
best_params = grid_results.best_params_
decision_tree = grid_results.best_estimator_
print(best_params)

{'criterion': 'entropy', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_split': 10, 'splitter': 'best'}


In [22]:
decision_tree = decision_tree.fit(w2v300_train, train_labels)

In [23]:
train_preds = decision_tree.predict(w2v300_train)
dev_preds = decision_tree.predict(w2v300_dev)
test_preds = decision_tree.predict(w2v300_test)

In [24]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9130129162639486
Accuracy Dev:  0.9036229335209286
Accuracy Test:  0.9104005621925509
F1 Train:  0.4344668368046411
F1 Dev:  0.31645725548164577
F1 Test:  0.3176997118508982
Precision Train:  0.7329644887671968
Precision Dev:  0.3012076445069762
Precision Test:  0.30368026254102204
Recall Train:  0.4096902747062894
Recall Dev:  0.3333333333333333
Recall Test:  0.3330762308780049
Confusion Matrix Train: 
[[    4  1958     0]
 [    3 20773     2]
 [    0    17     5]]
Confusion Matrix Dev: 
[[   0  272    0]
 [   0 2569    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[   0  250    0]
 [   1 2591    1]
 [   0    3    0]]


C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### TF-IDF PCA (1000 Dims)

In [27]:
tfidf_pca_train, tfidf_pca_dev, tfidf_pca_test = load_tfidf_pca()

In [28]:
grid_results = gridsearch.fit(tfidf_pca_train, train_labels)
best_params = grid_results.best_params_
decision_tree = grid_results.best_estimator_
print(best_params)

{'criterion': 'entropy', 'max_depth': 5, 'max_features': None, 'min_samples_split': 5, 'splitter': 'best'}


In [29]:
decision_tree = decision_tree.fit(tfidf_pca_train, train_labels)

In [30]:
train_preds = decision_tree.predict(tfidf_pca_train)
dev_preds = decision_tree.predict(tfidf_pca_dev)
test_preds = decision_tree.predict(tfidf_pca_test)

In [31]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9182409278622266
Accuracy Dev:  0.9092507914175167
Accuracy Test:  0.9153197470133521
F1 Train:  0.37483681358451854
F1 Dev:  0.37539487216426365
F1 Test:  0.3800923563995895
Precision Train:  0.5563618556290109
Precision Dev:  0.5408230915970854
Precision Test:  0.5207526662590857
Recall Train:  0.36376920464668533
Recall Dev:  0.36499429472061307
Recall Test:  0.36740506491837
Confusion Matrix Train: 
[[  185  1777     0]
 [   62 20716     0]
 [    0    22     0]]
Confusion Matrix Dev: 
[[  27  245    0]
 [  11 2558    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  27  223    0]
 [  15 2578    0]
 [   0    3    0]]


C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision

### Sentence Transformer Faster No PCA

In [7]:
train, dev, test = load_sent_trans_fast_no_pca()

In [8]:
grid_results = gridsearch.fit(train, train_labels)
best_params = grid_results.best_params_
decision_tree = grid_results.best_estimator_
print(best_params)

{'criterion': 'entropy', 'max_depth': 5, 'max_features': None, 'min_samples_split': 2, 'splitter': 'best'}


In [9]:
decision_tree = decision_tree.fit(train, train_labels)

In [10]:
train_preds = decision_tree.predict(train)
dev_preds = decision_tree.predict(dev)
test_preds = decision_tree.predict(test)

In [11]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9180212635093578
Accuracy Dev:  0.9046781568765389
Accuracy Test:  0.9139142656359803
F1 Train:  0.4808279140274286
F1 Dev:  0.36337297548523617
F1 Test:  0.36140608858320844
Precision Train:  0.8733636720464774
Precision Dev:  0.4822165352274508
Precision Test:  0.5198215553077157
Recall Train:  0.42653866261227963
Recall Dev:  0.35782882635342966
Recall Test:  0.3560478210566911
Confusion Matrix Train: 
[[  200  1762     0]
 [   86 20692     0]
 [    0    18     4]]
Confusion Matrix Dev: 
[[  22  250    0]
 [  19 2550    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  18  232    0]
 [  10 2583    0]
 [   0    3    0]]


C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Sentence Transformer Faster PCA

In [12]:
train, dev, test = load_sent_trans_fast_pca()

In [13]:
grid_results = gridsearch.fit(train, train_labels)
best_params = grid_results.best_params_
decision_tree = grid_results.best_estimator_
print(best_params)

{'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_split': 10, 'splitter': 'best'}


In [14]:
decision_tree = decision_tree.fit(train, train_labels)

In [15]:
train_preds = decision_tree.predict(train)
dev_preds = decision_tree.predict(dev)
test_preds = decision_tree.predict(test)

In [16]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9266321061418153
Accuracy Dev:  0.9120647203658108
Accuracy Test:  0.9139142656359803
F1 Train:  0.4420849668118629
F1 Dev:  0.41751023768386314
F1 Test:  0.41689146561663804
Precision Train:  0.559798244873722
Precision Dev:  0.522099333633684
Precision Test:  0.4897173428995547
Recall Train:  0.4112965872218999
Recall Dev:  0.394521500698372
Recall Test:  0.39580563054377166
Confusion Matrix Train: 
[[  474  1488     0]
 [  160 20618     0]
 [    0    22     0]]
Confusion Matrix Dev: 
[[  53  219    0]
 [  29 2540    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  51  199    0]
 [  43 2550    0]
 [   0    3    0]]


C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision

### Sentence Transformer Better No PCA

In [17]:
train, dev, test = load_sent_trans_better_no_pca()

In [18]:
grid_results = gridsearch.fit(train, train_labels)
best_params = grid_results.best_params_
decision_tree = grid_results.best_estimator_
print(best_params)

{'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_split': 5, 'splitter': 'random'}


In [19]:
decision_tree = decision_tree.fit(train, train_labels)

In [20]:
train_preds = decision_tree.predict(train)
dev_preds = decision_tree.predict(dev)
test_preds = decision_tree.predict(test)

In [21]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9187681223091116
Accuracy Dev:  0.9064368624692226
Accuracy Test:  0.9167252283907238
F1 Train:  0.3929046269552398
F1 Dev:  0.37513671389510317
F1 Test:  0.39200717510979155
Precision Train:  0.532760427518438
Precision Dev:  0.4984396740210693
Precision Test:  0.527105388650453
Recall Train:  0.3755006201670414
Recall Dev:  0.36505201535655135
Recall Test:  0.37514796246304155
Confusion Matrix Train: 
[[  260  1702     0]
 [  125 20653     0]
 [    0    22     0]]
Confusion Matrix Dev: 
[[  28  244    0]
 [  20 2549    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  33  217    0]
 [  17 2576    0]
 [   0    3    0]]


C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision

### Sentence Transformer Better PCA

In [22]:
train, dev, test = load_sent_trans_better_pca()

In [23]:
grid_results = gridsearch.fit(train, train_labels)
best_params = grid_results.best_params_
decision_tree = grid_results.best_estimator_
print(best_params)

{'criterion': 'entropy', 'max_depth': 5, 'max_features': None, 'min_samples_split': 2, 'splitter': 'best'}


In [24]:
decision_tree = decision_tree.fit(train, train_labels)

In [25]:
train_preds = decision_tree.predict(train)
dev_preds = decision_tree.predict(dev)
test_preds = decision_tree.predict(test)

In [26]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9217994903787013
Accuracy Dev:  0.9096025325360535
Accuracy Test:  0.9198875614898102
F1 Train:  0.44656542151917433
F1 Dev:  0.4319788842200489
F1 Test:  0.44912891986062714
Precision Train:  0.5166700595203474
Precision Dev:  0.49890471203750736
Precision Test:  0.5128895709365521
Recall Train:  0.4199938400305585
Recall Dev:  0.40895356780314307
Recall Test:  0.4232914256331148
Confusion Matrix Train: 
[[  542  1420     0]
 [  338 20440     0]
 [    0    22     0]]
Confusion Matrix Dev: 
[[  67  205    0]
 [  50 2519    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  72  178    0]
 [  47 2546    0]
 [   0    3    0]]


C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision