In [1]:
from embeddings_loader import *
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import roc_auc_score
from utils import *


In [2]:
train_labels, dev_labels, test_labels = load_labels()

In [3]:
label_replacement = {
    'Hope_speech': 0,
    'Non_hope_speech': 1,
    'not-English': 2,
}

In [4]:
# Replace labels with numbers
train_labels = [label_replacement[label] for label in train_labels]
dev_labels = [label_replacement[label] for label in dev_labels]
test_labels = [label_replacement[label] for label in test_labels]

In [5]:
decision_tree = DecisionTreeClassifier()
gridsearch = GridSearchCV(decision_tree, param_grid = {
    "criterion": ["gini", "entropy"],
    "max_depth": [5, 10, 15, 20],
    "max_features": ["sqrt", "log2", None],
    "splitter": ["best", "random"],
    "min_samples_split": [2, 5, 10],

}, scoring = "f1_micro")

### Glove Twitter 25

In [6]:
gt25_train, gt25_dev, gt25_test = load_glove_twitter_25()

In [7]:
# Set all NaN values to 0
gt25_train = np.nan_to_num(gt25_train)
gt25_dev = np.nan_to_num(gt25_dev)
gt25_test = np.nan_to_num(gt25_test)

In [8]:
grid_results = gridsearch.fit(gt25_train, train_labels)
best_params = grid_results.best_params_
decision_tree = grid_results.best_estimator_
print(best_params)

{'criterion': 'entropy', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_split': 2, 'splitter': 'best'}


In [9]:
decision_tree = decision_tree.fit(gt25_train, train_labels)
save_model(decision_tree, "decision_tree_gt25.joblib")

In [10]:
train_preds = decision_tree.predict(gt25_train)
dev_preds = decision_tree.predict(gt25_dev)
test_preds = decision_tree.predict(gt25_test)

In [11]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.91314471487567
Accuracy Dev:  0.9036229335209286
Accuracy Test:  0.9111033028812369
Weighted F1 Train:  0.8719423440595522
Weighted F1 Dev:  0.85787410059692
Weighted F1 Test:  0.8687225094212346
Macro F1 Train:  0.4217773062704073
Macro F1 Dev:  0.31645725548164577
Macro F1 Test:  0.31782803211374644
Micro F1 Train:  0.91314471487567
Micro F1 Dev:  0.9036229335209286
Micro F1 Test:  0.9111033028812369
Weighted Recall Train:  0.91314471487567
Weighted Recall Dev:  0.9036229335209286
Weighted Recall Test:  0.9111033028812369
Macro Recall Train:  0.39444907793531647
Macro Recall Dev:  0.3333333333333333
Macro Recall Test:  0.3333333333333333
Micro Recall Train:  0.91314471487567
Micro Recall Dev:  0.9036229335209286
Micro Recall Test:  0.9111033028812369
Confusion Matrix Train: 
[[    3  1959     0]
 [    0 20778     0]
 [    0    18     4]]
Confusion Matrix Dev: 
[[   0  272    0]
 [   0 2569    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[   0  250    0]
 [   0 25

### FastText 300 

In [12]:
ft300_train, ft300_dev, ft300_test = load_fasttext_300()

In [13]:
# Set all NaN values to 0
ft300_train = np.nan_to_num(ft300_train)
ft300_dev = np.nan_to_num(ft300_dev)
ft300_test = np.nan_to_num(ft300_test)

In [14]:
grid_results = gridsearch.fit(ft300_train, train_labels)
best_params = grid_results.best_params_
decision_tree = grid_results.best_estimator_
print(best_params)

{'criterion': 'entropy', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_split': 10, 'splitter': 'random'}


In [15]:
decision_tree = decision_tree.fit(ft300_train, train_labels)
save_model(decision_tree, "decision_tree_ft300.joblib")

In [16]:
train_preds = decision_tree.predict(ft300_train)
dev_preds = decision_tree.predict(ft300_dev)
test_preds = decision_tree.predict(ft300_test)

In [17]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9130129162639486
Accuracy Dev:  0.9032711924023918
Accuracy Test:  0.9107519325368939
Weighted F1 Train:  0.8716414984714669
Weighted F1 Dev:  0.8576986484131379
Weighted F1 Test:  0.8685471721471739
Macro F1 Train:  0.3985130818712892
Macro F1 Dev:  0.31639253372759196
Macro F1 Test:  0.3177638837808018
Micro F1 Train:  0.9130129162639486
Micro F1 Dev:  0.9032711924023918
Micro F1 Test:  0.9107519325368939
Weighted Recall Train:  0.9130129162639486
Weighted Recall Dev:  0.9032711924023918
Weighted Recall Test:  0.9107519325368939
Macro Recall Train:  0.3789577734531863
Macro Recall Dev:  0.33320358115998444
Macro Recall Test:  0.3332047821056691
Micro Recall Train:  0.9130129162639486
Micro Recall Dev:  0.9032711924023918
Micro Recall Test:  0.9107519325368939
Confusion Matrix Train: 
[[    1  1961     0]
 [    0 20778     0]
 [    0    19     3]]
Confusion Matrix Dev: 
[[   0  272    0]
 [   1 2568    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[   0  250    0]


### Word2Vec 300

In [18]:
w2v300_train, w2v300_dev, w2v300_test = load_word2vec_300()

In [19]:
# Set all NaN values to 0
w2v300_train = np.nan_to_num(w2v300_train)
w2v300_dev = np.nan_to_num(w2v300_dev)
w2v300_test = np.nan_to_num(w2v300_test)

In [20]:
grid_results = gridsearch.fit(w2v300_train, train_labels)
best_params = grid_results.best_params_
decision_tree = grid_results.best_estimator_
print(best_params)

{'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_split': 5, 'splitter': 'random'}


In [21]:
decision_tree = decision_tree.fit(w2v300_train, train_labels)
save_model(decision_tree, "decision_tree_w2v300.joblib")

In [22]:
train_preds = decision_tree.predict(w2v300_train)
dev_preds = decision_tree.predict(w2v300_dev)
test_preds = decision_tree.predict(w2v300_test)

In [23]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.91314471487567
Accuracy Dev:  0.9036229335209286
Accuracy Test:  0.9107519325368939
Weighted F1 Train:  0.8721121056341143
Weighted F1 Dev:  0.85787410059692
Weighted F1 Test:  0.8685471721471739
Macro F1 Train:  0.4151331732092756
Macro F1 Dev:  0.31645725548164577
Macro F1 Test:  0.3177638837808018
Micro F1 Train:  0.91314471487567
Micro F1 Dev:  0.9036229335209286
Micro F1 Test:  0.9107519325368939
Weighted Recall Train:  0.91314471487567
Weighted Recall Dev:  0.9036229335209286
Weighted Recall Test:  0.9107519325368939
Macro Recall Train:  0.3947567820475916
Macro Recall Dev:  0.3333333333333333
Macro Recall Test:  0.3332047821056691
Micro Recall Train:  0.91314471487567
Micro Recall Dev:  0.9036229335209286
Micro Recall Test:  0.9107519325368939
Confusion Matrix Train: 
[[    5  1956     1]
 [    1 20776     1]
 [    0    18     4]]
Confusion Matrix Dev: 
[[   0  272    0]
 [   0 2569    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[   0  250    0]
 [   0 2592

### TF-IDF PCA (1000 Dims)

In [6]:
tfidf_pca_train, tfidf_pca_dev, tfidf_pca_test = load_tfidf_pca()

In [7]:
grid_results = gridsearch.fit(tfidf_pca_train, train_labels)
best_params = grid_results.best_params_
decision_tree = grid_results.best_estimator_
print(best_params)

{'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_split': 2, 'splitter': 'random'}


In [8]:
decision_tree = decision_tree.fit(tfidf_pca_train, train_labels)
save_model(decision_tree, "decision_tree_tfidf_pca.joblib")

In [9]:
train_preds = decision_tree.predict(tfidf_pca_train)
dev_preds = decision_tree.predict(tfidf_pca_dev)
test_preds = decision_tree.predict(tfidf_pca_test)

In [10]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9150338283103417
Accuracy Dev:  0.9036229335209286
Accuracy Test:  0.9065354884047786
Weighted F1 Train:  0.8818635178226591
Weighted F1 Dev:  0.8676728921839489
Weighted F1 Test:  0.8689652720449805
Macro F1 Train:  0.35618493820601776
Macro F1 Dev:  0.3514445966216657
Macro F1 Test:  0.32680822932260334
Micro F1 Train:  0.9150338283103419
Micro F1 Dev:  0.9036229335209286
Micro F1 Test:  0.9065354884047786
Weighted Recall Train:  0.9150338283103417
Weighted Recall Dev:  0.9036229335209286
Weighted Recall Test:  0.9065354884047786
Macro Recall Train:  0.3529054146406127
Macro Recall Dev:  0.3508651416970057
Macro Recall Test:  0.3364812957963748
Micro Recall Train:  0.9150338283103417
Micro Recall Dev:  0.9036229335209286
Micro Recall Test:  0.9065354884047786
Confusion Matrix Train: 
[[  122  1840     0]
 [   72 20706     0]
 [    0    22     0]]
Confusion Matrix Dev: 
[[  16  256    0]
 [  16 2553    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[   4  246    0]


### Sentence Transformer Faster No PCA

In [11]:
train, dev, test = load_sent_trans_fast_no_pca()

In [12]:
grid_results = gridsearch.fit(train, train_labels)
best_params = grid_results.best_params_
decision_tree = grid_results.best_estimator_
print(best_params)

{'criterion': 'entropy', 'max_depth': 5, 'max_features': None, 'min_samples_split': 2, 'splitter': 'best'}


In [13]:
decision_tree = decision_tree.fit(train, train_labels)
save_model(decision_tree, "decision_tree_sent_trans_fast_no_pca.joblib")

In [14]:
train_preds = decision_tree.predict(train)
dev_preds = decision_tree.predict(dev)
test_preds = decision_tree.predict(test)

In [15]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9180212635093578
Accuracy Dev:  0.9046781568765389
Accuracy Test:  0.9139142656359803
Weighted F1 Train:  0.8890880832043696
Weighted F1 Dev:  0.8714789179030115
Weighted F1 Test:  0.8812255415131175
Macro F1 Train:  0.4808279140274286
Macro F1 Dev:  0.36337297548523617
Macro F1 Test:  0.36140608858320844
Micro F1 Train:  0.9180212635093578
Micro F1 Dev:  0.9046781568765389
Micro F1 Test:  0.9139142656359803
Weighted Recall Train:  0.9180212635093578
Weighted Recall Dev:  0.9046781568765389
Weighted Recall Test:  0.9139142656359803
Macro Recall Train:  0.42653866261227963
Macro Recall Dev:  0.35782882635342966
Macro Recall Test:  0.3560478210566911
Micro Recall Train:  0.9180212635093578
Micro Recall Dev:  0.9046781568765389
Micro Recall Test:  0.9139142656359803
Confusion Matrix Train: 
[[  200  1762     0]
 [   86 20692     0]
 [    0    18     4]]
Confusion Matrix Dev: 
[[  22  250    0]
 [  19 2550    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  18  232    0

### Sentence Transformer Faster PCA

In [18]:
train, dev, test = load_sent_trans_fast_pca()

In [19]:
grid_results = gridsearch.fit(train, train_labels)
best_params = grid_results.best_params_
decision_tree = grid_results.best_estimator_
print(best_params)

{'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_split': 10, 'splitter': 'best'}


In [20]:
decision_tree = decision_tree.fit(train, train_labels)
save_model(decision_tree, "decision_tree_sent_trans_fast_pca")

In [21]:
train_preds = decision_tree.predict(train)
dev_preds = decision_tree.predict(dev)
test_preds = decision_tree.predict(test)

In [22]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9266321061418153
Accuracy Dev:  0.9120647203658108
Accuracy Test:  0.9139142656359803
Weighted F1 Train:  0.9087843865753925
Weighted F1 Dev:  0.8898871410279732
Weighted F1 Test:  0.8953871984700564
Macro F1 Train:  0.4420849668118629
Macro F1 Dev:  0.41751023768386314
Macro F1 Test:  0.41689146561663804
Micro F1 Train:  0.9266321061418153
Micro F1 Dev:  0.9120647203658108
Micro F1 Test:  0.9139142656359803
Weighted Recall Train:  0.9266321061418153
Weighted Recall Dev:  0.9120647203658108
Weighted Recall Test:  0.9139142656359803
Macro Recall Train:  0.4112965872218999
Macro Recall Dev:  0.394521500698372
Macro Recall Test:  0.39580563054377166
Micro Recall Train:  0.9266321061418153
Micro Recall Dev:  0.9120647203658108
Micro Recall Test:  0.9139142656359803
Confusion Matrix Train: 
[[  474  1488     0]
 [  160 20618     0]
 [    0    22     0]]
Confusion Matrix Dev: 
[[  53  219    0]
 [  29 2540    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  51  199    0]


### Sentence Transformer Better No PCA

In [23]:
train, dev, test = load_sent_trans_better_no_pca()

In [24]:
grid_results = gridsearch.fit(train, train_labels)
best_params = grid_results.best_params_
decision_tree = grid_results.best_estimator_
print(best_params)

{'criterion': 'entropy', 'max_depth': 5, 'max_features': None, 'min_samples_split': 2, 'splitter': 'best'}


In [25]:
decision_tree = decision_tree.fit(train, train_labels)
save_model(decision_tree, "decision_tree_sent_trans_better_no_pca.joblib")

In [26]:
train_preds = decision_tree.predict(train)
dev_preds = decision_tree.predict(dev)
test_preds = decision_tree.predict(test)

In [27]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9206133028732097
Accuracy Dev:  0.9074920858248329
Accuracy Test:  0.9205903021784961
Weighted F1 Train:  0.8969380939532107
Weighted F1 Dev:  0.8811736807096866
Weighted F1 Test:  0.8980599647297248
Macro F1 Train:  0.4059029302826489
Macro F1 Dev:  0.3936278770720023
Macro F1 Test:  0.4151670818753486
Micro F1 Train:  0.9206133028732097
Micro F1 Dev:  0.9074920858248328
Micro F1 Test:  0.920590302178496
Weighted Recall Train:  0.9206133028732097
Weighted Recall Dev:  0.9074920858248329
Weighted Recall Test:  0.9205903021784961
Macro Recall Train:  0.38432856872746984
Macro Recall Dev:  0.37749439012662284
Macro Recall Test:  0.3910194112353773
Micro Recall Train:  0.9206133028732097
Micro Recall Dev:  0.9074920858248329
Micro Recall Test:  0.9205903021784961
Confusion Matrix Train: 
[[  313  1649     0]
 [  136 20642     0]
 [    0    22     0]]
Confusion Matrix Dev: 
[[  39  233    0]
 [  28 2541    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  45  205    0]
 

### Sentence Transformer Better PCA

In [6]:
train, dev, test = load_sent_trans_better_pca()

In [7]:
grid_results = gridsearch.fit(train, train_labels)
best_params = grid_results.best_params_
decision_tree = grid_results.best_estimator_
print(best_params)

{'criterion': 'entropy', 'max_depth': 5, 'max_features': None, 'min_samples_split': 2, 'splitter': 'best'}


In [8]:
decision_tree = decision_tree.fit(train, train_labels)
save_model(decision_tree, "decision_tree_sent_trans_better_pca.joblib")

In [9]:
train_preds = decision_tree.predict(train)
dev_preds = decision_tree.predict(dev)
test_preds = decision_tree.predict(test)

In [10]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9217994903787013
Accuracy Dev:  0.9096025325360535
Accuracy Test:  0.9198875614898102
Weighted F1 Train:  0.907625929126145
Weighted F1 Dev:  0.8927213373089214
Weighted F1 Test:  0.9063360520664737
Macro F1 Train:  0.44656542151917433
Macro F1 Dev:  0.4319788842200489
Macro F1 Test:  0.44912891986062714
Micro F1 Train:  0.9217994903787015
Micro F1 Dev:  0.9096025325360535
Micro F1 Test:  0.9198875614898102
Weighted Recall Train:  0.9217994903787013
Weighted Recall Dev:  0.9096025325360535
Weighted Recall Test:  0.9198875614898102
Macro Recall Train:  0.4199938400305585
Macro Recall Dev:  0.40895356780314307
Macro Recall Test:  0.4232914256331148
Micro Recall Train:  0.9217994903787013
Micro Recall Dev:  0.9096025325360535
Micro Recall Test:  0.9198875614898102
Confusion Matrix Train: 
[[  542  1420     0]
 [  338 20440     0]
 [    0    22     0]]
Confusion Matrix Dev: 
[[  67  205    0]
 [  50 2519    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  72  178    0]
