In [22]:
from embeddings_loader import *
from sklearn_extra.cluster import KMedoids
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import roc_auc_score
from utils import *


In [23]:
train_labels, dev_labels, test_labels = load_labels()

In [24]:
label_replacement = {
    'Hope_speech': 0,
    'Non_hope_speech': 1,
    'not-English': 2,
}

In [25]:
# Replace labels with numbers
train_labels = [label_replacement[label] for label in train_labels]
dev_labels = [label_replacement[label] for label in dev_labels]
test_labels = [label_replacement[label] for label in test_labels]

### Glove Twitter 25

In [26]:
gt25_train, gt25_dev, gt25_test = load_glove_twitter_25()

In [27]:
# Set all NaN values to 0
gt25_train = np.nan_to_num(gt25_train)
gt25_dev = np.nan_to_num(gt25_dev)
gt25_test = np.nan_to_num(gt25_test)

In [28]:
k_medoids = KMedoids(n_clusters=3, random_state=0).fit(gt25_train, train_labels)
save_model(k_medoids, "k_medoids_gt25.joblib")

In [29]:
train_preds = k_medoids.predict(gt25_train)
dev_preds = k_medoids.predict(gt25_dev)
test_preds = k_medoids.predict(gt25_test)

In [30]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.39056321940075567
Accuracy Dev:  0.3939500527611678
Accuracy Test:  0.3882642304989459
Weighted F1 Train:  0.5223527450922112
Weighted F1 Dev:  0.5195456233834906
Weighted F1 Test:  0.5199517346530479
Macro F1 Train:  0.23299111756158597
Macro F1 Dev:  0.24149580109249755
Macro F1 Test:  0.2308150733779275
Micro F1 Train:  0.39056321940075567
Micro F1 Dev:  0.3939500527611678
Micro F1 Test:  0.3882642304989459
Weighted Recall Train:  0.39056321940075567
Weighted Recall Dev:  0.3939500527611678
Weighted Recall Test:  0.3882642304989459
Macro Recall Train:  0.2999336290008057
Macro Recall Dev:  0.2527047603782657
Macro Recall Test:  0.3445951064832669
Micro Recall Train:  0.39056321940075567
Micro Recall Dev:  0.3939500527611678
Micro Recall Test:  0.3882642304989459
Confusion Matrix Train: 
[[ 629  488  845]
 [6474 8257 6047]
 [   6   12    4]]
Confusion Matrix Dev: 
[[  98   75   99]
 [ 802 1022  745]
 [   0    2    0]]
Confusion Matrix Test: 
[[  76   63  111]
 [ 82

### FastText 300 

In [31]:
ft300_train, ft300_dev, ft300_test = load_fasttext_300()

In [32]:
# Set all NaN values to 0
ft300_train = np.nan_to_num(ft300_train)
ft300_dev = np.nan_to_num(ft300_dev)
ft300_test = np.nan_to_num(ft300_test)

In [33]:
k_medoids = KMedoids(n_clusters=3, random_state=0).fit(ft300_train, train_labels)
save_model(k_medoids, "k_medoids_ft300.joblib")

In [34]:
train_preds = k_medoids.predict(ft300_train)
dev_preds = k_medoids.predict(ft300_dev)
test_preds = k_medoids.predict(ft300_test)

In [35]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.30151129074773747
Accuracy Dev:  0.3119943721421034
Accuracy Test:  0.3021784961349262
Weighted F1 Train:  0.4109333008773261
Weighted F1 Dev:  0.4200063542529816
Weighted F1 Test:  0.408778787625074
Macro F1 Train:  0.18952357012854415
Macro F1 Dev:  0.19813893483270875
Macro F1 Test:  0.19204232944421282
Micro F1 Train:  0.30151129074773747
Micro F1 Dev:  0.3119943721421034
Micro F1 Test:  0.3021784961349262
Weighted Recall Train:  0.30151129074773747
Weighted Recall Dev:  0.3119943721421034
Weighted Recall Test:  0.3021784961349262
Macro Recall Train:  0.28628109207736036
Macro Recall Dev:  0.40982844091315
Macro Recall Test:  0.2527183442601877
Micro Recall Train:  0.30151129074773747
Micro Recall Dev:  0.3119943721421034
Micro Recall Test:  0.3021784961349262
Confusion Matrix Train: 
[[  850   651   461]
 [10313  6010  4455]
 [   12     7     3]]
Confusion Matrix Dev: 
[[ 117   80   75]
 [1267  769  533]
 [   0    1    1]]
Confusion Matrix Test: 
[[ 118   75   5

### Word2Vec 300

In [36]:
w2v300_train, w2v300_dev, w2v300_test = load_word2vec_300()

In [37]:
# Set all NaN values to 0
w2v300_train = np.nan_to_num(w2v300_train)
w2v300_dev = np.nan_to_num(w2v300_dev)
w2v300_test = np.nan_to_num(w2v300_test)

In [38]:
k_medoids = KMedoids(n_clusters=3, random_state=0).fit(w2v300_train, train_labels)
save_model(k_medoids, "k_medoids_w2v300.joblib")

In [39]:
train_preds = k_medoids.predict(w2v300_train)
dev_preds = k_medoids.predict(w2v300_dev)
test_preds = k_medoids.predict(w2v300_test)

In [40]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.3707494947719884
Accuracy Dev:  0.38199085473091804
Accuracy Test:  0.3713984539704849
Weighted F1 Train:  0.49738475737975885
Weighted F1 Dev:  0.5056663668221113
Weighted F1 Test:  0.49969592051483397
Macro F1 Train:  0.23889330096627073
Macro F1 Dev:  0.2492302440397095
Macro F1 Test:  0.23993587762796267
Micro F1 Train:  0.3707494947719884
Micro F1 Dev:  0.38199085473091804
Micro F1 Test:  0.3713984539704849
Weighted Recall Train:  0.3707494947719884
Weighted Recall Dev:  0.38199085473091804
Weighted Recall Test:  0.3713984539704849
Macro Recall Train:  0.35835533026148364
Macro Recall Dev:  0.442223551545959
Macro Recall Test:  0.2659951150533488
Micro Recall Train:  0.3707494947719884
Micro Recall Dev:  0.38199085473091804
Micro Recall Test:  0.3713984539704849
Confusion Matrix Train: 
[[ 859  374  729]
 [6313 7574 6891]
 [   5   11    6]]
Confusion Matrix Dev: 
[[123  47 102]
 [788 962 819]
 [  0   1   1]]
Confusion Matrix Test: 
[[108  36 106]
 [780 949 864]


### TF-IDF PCA (1000 Dims)

In [41]:
tfidf_pca_train, tfidf_pca_dev, tfidf_pca_test = load_tfidf_pca()

In [42]:
k_medoids = KMedoids(n_clusters=3, random_state=0).fit(tfidf_pca_train, train_labels)
save_model(k_medoids, "k_medoids_tfidf_pca.joblib")

In [43]:
train_preds = k_medoids.predict(tfidf_pca_train)
dev_preds = k_medoids.predict(tfidf_pca_dev)
test_preds = k_medoids.predict(tfidf_pca_test)

In [44]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.08619629206572357
Accuracy Dev:  0.09567358424199789
Accuracy Test:  0.08784258608573436
Weighted F1 Train:  0.013680401636705197
Weighted F1 Dev:  0.01670832418223013
Weighted F1 Test:  0.014186464161132811
Macro F1 Train:  0.05290406083158065
Macro F1 Dev:  0.05821294810058855
Macro F1 Test:  0.053832902670111975
Micro F1 Train:  0.08619629206572357
Micro F1 Dev:  0.09567358424199787
Micro F1 Test:  0.08784258608573436
Weighted Recall Train:  0.08619629206572357
Weighted Recall Dev:  0.09567358424199789
Weighted Recall Test:  0.08784258608573436
Macro Recall Train:  0.3333333333333333
Macro Recall Dev:  0.3333333333333333
Macro Recall Test:  0.3333333333333333
Micro Recall Train:  0.08619629206572357
Micro Recall Dev:  0.09567358424199789
Micro Recall Test:  0.08784258608573436
Confusion Matrix Train: 
[[ 1962     0     0]
 [20778     0     0]
 [   22     0     0]]
Confusion Matrix Dev: 
[[ 272    0    0]
 [2569    0    0]
 [   2    0    0]]
Confusion Matrix Test: 

### Sentence Transformer Faster No PCA

In [45]:
train, dev, test = load_sent_trans_fast_no_pca()

In [46]:
k_medoids = KMedoids(n_clusters=3, random_state=0).fit(train, train_labels)
save_model(k_medoids, "k_medoids_sent_trans_fast_no_pca.joblib")

In [47]:
train_preds = k_medoids.predict(train)
dev_preds = k_medoids.predict(dev)
test_preds = k_medoids.predict(test)

In [48]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.31644846674281696
Accuracy Dev:  0.31304959549771366
Accuracy Test:  0.2965565706254392
Weighted F1 Train:  0.44782182346252086
Weighted F1 Dev:  0.44114286442094347
Weighted F1 Test:  0.42876095687694726
Macro F1 Train:  0.18298117848784165
Macro F1 Dev:  0.18675427875503103
Macro F1 Test:  0.17231103347803547
Micro F1 Train:  0.31644846674281696
Micro F1 Dev:  0.31304959549771366
Micro F1 Test:  0.2965565706254392
Weighted Recall Train:  0.31644846674281696
Weighted Recall Dev:  0.31304959549771366
Weighted Recall Test:  0.2965565706254392
Macro Recall Train:  0.2571389276306527
Macro Recall Dev:  0.33899472595577745
Macro Recall Test:  0.14945982774135494
Micro Recall Train:  0.31644846674281696
Micro Recall Dev:  0.31304959549771366
Micro Recall Test:  0.2965565706254392
Confusion Matrix Train: 
[[ 330  682  950]
 [8270 6867 5641]
 [   7    9    6]]
Confusion Matrix Dev: 
[[  52   81  139]
 [1009  837  723]
 [   0    1    1]]
Confusion Matrix Test: 
[[  34   74  

### Sentence Transformer Faster PCA

In [49]:
train, dev, test = load_sent_trans_fast_pca()

In [50]:
k_medoids = KMedoids(n_clusters=3, random_state=0).fit(train, train_labels)
save_model(k_medoids, "k_medoids_sent_trans_fast_pca.joblib")

In [51]:
train_preds = k_medoids.predict(train)
dev_preds = k_medoids.predict(dev)
test_preds = k_medoids.predict(test)

In [52]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.16448466742816975
Accuracy Dev:  0.1691874780161801
Accuracy Test:  0.15495432185523542
Weighted F1 Train:  0.21459182406385943
Weighted F1 Dev:  0.21653690891808933
Weighted F1 Test:  0.20504840224103543
Macro F1 Train:  0.12387080883797429
Macro F1 Dev:  0.12881161428277996
Macro F1 Test:  0.11678999339470407
Micro F1 Train:  0.16448466742816975
Micro F1 Dev:  0.1691874780161801
Micro F1 Test:  0.15495432185523542
Weighted Recall Train:  0.16448466742816975
Weighted Recall Dev:  0.16918747801618012
Weighted Recall Test:  0.15495432185523542
Macro Recall Train:  0.3122091998338134
Macro Recall Dev:  0.4009785794426762
Macro Recall Test:  0.2169271114539144
Micro Recall Train:  0.16448466742816975
Micro Recall Dev:  0.1691874780161801
Micro Recall Test:  0.15495432185523542
Confusion Matrix Train: 
[[ 1147    86   729]
 [12259  2592  5927]
 [   16     1     5]]
Confusion Matrix Dev: 
[[ 157   11  104]
 [1514  323  732]
 [   1    0    1]]
Confusion Matrix Test: 
[[ 13

### Sentence Transformer Better No PCA

In [53]:
train, dev, test = load_sent_trans_better_no_pca()

In [54]:
k_medoids = KMedoids(n_clusters=3, random_state=0).fit(train, train_labels)
save_model(k_medoids, "k_medoids_sent_trans_better_no_pca.joblib")

In [55]:
train_preds = k_medoids.predict(train)
dev_preds = k_medoids.predict(dev)
test_preds = k_medoids.predict(test)

In [56]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.4275107635532906
Accuracy Dev:  0.4175167077031305
Accuracy Test:  0.42059030217849613
Weighted F1 Train:  0.5512414039335068
Weighted F1 Dev:  0.538153145434586
Weighted F1 Test:  0.5446920148680607
Macro F1 Train:  0.2492365853734491
Macro F1 Dev:  0.2423202598313456
Macro F1 Test:  0.24628309355788405
Micro F1 Train:  0.42751076355329065
Micro F1 Dev:  0.4175167077031305
Micro F1 Test:  0.42059030217849613
Weighted Recall Train:  0.4275107635532906
Weighted Recall Dev:  0.4175167077031305
Weighted Recall Test:  0.42059030217849613
Macro Recall Train:  0.3985457724897199
Macro Recall Dev:  0.23510044344713363
Macro Recall Test:  0.24543925954492865
Micro Recall Train:  0.4275107635532906
Micro Recall Dev:  0.4175167077031305
Micro Recall Test:  0.42059030217849613
Confusion Matrix Train: 
[[ 592 1073  297]
 [5050 9129 6599]
 [   3    9   10]]
Confusion Matrix Dev: 
[[  74  154   44]
 [ 661 1113  795]
 [   0    2    0]]
Confusion Matrix Test: 
[[  76  131   43]
 [ 6

### Sentence Transformer Better PCA

In [57]:
train, dev, test = load_sent_trans_better_pca()

In [58]:
k_medoids = KMedoids(n_clusters=3, random_state=0).fit(train, train_labels)
save_model(k_medoids, "k_medoids_sent_trans_better_pca.joblib")

In [59]:
train_preds = k_medoids.predict(train)
dev_preds = k_medoids.predict(dev)
test_preds = k_medoids.predict(test)

In [60]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.23890695018012478
Accuracy Dev:  0.24164614843475202
Accuracy Test:  0.2449051300070274
Weighted F1 Train:  0.3522420681742569
Weighted F1 Dev:  0.3507008494757182
Weighted F1 Test:  0.35588937983269175
Macro F1 Train:  0.19236199028107315
Macro F1 Dev:  0.20010792196537044
Macro F1 Test:  0.19843517429111945
Micro F1 Train:  0.23890695018012478
Micro F1 Dev:  0.24164614843475202
Micro F1 Test:  0.2449051300070274
Weighted Recall Train:  0.23890695018012478
Weighted Recall Dev:  0.24164614843475202
Weighted Recall Test:  0.2449051300070274
Macro Recall Train:  0.40714046766761314
Macro Recall Dev:  0.372920626016074
Macro Recall Test:  0.4308387539100999
Micro Recall Train:  0.23890695018012478
Micro Recall Dev:  0.24164614843475202
Micro Recall Test:  0.2449051300070274
Confusion Matrix Train: 
[[  702   287   973]
 [ 4058  4722 11998]
 [    3     5    14]]
Confusion Matrix Dev: 
[[ 107   41  124]
 [ 527  579 1463]
 [   1    0    1]]
Confusion Matrix Test: 
[[  99  