In [9]:
from embeddings_loader import *
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import roc_auc_score


In [10]:
train_labels, dev_labels, test_labels = load_labels()

In [11]:
def computeAllScores(y_pred_train, y_pred_dev, y_pred_test):
    print("Accuracy Train: ", accuracy_score(train_labels, y_pred_train))
    print("Accuracy Dev: ", accuracy_score(dev_labels, y_pred_dev))
    print("Accuracy Test: ", accuracy_score(test_labels, y_pred_test))
    print("F1 Train: ", f1_score(train_labels, y_pred_train, average='macro'))
    print("F1 Dev: ", f1_score(dev_labels, y_pred_dev, average='macro'))
    print("F1 Test: ", f1_score(test_labels, y_pred_test, average='macro'))
    print("Precision Train: ", precision_score(train_labels, y_pred_train, average='macro'))
    print("Precision Dev: ", precision_score(dev_labels, y_pred_dev, average='macro'))
    print("Precision Test: ", precision_score(test_labels, y_pred_test, average='macro'))
    print("Recall Train: ", recall_score(train_labels, y_pred_train, average='macro'))
    print("Recall Dev: ", recall_score(dev_labels, y_pred_dev, average='macro'))
    print("Recall Test: ", recall_score(test_labels, y_pred_test, average='macro'))
    # Confusion Matrix
    print("Confusion Matrix Train: ")
    print(confusion_matrix(train_labels, y_pred_train))
    print("Confusion Matrix Dev: ")
    print(confusion_matrix(dev_labels, y_pred_dev))
    print("Confusion Matrix Test: ")
    print(confusion_matrix(test_labels, y_pred_test))

In [12]:
label_replacement = {
    'Hope_speech': 0,
    'Non_hope_speech': 1,
    'not-English': 2,
}

In [13]:
# Replace labels with numbers
train_labels = [label_replacement[label] for label in train_labels]
dev_labels = [label_replacement[label] for label in dev_labels]
test_labels = [label_replacement[label] for label in test_labels]

### Glove Twitter 25

In [14]:
gt25_train, gt25_dev, gt25_test = load_glove_twitter_25()

In [15]:
# Set all NaN values to 0
gt25_train = np.nan_to_num(gt25_train)
gt25_dev = np.nan_to_num(gt25_dev)
gt25_test = np.nan_to_num(gt25_test)

In [16]:
KNN = KNeighborsClassifier(n_neighbors=3).fit(gt25_train, train_labels)

In [17]:
train_preds = KNN.predict(gt25_train)
dev_preds = KNN.predict(gt25_dev)
test_preds = KNN.predict(gt25_test)

In [18]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9424479395483701
Accuracy Dev:  0.8895532887794583
Accuracy Test:  0.8942375263527759
F1 Train:  0.63101796382433
F1 Dev:  0.4262458212469269
F1 Test:  0.423813613422765
Precision Train:  0.8977907492371946
Precision Dev:  0.4421995207466263
Precision Test:  0.4361384522087979
Recall Train:  0.5645402284101826
Recall Dev:  0.4158022882177394
Recall Test:  0.41511196811929557
Confusion Matrix Train: 
[[ 1039   923     0]
 [  369 20409     0]
 [    1    17     4]]
Confusion Matrix Dev: 
[[  80  192    0]
 [ 120 2449    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  73  177    0]
 [ 121 2472    0]
 [   0    3    0]]


C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### FastText 300 

In [19]:
ft300_train, ft300_dev, ft300_test = load_fasttext_300()

In [20]:
# Set all NaN values to 0
ft300_train = np.nan_to_num(ft300_train)
ft300_dev = np.nan_to_num(ft300_dev)
ft300_test = np.nan_to_num(ft300_test)

In [21]:
KNN = KNeighborsClassifier(n_neighbors=3).fit(ft300_train, train_labels)

In [22]:
train_preds = KNN.predict(ft300_train)
dev_preds = KNN.predict(ft300_dev)
test_preds = KNN.predict(ft300_test)

In [23]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9362534047974694
Accuracy Dev:  0.8705592683784734
Accuracy Test:  0.8713984539704849
F1 Train:  0.6310960404746296
F1 Dev:  0.4248698933125163
F1 Test:  0.42012283673993783
Precision Train:  0.8687021371661738
Precision Dev:  0.42250987533521783
Precision Test:  0.41444026011469254
Recall Train:  0.5828943960396512
Recall Dev:  0.42742321724330057
Recall Test:  0.4272374341174958
Confusion Matrix Train: 
[[ 1173   789     0]
 [  644 20134     0]
 [    3    15     4]]
Confusion Matrix Dev: 
[[  97  175    0]
 [ 191 2378    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  90  160    0]
 [ 203 2390    0]
 [   0    3    0]]


C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Word2Vec 300

In [24]:
w2v300_train, w2v300_dev, w2v300_test = load_word2vec_300()

In [25]:
# Set all NaN values to 0
w2v300_train = np.nan_to_num(w2v300_train)
w2v300_dev = np.nan_to_num(w2v300_dev)
w2v300_test = np.nan_to_num(w2v300_test)

In [26]:
KNN = KNeighborsClassifier(n_neighbors=3).fit(w2v300_train, train_labels)

In [27]:
train_preds = KNN.predict(w2v300_train)
dev_preds = KNN.predict(w2v300_dev)
test_preds = KNN.predict(w2v300_test)

In [28]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.935770143221158
Accuracy Dev:  0.8550826591628561
Accuracy Test:  0.8777231201686577
F1 Train:  0.6635444000875824
F1 Dev:  0.4278488646247241
F1 Test:  0.45621206920710583
Precision Train:  0.8617325784345405
Precision Dev:  0.41744151543308144
Precision Test:  0.44040670313873553
Recall Train:  0.6295469234454629
Recall Dev:  0.4447246200932689
Recall Test:  0.48256176886489266
Confusion Matrix Train: 
[[ 1379   583     0]
 [  862 19916     0]
 [    4    13     5]]
Confusion Matrix Dev: 
[[ 118  154    0]
 [ 256 2313    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 134  116    0]
 [ 229 2364    0]
 [   0    3    0]]


C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### TF-IDF PCA (1000 Dims)

In [29]:
tfidf_pca_train, tfidf_pca_dev, tfidf_pca_test = load_tfidf_pca()

In [30]:
KNN = KNeighborsClassifier(n_neighbors=3).fit(tfidf_pca_train, train_labels)

In [31]:
train_preds = KNN.predict(tfidf_pca_train)
dev_preds = KNN.predict(tfidf_pca_dev)
test_preds = KNN.predict(tfidf_pca_test)

In [32]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9341885598805026
Accuracy Dev:  0.9046781568765389
Accuracy Test:  0.9086437104708363
F1 Train:  0.5879187479278969
F1 Dev:  0.4095145734591559
F1 Test:  0.4023870862925312
Precision Train:  0.759099044593718
Precision Dev:  0.4796790663749088
Precision Test:  0.46403757756689384
Recall Train:  0.5201959858260939
Recall Dev:  0.3907009670353155
Recall Test:  0.38544388738912455
Confusion Matrix Train: 
[[  672  1290     0]
 [  187 20587     4]
 [    1    16     5]]
Confusion Matrix Dev: 
[[  52  220    0]
 [  48 2520    1]
 [   0    2    0]]
Confusion Matrix Test: 
[[  44  206    0]
 [  50 2542    1]
 [   0    3    0]]


### Sentence Transformer Faster No PCA

In [33]:
train, dev, test = load_sent_trans_fast_no_pca()

In [34]:
KNN = KNeighborsClassifier(n_neighbors=3).fit(train, train_labels)

In [35]:
train_preds = KNN.predict(train)
dev_preds = KNN.predict(dev)
test_preds = KNN.predict(test)

In [36]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9507951849573851
Accuracy Dev:  0.9053816391136124
Accuracy Test:  0.9111033028812369
F1 Train:  0.6584506532857021
F1 Dev:  0.47782260546475
F1 Test:  0.4834185876835533
Precision Train:  0.908338582488703
Precision Dev:  0.4843702238885112
Precision Test:  0.4841235706071004
Recall Train:  0.6008203682781857
Recall Dev:  0.4720450850639984
Recall Test:  0.48272631443630293
Confusion Matrix Train: 
[[ 1255   707     0]
 [  395 20383     0]
 [    3    15     4]]
Confusion Matrix Dev: 
[[ 126  146    0]
 [ 121 2448    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 124  126    0]
 [ 123 2469    1]
 [   0    3    0]]


C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Sentence Transformer Faster PCA

In [37]:
train, dev, test = load_sent_trans_fast_pca()

In [38]:
KNN = KNeighborsClassifier(n_neighbors=3).fit(train, train_labels)

In [39]:
train_preds = KNN.predict(train)
dev_preds = KNN.predict(dev)
test_preds = KNN.predict(test)

In [40]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9505315877339425
Accuracy Dev:  0.9064368624692226
Accuracy Test:  0.9125087842586086
F1 Train:  0.657113058153801
F1 Dev:  0.4763079750270783
F1 Test:  0.4843686909558376
Precision Train:  0.908866428697865
Precision Dev:  0.4862148626362314
Precision Test:  0.48681674963297233
Recall Train:  0.5982624797249653
Recall Dev:  0.4680513894931269
Recall Test:  0.4820357372412906
Confusion Matrix Train: 
[[ 1239   723     0]
 [  385 20393     0]
 [    3    15     4]]
Confusion Matrix Dev: 
[[ 122  150    0]
 [ 114 2455    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 123  127    0]
 [ 118 2474    1]
 [   0    3    0]]


C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Sentence Transformer Better No PCA

In [41]:
train, dev, test = load_sent_trans_better_no_pca()

In [42]:
KNN = KNeighborsClassifier(n_neighbors=3).fit(train, train_labels)

In [43]:
train_preds = KNN.predict(train)
dev_preds = KNN.predict(dev)
test_preds = KNN.predict(test)

In [44]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9514541780159915
Accuracy Dev:  0.9057333802321491
Accuracy Test:  0.9170765987350668
F1 Train:  0.6815443430257889
F1 Dev:  0.48688671304475123
F1 Test:  0.4988932800327692
Precision Train:  0.8467882919468094
Precision Dev:  0.48626284380774326
Precision Test:  0.4961218328052499
Recall Train:  0.632197093796386
Recall Dev:  0.4875151695555606
Recall Test:  0.5017786347859622
Confusion Matrix Train: 
[[ 1359   603     0]
 [  484 20293     1]
 [    2    15     5]]
Confusion Matrix Dev: 
[[ 140  132    0]
 [ 134 2435    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 138  112    0]
 [ 121 2472    0]
 [   0    3    0]]


C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Sentence Transformer Better PCA

In [45]:
train, dev, test = load_sent_trans_better_pca()

In [46]:
KNN = KNeighborsClassifier(n_neighbors=3).fit(train, train_labels)

In [47]:
train_preds = KNN.predict(train)
dev_preds = KNN.predict(dev)
test_preds = KNN.predict(test)

In [48]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.951366312274844
Accuracy Dev:  0.9050298979950756
Accuracy Test:  0.9177793394237527
F1 Train:  0.6810537202231489
F1 Dev:  0.48434210129732574
F1 Test:  0.49974079597331683
Precision Train:  0.8470168508215816
Precision Dev:  0.48472072279560297
Precision Test:  0.4975154286893717
Recall Train:  0.6310880441850831
Recall Dev:  0.48396845114067427
Recall Test:  0.5020357372412906
Confusion Matrix Train: 
[[ 1352   610     0]
 [  479 20298     1]
 [    2    15     5]]
Confusion Matrix Dev: 
[[ 137  135    0]
 [ 133 2436    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 138  112    0]
 [ 119 2474    0]
 [   0    3    0]]


C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
