In [1]:
from embeddings_loader import *
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import roc_auc_score
from utils import *


In [2]:
train_labels, dev_labels, test_labels = load_labels()

In [3]:
label_replacement = {
    'Hope_speech': 0,
    'Non_hope_speech': 1,
    'not-English': 2,
}

In [4]:
# Replace labels with numbers
train_labels = [label_replacement[label] for label in train_labels]
dev_labels = [label_replacement[label] for label in dev_labels]
test_labels = [label_replacement[label] for label in test_labels]

### Glove Twitter 25

In [5]:
gt25_train, gt25_dev, gt25_test = load_glove_twitter_25()

In [6]:
# Set all NaN values to 0
gt25_train = np.nan_to_num(gt25_train)
gt25_dev = np.nan_to_num(gt25_dev)
gt25_test = np.nan_to_num(gt25_test)

In [7]:
KNN = KNeighborsClassifier(n_neighbors=3).fit(gt25_train, train_labels)
save_model(KNN, 'KNN_gt25.joblib')

In [8]:
train_preds = KNN.predict(gt25_train)
dev_preds = KNN.predict(gt25_dev)
test_preds = KNN.predict(gt25_test)

In [9]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9424479395483701
Accuracy Dev:  0.8895532887794583
Accuracy Test:  0.8942375263527759
Weighted F1 Train:  0.937904602889989
Weighted F1 Dev:  0.8816153628397662
Weighted F1 Test:  0.8877020916618915
Macro F1 Train:  0.63101796382433
Macro F1 Dev:  0.4262458212469269
Macro F1 Test:  0.423813613422765
Micro F1 Train:  0.9424479395483701
Micro F1 Dev:  0.8895532887794583
Micro F1 Test:  0.8942375263527759
Weighted Recall Train:  0.9424479395483701
Weighted Recall Dev:  0.8895532887794583
Weighted Recall Test:  0.8942375263527759
Macro Recall Train:  0.5645402284101826
Macro Recall Dev:  0.4158022882177394
Macro Recall Test:  0.41511196811929557
Micro Recall Train:  0.9424479395483701
Micro Recall Dev:  0.8895532887794583
Micro Recall Test:  0.8942375263527759
Confusion Matrix Train: 
[[ 1039   923     0]
 [  369 20409     0]
 [    1    17     4]]
Confusion Matrix Dev: 
[[  80  192    0]
 [ 120 2449    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  73  177    0]
 [ 12

### FastText 300 

In [10]:
ft300_train, ft300_dev, ft300_test = load_fasttext_300()

In [11]:
# Set all NaN values to 0
ft300_train = np.nan_to_num(ft300_train)
ft300_dev = np.nan_to_num(ft300_dev)
ft300_test = np.nan_to_num(ft300_test)

In [12]:
KNN = KNeighborsClassifier(n_neighbors=3).fit(ft300_train, train_labels)
save_model(KNN, 'KNN_ft300.joblib')

In [13]:
train_preds = KNN.predict(ft300_train)
dev_preds = KNN.predict(ft300_dev)
test_preds = KNN.predict(ft300_test)

In [14]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9362534047974694
Accuracy Dev:  0.8705592683784734
Accuracy Test:  0.8713984539704849
Weighted F1 Train:  0.9349173130564195
Weighted F1 Dev:  0.871869799221996
Weighted F1 Test:  0.8754218074936921
Macro F1 Train:  0.6310960404746296
Macro F1 Dev:  0.4248698933125163
Macro F1 Test:  0.42012283673993783
Micro F1 Train:  0.9362534047974694
Micro F1 Dev:  0.8705592683784734
Micro F1 Test:  0.8713984539704849
Weighted Recall Train:  0.9362534047974694
Weighted Recall Dev:  0.8705592683784734
Weighted Recall Test:  0.8713984539704849
Macro Recall Train:  0.5828943960396512
Macro Recall Dev:  0.42742321724330057
Macro Recall Test:  0.4272374341174958
Micro Recall Train:  0.9362534047974694
Micro Recall Dev:  0.8705592683784734
Micro Recall Test:  0.8713984539704849
Confusion Matrix Train: 
[[ 1173   789     0]
 [  644 20134     0]
 [    3    15     4]]
Confusion Matrix Dev: 
[[  97  175    0]
 [ 191 2378    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  90  160    0]
 

### Word2Vec 300

In [15]:
w2v300_train, w2v300_dev, w2v300_test = load_word2vec_300()

In [16]:
# Set all NaN values to 0
w2v300_train = np.nan_to_num(w2v300_train)
w2v300_dev = np.nan_to_num(w2v300_dev)
w2v300_test = np.nan_to_num(w2v300_test)

In [17]:
KNN = KNeighborsClassifier(n_neighbors=3).fit(w2v300_train, train_labels)
save_model(KNN, 'KNN_w2v300.joblib')

In [18]:
train_preds = KNN.predict(w2v300_train)
dev_preds = KNN.predict(w2v300_dev)
test_preds = KNN.predict(w2v300_test)

In [19]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.935770143221158
Accuracy Dev:  0.8550826591628561
Accuracy Test:  0.8777231201686577
Weighted F1 Train:  0.9374698194204653
Weighted F1 Dev:  0.8646779799072708
Weighted F1 Test:  0.8870442186337211
Macro F1 Train:  0.6635444000875824
Macro F1 Dev:  0.4278488646247241
Macro F1 Test:  0.45621206920710583
Micro F1 Train:  0.935770143221158
Micro F1 Dev:  0.8550826591628561
Micro F1 Test:  0.8777231201686577
Weighted Recall Train:  0.935770143221158
Weighted Recall Dev:  0.8550826591628561
Weighted Recall Test:  0.8777231201686577
Macro Recall Train:  0.6295469234454629
Macro Recall Dev:  0.4447246200932689
Macro Recall Test:  0.48256176886489266
Micro Recall Train:  0.935770143221158
Micro Recall Dev:  0.8550826591628561
Micro Recall Test:  0.8777231201686577
Confusion Matrix Train: 
[[ 1379   583     0]
 [  862 19916     0]
 [    4    13     5]]
Confusion Matrix Dev: 
[[ 118  154    0]
 [ 256 2313    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 134  116    0]
 [ 2

### TF-IDF PCA (1000 Dims)

In [20]:
tfidf_pca_train, tfidf_pca_dev, tfidf_pca_test = load_tfidf_pca()

In [21]:
KNN = KNeighborsClassifier(n_neighbors=3).fit(tfidf_pca_train, train_labels)
save_model(KNN, 'KNN_tfidf_pca.joblib')

In [22]:
train_preds = KNN.predict(tfidf_pca_train)
dev_preds = KNN.predict(tfidf_pca_dev)
test_preds = KNN.predict(tfidf_pca_test)

In [23]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9341885598805026
Accuracy Dev:  0.9046781568765389
Accuracy Test:  0.9086437104708363
Weighted F1 Train:  0.9221761418639955
Weighted F1 Dev:  0.8842619678645663
Weighted F1 Test:  0.8892470313585188
Macro F1 Train:  0.5879187479278969
Macro F1 Dev:  0.4095145734591559
Macro F1 Test:  0.4023870862925312
Micro F1 Train:  0.9341885598805026
Micro F1 Dev:  0.9046781568765389
Micro F1 Test:  0.9086437104708363
Weighted Recall Train:  0.9341885598805026
Weighted Recall Dev:  0.9046781568765389
Weighted Recall Test:  0.9086437104708363
Macro Recall Train:  0.5201959858260939
Macro Recall Dev:  0.3907009670353155
Macro Recall Test:  0.38544388738912455
Micro Recall Train:  0.9341885598805026
Micro Recall Dev:  0.9046781568765389
Micro Recall Test:  0.9086437104708363
Confusion Matrix Train: 
[[  672  1290     0]
 [  187 20587     4]
 [    1    16     5]]
Confusion Matrix Dev: 
[[  52  220    0]
 [  48 2520    1]
 [   0    2    0]]
Confusion Matrix Test: 
[[  44  206    0]
 

### Sentence Transformer Faster No PCA

In [24]:
train, dev, test = load_sent_trans_fast_no_pca()

In [25]:
KNN = KNeighborsClassifier(n_neighbors=3).fit(train, train_labels)
save_model(KNN, "KNN_sent_trans_fast_no_pca.joblib")

In [26]:
train_preds = KNN.predict(train)
dev_preds = KNN.predict(dev)
test_preds = KNN.predict(test)

In [27]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9507951849573851
Accuracy Dev:  0.9053816391136124
Accuracy Test:  0.9111033028812369
Weighted F1 Train:  0.9486382373314389
Weighted F1 Dev:  0.9030152873497449
Weighted F1 Test:  0.910530687437633
Macro F1 Train:  0.6584506532857021
Macro F1 Dev:  0.47782260546475
Macro F1 Test:  0.4834185876835533
Micro F1 Train:  0.9507951849573851
Micro F1 Dev:  0.9053816391136124
Micro F1 Test:  0.9111033028812369
Weighted Recall Train:  0.9507951849573851
Weighted Recall Dev:  0.9053816391136124
Weighted Recall Test:  0.9111033028812369
Macro Recall Train:  0.6008203682781857
Macro Recall Dev:  0.4720450850639984
Macro Recall Test:  0.48272631443630293
Micro Recall Train:  0.9507951849573851
Micro Recall Dev:  0.9053816391136124
Micro Recall Test:  0.9111033028812369
Confusion Matrix Train: 
[[ 1255   707     0]
 [  395 20383     0]
 [    3    15     4]]
Confusion Matrix Dev: 
[[ 126  146    0]
 [ 121 2448    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 124  126    0]
 [ 1

### Sentence Transformer Faster PCA

In [28]:
train, dev, test = load_sent_trans_fast_pca()

In [29]:
KNN = KNeighborsClassifier(n_neighbors=3).fit(train, train_labels)
save_model(KNN, "KNN_sent_trans_fast_pca.joblib")

In [30]:
train_preds = KNN.predict(train)
dev_preds = KNN.predict(dev)
test_preds = KNN.predict(test)

In [31]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9505315877339425
Accuracy Dev:  0.9064368624692226
Accuracy Test:  0.9125087842586086
Weighted F1 Train:  0.9481876793683077
Weighted F1 Dev:  0.903138269070265
Weighted F1 Test:  0.9114610329931896
Macro F1 Train:  0.657113058153801
Macro F1 Dev:  0.4763079750270783
Macro F1 Test:  0.4843686909558376
Micro F1 Train:  0.9505315877339425
Micro F1 Dev:  0.9064368624692226
Micro F1 Test:  0.9125087842586086
Weighted Recall Train:  0.9505315877339425
Weighted Recall Dev:  0.9064368624692226
Weighted Recall Test:  0.9125087842586086
Macro Recall Train:  0.5982624797249653
Macro Recall Dev:  0.4680513894931269
Macro Recall Test:  0.4820357372412906
Micro Recall Train:  0.9505315877339425
Micro Recall Dev:  0.9064368624692226
Micro Recall Test:  0.9125087842586086
Confusion Matrix Train: 
[[ 1239   723     0]
 [  385 20393     0]
 [    3    15     4]]
Confusion Matrix Dev: 
[[ 122  150    0]
 [ 114 2455    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 123  127    0]
 [ 1

### Sentence Transformer Better No PCA

In [32]:
train, dev, test = load_sent_trans_better_no_pca()

In [33]:
KNN = KNeighborsClassifier(n_neighbors=3).fit(train, train_labels)
save_model(KNN, "KNN_sent_trans_best_no_pca.joblib")

In [34]:
train_preds = KNN.predict(train)
dev_preds = KNN.predict(dev)
test_preds = KNN.predict(test)

In [35]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9514541780159915
Accuracy Dev:  0.9057333802321491
Accuracy Test:  0.9170765987350668
Weighted F1 Train:  0.9505703604798112
Weighted F1 Dev:  0.9055530001713613
Weighted F1 Test:  0.9172253133794303
Macro F1 Train:  0.6815443430257889
Macro F1 Dev:  0.48688671304475123
Macro F1 Test:  0.4988932800327692
Micro F1 Train:  0.9514541780159915
Micro F1 Dev:  0.9057333802321491
Micro F1 Test:  0.9170765987350668
Weighted Recall Train:  0.9514541780159915
Weighted Recall Dev:  0.9057333802321491
Weighted Recall Test:  0.9170765987350668
Macro Recall Train:  0.632197093796386
Macro Recall Dev:  0.4875151695555606
Macro Recall Test:  0.5017786347859622
Micro Recall Train:  0.9514541780159915
Micro Recall Dev:  0.9057333802321491
Micro Recall Test:  0.9170765987350668
Confusion Matrix Train: 
[[ 1359   603     0]
 [  484 20293     1]
 [    2    15     5]]
Confusion Matrix Dev: 
[[ 140  132    0]
 [ 134 2435    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 138  112    0]
 [

### Sentence Transformer Better PCA

In [36]:
train, dev, test = load_sent_trans_better_pca()

In [37]:
KNN = KNeighborsClassifier(n_neighbors=3).fit(train, train_labels)
save_model(KNN, "KNN_sent_trans_best_pca.joblib")

In [38]:
train_preds = KNN.predict(train)
dev_preds = KNN.predict(dev)
test_preds = KNN.predict(test)

In [39]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.951366312274844
Accuracy Dev:  0.9050298979950756
Accuracy Test:  0.9177793394237527
Weighted F1 Train:  0.9504101384812274
Weighted F1 Dev:  0.9045411721977727
Weighted F1 Test:  0.9177808720785676
Macro F1 Train:  0.6810537202231489
Macro F1 Dev:  0.48434210129732574
Macro F1 Test:  0.49974079597331683
Micro F1 Train:  0.951366312274844
Micro F1 Dev:  0.9050298979950756
Micro F1 Test:  0.9177793394237527
Weighted Recall Train:  0.951366312274844
Weighted Recall Dev:  0.9050298979950756
Weighted Recall Test:  0.9177793394237527
Macro Recall Train:  0.6310880441850831
Macro Recall Dev:  0.48396845114067427
Macro Recall Test:  0.5020357372412906
Micro Recall Train:  0.951366312274844
Micro Recall Dev:  0.9050298979950756
Micro Recall Test:  0.9177793394237527
Confusion Matrix Train: 
[[ 1352   610     0]
 [  479 20298     1]
 [    2    15     5]]
Confusion Matrix Dev: 
[[ 137  135    0]
 [ 133 2436    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 138  112    0]
 [ 