In [1]:
from embeddings_loader import *
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import roc_auc_score
from utils import *


--ip=127.0.0.1


In [2]:
train_labels, dev_labels, test_labels = load_labels()
train_augmented_labels, dev_augmented_labels, test_augmented_labels = load_augmented_labels()

In [3]:
label_replacement = {
    'Hope_speech': 0,
    'Non_hope_speech': 1,
    'not-English': 2,
}

In [4]:
# Replace labels with numbers
train_labels = [label_replacement[label] for label in train_labels]
dev_labels = [label_replacement[label] for label in dev_labels]
test_labels = [label_replacement[label] for label in test_labels]
train_augmented_labels = [label_replacement[label] for label in train_augmented_labels]

### Glove Twitter 25

In [5]:
gt25_train, gt25_dev, gt25_test = load_glove_twitter_25()

In [6]:
# Set all NaN values to 0
gt25_train = np.nan_to_num(gt25_train)
gt25_dev = np.nan_to_num(gt25_dev)
gt25_test = np.nan_to_num(gt25_test)

In [7]:
linear_discriminant_analysis = LinearDiscriminantAnalysis().fit(gt25_train, train_labels)
save_model(linear_discriminant_analysis, "linear_discriminant_analysis_gt25.joblib")

In [8]:
train_preds = linear_discriminant_analysis.predict(gt25_train)
dev_preds = linear_discriminant_analysis.predict(gt25_dev)
test_preds = linear_discriminant_analysis.predict(gt25_test)

In [9]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9079167032773922
Accuracy Dev:  0.898698557861414
Accuracy Test:  0.9082923401264933
Weighted F1 Train:  0.874038857270971
Weighted F1 Dev:  0.8624845462727491
Weighted F1 Test:  0.8720091183359844
Macro F1 Train:  0.36459038619550105
Macro F1 Dev:  0.340309658495705
Macro F1 Test:  0.38622567029769245
Micro F1 Train:  0.9079167032773922
Micro F1 Dev:  0.898698557861414
Micro F1 Test:  0.9082923401264933
Weighted Recall Train:  0.9079167032773922
Weighted Recall Dev:  0.898698557861414
Weighted Recall Test:  0.9082923401264933
Macro Recall Train:  0.41721430746696536
Macro Recall Dev:  0.3435699211564735
Macro Recall Test:  0.4517209581351502
Micro Recall Train:  0.9079167032773922
Micro Recall Dev:  0.898698557861414
Micro Recall Test:  0.9082923401264933
Confusion Matrix Train: 
[[   65  1896     1]
 [   86 20596    96]
 [    0    17     5]]
Confusion Matrix Dev: 
[[  11  260    1]
 [  13 2544   12]
 [   0    2    0]]
Confusion Matrix Test: 
[[   7  243    0]
 [   

### FastText 300 

In [10]:
ft300_train, ft300_dev, ft300_test = load_fasttext_300()

In [11]:
# Set all NaN values to 0
ft300_train = np.nan_to_num(ft300_train)
ft300_dev = np.nan_to_num(ft300_dev)
ft300_test = np.nan_to_num(ft300_test)

In [12]:
linear_discriminant_analysis = LinearDiscriminantAnalysis().fit(ft300_train, train_labels)
save_model(linear_discriminant_analysis, "linear_discriminant_analysis_ft300.joblib")

In [13]:
train_preds = linear_discriminant_analysis.predict(ft300_train)
dev_preds = linear_discriminant_analysis.predict(ft300_dev)
test_preds = linear_discriminant_analysis.predict(ft300_test)

In [14]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9126614532993585
Accuracy Dev:  0.9071403447062961
Accuracy Test:  0.910049191848208
Weighted F1 Train:  0.8934781948762186
Weighted F1 Dev:  0.8887626728422264
Weighted F1 Test:  0.8887201943577504
Macro F1 Train:  0.5010472645030078
Macro F1 Dev:  0.42172269960030934
Macro F1 Test:  0.5623809652351002
Micro F1 Train:  0.9126614532993585
Micro F1 Dev:  0.9071403447062961
Micro F1 Test:  0.910049191848208
Weighted Recall Train:  0.9126614532993585
Weighted Recall Dev:  0.9071403447062961
Weighted Recall Test:  0.910049191848208
Macro Recall Train:  0.4930656903412138
Macro Recall Dev:  0.400375136430594
Macro Recall Test:  0.49091674165488275
Micro Recall Train:  0.9126614532993585
Micro Recall Dev:  0.9071403447062961
Micro Recall Test:  0.910049191848208
Confusion Matrix Train: 
[[  350  1612     0]
 [  341 20417    20]
 [    0    15     7]]
Confusion Matrix Dev: 
[[  60  212    0]
 [  49 2519    1]
 [   0    2    0]]
Confusion Matrix Test: 
[[  39  211    0]
 [  4

### Word2Vec 300

In [15]:
w2v300_train, w2v300_dev, w2v300_test = load_word2vec_300()

In [16]:
# Set all NaN values to 0
w2v300_train = np.nan_to_num(w2v300_train)
w2v300_dev = np.nan_to_num(w2v300_dev)
w2v300_test = np.nan_to_num(w2v300_test)

In [17]:
linear_discriminant_analysis = LinearDiscriminantAnalysis().fit(w2v300_train, train_labels)
save_model(linear_discriminant_analysis, "linear_discriminant_analysis_w2v300.joblib")

In [18]:
train_preds = linear_discriminant_analysis.predict(w2v300_train)
dev_preds = linear_discriminant_analysis.predict(w2v300_dev)
test_preds = linear_discriminant_analysis.predict(w2v300_test)

In [19]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9127932519110799
Accuracy Dev:  0.9110094970102005
Accuracy Test:  0.9065354884047786
Weighted F1 Train:  0.8948068945756313
Weighted F1 Dev:  0.8934695262440009
Weighted F1 Test:  0.887026339373011
Macro F1 Train:  0.5317567127629402
Macro F1 Dev:  0.4323068918635153
Macro F1 Test:  0.5073037805813615
Micro F1 Train:  0.9127932519110799
Micro F1 Dev:  0.9110094970102005
Micro F1 Test:  0.9065354884047786
Weighted Recall Train:  0.9127932519110799
Weighted Recall Dev:  0.9110094970102005
Weighted Recall Test:  0.9065354884047786
Macro Recall Train:  0.5124032962267827
Macro Recall Dev:  0.4083768384738091
Macro Recall Test:  0.49204079358957875
Micro Recall Train:  0.9127932519110799
Micro Recall Dev:  0.9110094970102005
Micro Recall Test:  0.9065354884047786
Confusion Matrix Train: 
[[  377  1584     1]
 [  373 20392    13]
 [    0    14     8]]
Confusion Matrix Dev: 
[[  66  206    0]
 [  45 2524    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  41  209    0]
 [

### TF-IDF PCA (1000 Dims)

In [20]:
tfidf_pca_train, tfidf_pca_dev, tfidf_pca_test = load_tfidf_pca()

In [21]:
linear_discriminant_analysis = LinearDiscriminantAnalysis().fit(tfidf_pca_train, train_labels)
save_model(linear_discriminant_analysis, "linear_discriminant_analysis_tfidf_pca.joblib")

In [22]:
train_preds = linear_discriminant_analysis.predict(tfidf_pca_train)
dev_preds = linear_discriminant_analysis.predict(tfidf_pca_dev)
test_preds = linear_discriminant_analysis.predict(tfidf_pca_test)

In [23]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9249626570600123
Accuracy Dev:  0.9096025325360535
Accuracy Test:  0.9093464511595222
Weighted F1 Train:  0.9240693947324502
Weighted F1 Dev:  0.9091847121944527
Weighted F1 Test:  0.909648731477934
Macro F1 Train:  0.5522586948263765
Macro F1 Dev:  0.49147230896878646
Macro F1 Test:  0.4827525893804463
Micro F1 Train:  0.9249626570600123
Micro F1 Dev:  0.9096025325360535
Micro F1 Test:  0.9093464511595223
Weighted Recall Train:  0.9249626570600123
Weighted Recall Dev:  0.9096025325360535
Weighted Recall Test:  0.9093464511595222
Macro Recall Train:  0.6862203638663568
Macro Recall Dev:  0.4746978491669147
Macro Recall Test:  0.47244530145262886
Micro Recall Train:  0.9249626570600123
Micro Recall Dev:  0.9096025325360535
Micro Recall Test:  0.9093464511595222
Confusion Matrix Train: 
[[  986   967     9]
 [  579 20055   144]
 [    0     9    13]]
Confusion Matrix Dev: 
[[ 127  143    2]
 [  86 2459   24]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 116  134    0]
 

### Sentence Transformer Faster No PCA

In [24]:
train, dev, test = load_sent_trans_fast_no_pca()

In [25]:
linear_discriminant_analysis = LinearDiscriminantAnalysis().fit(train, train_labels)
save_model(linear_discriminant_analysis, "linear_discriminant_analysis_sent_trans_fast_no_pca.joblib")

In [26]:
train_preds = linear_discriminant_analysis.predict(train)
dev_preds = linear_discriminant_analysis.predict(dev)
test_preds = linear_discriminant_analysis.predict(test)

In [27]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9253141200246024
Accuracy Dev:  0.9176925782623989
Accuracy Test:  0.9188334504567814
Weighted F1 Train:  0.9209556515080913
Weighted F1 Dev:  0.9119872252172647
Weighted F1 Test:  0.914249702678899
Macro F1 Train:  0.6522347837376588
Macro F1 Dev:  0.48890475977919623
Macro F1 Test:  0.5652457244580075
Micro F1 Train:  0.9253141200246023
Micro F1 Dev:  0.9176925782623989
Micro F1 Test:  0.9188334504567814
Weighted Recall Train:  0.9253141200246024
Weighted Recall Dev:  0.9176925782623989
Weighted Recall Test:  0.9188334504567814
Macro Recall Train:  0.6575203992011289
Macro Recall Dev:  0.4711077210175623
Macro Recall Test:  0.5772604876376569
Micro Recall Train:  0.9253141200246024
Micro Recall Dev:  0.9176925782623989
Micro Recall Test:  0.9188334504567814
Confusion Matrix Train: 
[[  897  1064     1]
 [  610 20153    15]
 [    0    10    12]]
Confusion Matrix Dev: 
[[ 121  151    0]
 [  80 2488    1]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 108  142    0]
 [

### Sentence Transformer Faster PCA

In [28]:
train, dev, test = load_sent_trans_fast_pca()

In [29]:
linear_discriminant_analysis = LinearDiscriminantAnalysis().fit(train, train_labels)
save_model(linear_discriminant_analysis, "linear_discriminant_analysis_sent_trans_fast_pca.joblib")

In [30]:
train_preds = linear_discriminant_analysis.predict(train)
dev_preds = linear_discriminant_analysis.predict(dev)
test_preds = linear_discriminant_analysis.predict(test)

In [31]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9229417450136191
Accuracy Dev:  0.9138234259584945
Accuracy Test:  0.9188334504567814
Weighted F1 Train:  0.917783884830192
Weighted F1 Dev:  0.9078645778215626
Weighted F1 Test:  0.9134276856764797
Macro F1 Train:  0.597693481551787
Macro F1 Dev:  0.480408269394049
Macro F1 Test:  0.4796357783302687
Micro F1 Train:  0.9229417450136191
Micro F1 Dev:  0.9138234259584945
Micro F1 Test:  0.9188334504567814
Weighted Recall Train:  0.9229417450136191
Weighted Recall Dev:  0.9138234259584945
Weighted Recall Test:  0.9188334504567814
Macro Recall Train:  0.6029396696474878
Macro Recall Dev:  0.4620102809516177
Macro Recall Test:  0.4638683635428718
Micro Recall Train:  0.9229417450136191
Micro Recall Dev:  0.9138234259584945
Micro Recall Test:  0.9188334504567814
Confusion Matrix Train: 
[[  843  1119     0]
 [  600 20156    22]
 [    0    13     9]]
Confusion Matrix Dev: 
[[ 114  158    0]
 [  81 2484    4]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 106  144    0]
 [  8

In [32]:
# Format List of Lists as Confusion Matrix
import tabulate
def format_confusion_matrix(confusion_matrix):
    return tabulate(confusion_matrix, headers=['Hope_speech', 'Non_hope_speech', 'not-English'], tablefmt='psql')


### Sentence Transformer Better No PCA

In [33]:
train, dev, test = load_sent_trans_better_no_pca()

In [34]:
linear_discriminant_analysis = LinearDiscriminantAnalysis().fit(train, train_labels)
save_model(linear_discriminant_analysis, "linear_discriminant_analysis_sent_trans_better_no_pca.joblib")

In [35]:
train_preds = linear_discriminant_analysis.predict(train)
dev_preds = linear_discriminant_analysis.predict(dev)
test_preds = linear_discriminant_analysis.predict(test)

In [36]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9329584395044372
Accuracy Dev:  0.9257826239887443
Accuracy Test:  0.9314827828531272
Weighted F1 Train:  0.9309155504439608
Weighted F1 Dev:  0.9224525039048963
Weighted F1 Test:  0.9278586560798175
Macro F1 Train:  0.734891346582057
Macro F1 Dev:  0.5134893380460697
Macro F1 Test:  0.5132810757818648
Micro F1 Train:  0.9329584395044372
Micro F1 Dev:  0.9257826239887443
Micro F1 Test:  0.9314827828531272
Weighted Recall Train:  0.9329584395044372
Weighted Recall Dev:  0.9257826239887443
Weighted Recall Test:  0.9314827828531272
Macro Recall Train:  0.7341808612091841
Macro Recall Dev:  0.5003897335500959
Macro Recall Test:  0.49861576038051164
Micro Recall Train:  0.9329584395044372
Micro Recall Dev:  0.9257826239887443
Micro Recall Test:  0.9314827828531272
Confusion Matrix Train: 
[[ 1082   880     0]
 [  630 20139     9]
 [    0     7    15]]
Confusion Matrix Dev: 
[[ 145  127    0]
 [  82 2487    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 131  119    0]
 [

### Sentence Transformer Better PCA

In [37]:
train, dev, test = load_sent_trans_better_pca()

In [38]:
linear_discriminant_analysis = LinearDiscriminantAnalysis().fit(train, train_labels)
save_model(linear_discriminant_analysis, "linear_discriminant_analysis_sent_trans_better_pca.joblib")

In [39]:
train_preds = linear_discriminant_analysis.predict(train)
dev_preds = linear_discriminant_analysis.predict(dev)
test_preds = linear_discriminant_analysis.predict(test)

In [40]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9285212195764871
Accuracy Dev:  0.9205065072106929
Accuracy Test:  0.9272663387210119
Weighted F1 Train:  0.9259481858495237
Weighted F1 Dev:  0.9160776981610912
Weighted F1 Test:  0.9239791816921512
Macro F1 Train:  0.6345459293052274
Macro F1 Dev:  0.49916287013549726
Macro F1 Test:  0.5058152534206223
Micro F1 Train:  0.9285212195764871
Micro F1 Dev:  0.9205065072106929
Micro F1 Test:  0.9272663387210119
Weighted Recall Train:  0.9285212195764871
Weighted Recall Dev:  0.9205065072106929
Weighted Recall Test:  0.9272663387210119
Macro Recall Train:  0.6314396346677315
Macro Recall Dev:  0.4841988566543784
Macro Recall Test:  0.49225401722586454
Micro Recall Train:  0.9285212195764871
Micro Recall Dev:  0.9205065072106929
Micro Recall Test:  0.9272663387210119
Confusion Matrix Train: 
[[ 1015   947     0]
 [  651 20111    16]
 [    0    13     9]]
Confusion Matrix Dev: 
[[ 132  140    0]
 [  84 2485    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 127  123    0]


## Augmented Data Sentence Transformer Better

In [41]:
train_aug, dev, test = load_sent_trans_augmented_no_pca()


In [42]:
linear_discriminant_analysis = LinearDiscriminantAnalysis().fit(train_aug, train_augmented_labels)
save_model(linear_discriminant_analysis, "linear_discriminant_analysis_sent_trans_augmented_no_pca.joblib")

In [43]:
train_preds = linear_discriminant_analysis.predict(train_aug)
dev_preds = linear_discriminant_analysis.predict(dev)
test_preds = linear_discriminant_analysis.predict(test)

In [44]:
computeAllScores(train_preds, dev_preds, test_preds, aug=True)

Accuracy Train:  0.8904487754235288
Accuracy Dev:  0.8519169890960253
Accuracy Test:  0.8475052705551651
Weighted F1 Train:  0.8904516680712965
Weighted F1 Dev:  0.8692369589909583
Weighted F1 Test:  0.8698072326737343
Macro F1 Train:  0.8070183181840536
Macro F1 Dev:  0.4541585352532163
Macro F1 Test:  0.5622028726178442
Micro F1 Train:  0.8904487754235288
Micro F1 Dev:  0.8519169890960253
Micro F1 Test:  0.8475052705551651
Weighted Recall Train:  0.8904487754235288
Weighted Recall Dev:  0.8519169890960253
Weighted Recall Test:  0.8475052705551651
Macro Recall Train:  0.8360185280406122
Macro Recall Dev:  0.5005352277150642
Macro Recall Test:  0.6258610789733042
Micro Recall Train:  0.8904487754235288
Micro Recall Dev:  0.8519169890960253
Micro Recall Test:  0.8475052705551651
Confusion Matrix Train: 
[[19378  2204     0]
 [ 2421 18345    12]
 [    0     6    16]]
Confusion Matrix Dev: 
[[ 170  102    0]
 [ 317 2252    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 170   80    0]
 [

## Only 2 Class Augmented Data Sentence Transformer Better

In [45]:
train, dev, test, train_labels, dev_labels, test_labels = load_only_2_class("sent_trans_augmented_no_pca", True)

In [51]:
train_labels = [label_replacement[label] for label in train_labels]
dev_labels = [label_replacement[label] for label in dev_labels]
test_labels = [label_replacement[label] for label in test_labels]

In [52]:
linear_discriminant_analysis = LinearDiscriminantAnalysis().fit(train, train_labels)
save_model(linear_discriminant_analysis, "linear_discriminant_analysis_sent_trans_augmented_no_pca_2_class.joblib")

In [53]:
train_preds = linear_discriminant_analysis.predict(train)
dev_preds = linear_discriminant_analysis.predict(dev)
test_preds = linear_discriminant_analysis.predict(test)

In [54]:
computeAllScores(train_preds, dev_preds, test_preds, aug=True)

Accuracy Train:  0.8904487754235288
Accuracy Dev:  0.8519169890960253
Accuracy Test:  0.8475052705551651
Weighted F1 Train:  0.8904516680712965
Weighted F1 Dev:  0.8692369589909583
Weighted F1 Test:  0.8698072326737343
Macro F1 Train:  0.8070183181840536
Macro F1 Dev:  0.4541585352532163
Macro F1 Test:  0.5622028726178442
Micro F1 Train:  0.8904487754235288
Micro F1 Dev:  0.8519169890960253
Micro F1 Test:  0.8475052705551651
Weighted Recall Train:  0.8904487754235288
Weighted Recall Dev:  0.8519169890960253
Weighted Recall Test:  0.8475052705551651
Macro Recall Train:  0.8360185280406122
Macro Recall Dev:  0.5005352277150642
Macro Recall Test:  0.6258610789733042
Micro Recall Train:  0.8904487754235288
Micro Recall Dev:  0.8519169890960253
Micro Recall Test:  0.8475052705551651
Confusion Matrix Train: 
[[19378  2204     0]
 [ 2421 18345    12]
 [    0     6    16]]
Confusion Matrix Dev: 
[[ 170  102    0]
 [ 317 2252    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 170   80    0]
 [