In [1]:
from embeddings_loader import *
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import roc_auc_score


In [2]:
train_labels, dev_labels, test_labels = load_labels()

In [3]:
def computeAllScores(y_pred_train, y_pred_dev, y_pred_test):
    print("Accuracy Train: ", accuracy_score(train_labels, y_pred_train))
    print("Accuracy Dev: ", accuracy_score(dev_labels, y_pred_dev))
    print("Accuracy Test: ", accuracy_score(test_labels, y_pred_test))
    print("F1 Train: ", f1_score(train_labels, y_pred_train, average='macro'))
    print("F1 Dev: ", f1_score(dev_labels, y_pred_dev, average='macro'))
    print("F1 Test: ", f1_score(test_labels, y_pred_test, average='macro'))
    print("Precision Train: ", precision_score(train_labels, y_pred_train, average='macro'))
    print("Precision Dev: ", precision_score(dev_labels, y_pred_dev, average='macro'))
    print("Precision Test: ", precision_score(test_labels, y_pred_test, average='macro'))
    print("Recall Train: ", recall_score(train_labels, y_pred_train, average='macro'))
    print("Recall Dev: ", recall_score(dev_labels, y_pred_dev, average='macro'))
    print("Recall Test: ", recall_score(test_labels, y_pred_test, average='macro'))
    # Confusion Matrix
    print("Confusion Matrix Train: ")
    print(confusion_matrix(train_labels, y_pred_train))
    print("Confusion Matrix Dev: ")
    print(confusion_matrix(dev_labels, y_pred_dev))
    print("Confusion Matrix Test: ")
    print(confusion_matrix(test_labels, y_pred_test))

In [4]:
label_replacement = {
    'Hope_speech': 0,
    'Non_hope_speech': 1,
    'not-English': 2,
}

In [5]:
# Replace labels with numbers
train_labels = [label_replacement[label] for label in train_labels]
dev_labels = [label_replacement[label] for label in dev_labels]
test_labels = [label_replacement[label] for label in test_labels]

### Glove Twitter 25

In [6]:
gt25_train, gt25_dev, gt25_test = load_glove_twitter_25()

In [7]:
# Set all NaN values to 0
gt25_train = np.nan_to_num(gt25_train)
gt25_dev = np.nan_to_num(gt25_dev)
gt25_test = np.nan_to_num(gt25_test)

In [8]:
linear_discriminant_analysis = LinearDiscriminantAnalysis().fit(gt25_train, train_labels)

In [9]:
train_preds = linear_discriminant_analysis.predict(gt25_train)
dev_preds = linear_discriminant_analysis.predict(gt25_dev)
test_preds = linear_discriminant_analysis.predict(gt25_test)

In [10]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9079167032773922
Accuracy Dev:  0.898698557861414
Accuracy Test:  0.9082923401264933
F1 Train:  0.36459038619550105
F1 Dev:  0.340309658495705
F1 Test:  0.38622567029769245
Precision Train:  0.464831652356876
Precision Dev:  0.45498732874000153
Precision Test:  0.5043940467753366
Recall Train:  0.41721430746696536
Recall Dev:  0.3435699211564735
Recall Test:  0.4517209581351502
Confusion Matrix Train: 
[[   65  1896     1]
 [   86 20596    96]
 [    0    17     5]]
Confusion Matrix Dev: 
[[  11  260    1]
 [  13 2544   12]
 [   0    2    0]]
Confusion Matrix Test: 
[[   7  243    0]
 [   7 2577    9]
 [   0    2    1]]


### FastText 300 

In [11]:
ft300_train, ft300_dev, ft300_test = load_fasttext_300()

In [12]:
# Set all NaN values to 0
ft300_train = np.nan_to_num(ft300_train)
ft300_dev = np.nan_to_num(ft300_dev)
ft300_test = np.nan_to_num(ft300_test)

In [13]:
linear_discriminant_analysis = LinearDiscriminantAnalysis().fit(ft300_train, train_labels)

In [14]:
train_preds = linear_discriminant_analysis.predict(ft300_train)
dev_preds = linear_discriminant_analysis.predict(ft300_dev)
test_preds = linear_discriminant_analysis.predict(ft300_test)

In [15]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9126614532993585
Accuracy Dev:  0.9071403447062961
Accuracy Test:  0.910049191848208
F1 Train:  0.5010472645030078
F1 Dev:  0.42172269960030934
F1 Test:  0.5623809652351002
Precision Train:  0.563988209560307
Precision Dev:  0.49071882787227356
Precision Test:  0.7995065455540549
Recall Train:  0.4930656903412138
Recall Dev:  0.400375136430594
Recall Test:  0.49091674165488275
Confusion Matrix Train: 
[[  350  1612     0]
 [  341 20417    20]
 [    0    15     7]]
Confusion Matrix Dev: 
[[  60  212    0]
 [  49 2519    1]
 [   0    2    0]]
Confusion Matrix Test: 
[[  39  211    0]
 [  43 2550    0]
 [   0    2    1]]


### Word2Vec 300

In [16]:
w2v300_train, w2v300_dev, w2v300_test = load_word2vec_300()

In [17]:
# Set all NaN values to 0
w2v300_train = np.nan_to_num(w2v300_train)
w2v300_dev = np.nan_to_num(w2v300_dev)
w2v300_test = np.nan_to_num(w2v300_test)

In [18]:
linear_discriminant_analysis = LinearDiscriminantAnalysis().fit(w2v300_train, train_labels)

In [19]:
train_preds = linear_discriminant_analysis.predict(w2v300_train)
dev_preds = linear_discriminant_analysis.predict(w2v300_dev)
test_preds = linear_discriminant_analysis.predict(w2v300_test)

In [20]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9127932519110799
Accuracy Dev:  0.9110094970102005
Accuracy Test:  0.9065354884047786
F1 Train:  0.5317567127629402
F1 Dev:  0.4323068918635153
F1 Test:  0.5073037805813615
Precision Train:  0.5978778783744678
Precision Dev:  0.5061532982470025
Precision Test:  0.564249454132042
Recall Train:  0.5124032962267827
Recall Dev:  0.4083768384738091
Recall Test:  0.49204079358957875
Confusion Matrix Train: 
[[  377  1584     1]
 [  373 20392    13]
 [    0    14     8]]
Confusion Matrix Dev: 
[[  66  206    0]
 [  45 2524    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  41  209    0]
 [  53 2538    2]
 [   0    2    1]]


C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### TF-IDF PCA (1000 Dims)

In [21]:
tfidf_pca_train, tfidf_pca_dev, tfidf_pca_test = load_tfidf_pca()

In [22]:
linear_discriminant_analysis = LinearDiscriminantAnalysis().fit(tfidf_pca_train, train_labels)

In [23]:
train_preds = linear_discriminant_analysis.predict(tfidf_pca_train)
dev_preds = linear_discriminant_analysis.predict(tfidf_pca_dev)
test_preds = linear_discriminant_analysis.predict(tfidf_pca_test)

In [24]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9249626570600123
Accuracy Dev:  0.9096025325360535
Accuracy Test:  0.9093464511595222
F1 Train:  0.5522586948263765
F1 Dev:  0.49147230896878646
F1 Test:  0.4827525893804463
Precision Train:  0.5539791726662117
Precision Dev:  0.513520189235773
Precision Test:  0.49484216553336263
Recall Train:  0.6862203638663568
Recall Dev:  0.4746978491669147
Recall Test:  0.47244530145262886
Confusion Matrix Train: 
[[  986   967     9]
 [  579 20055   144]
 [    0     9    13]]
Confusion Matrix Dev: 
[[ 127  143    2]
 [  86 2459   24]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 116  134    0]
 [ 100 2472   21]
 [   0    3    0]]


### Sentence Transformer Faster No PCA

In [25]:
train, dev, test = load_sent_trans_fast_no_pca()

In [26]:
linear_discriminant_analysis = LinearDiscriminantAnalysis().fit(train, train_labels)

In [27]:
train_preds = linear_discriminant_analysis.predict(train)
dev_preds = linear_discriminant_analysis.predict(dev)
test_preds = linear_discriminant_analysis.predict(test)

In [28]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9253141200246024
Accuracy Dev:  0.9176925782623989
Accuracy Test:  0.9188334504567814
F1 Train:  0.6522347837376588
F1 Dev:  0.48890475977919623
F1 Test:  0.5652457244580075
Precision Train:  0.6577325951298433
Precision Dev:  0.5146858161546176
Precision Test:  0.5703684678455003
Recall Train:  0.6575203992011289
Recall Dev:  0.4711077210175623
Recall Test:  0.5772604876376569
Confusion Matrix Train: 
[[  897  1064     1]
 [  610 20153    15]
 [    0    10    12]]
Confusion Matrix Dev: 
[[ 121  151    0]
 [  80 2488    1]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 108  142    0]
 [  83 2506    4]
 [   0    2    1]]


### Sentence Transformer Faster PCA

In [29]:
train, dev, test = load_sent_trans_fast_pca()

In [30]:
linear_discriminant_analysis = LinearDiscriminantAnalysis().fit(train, train_labels)

In [31]:
train_preds = linear_discriminant_analysis.predict(train)
dev_preds = linear_discriminant_analysis.predict(dev)
test_preds = linear_discriminant_analysis.predict(test)

In [32]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9229417450136191
Accuracy Dev:  0.9138234259584945
Accuracy Test:  0.9188334504567814
F1 Train:  0.597693481551787
F1 Dev:  0.480408269394049
F1 Test:  0.4796357783302687
Precision Train:  0.6071155556372125
Precision Dev:  0.508033670817332
Precision Test:  0.5018333917681307
Recall Train:  0.6029396696474878
Recall Dev:  0.4620102809516177
Recall Test:  0.4638683635428718
Confusion Matrix Train: 
[[  843  1119     0]
 [  600 20156    22]
 [    0    13     9]]
Confusion Matrix Dev: 
[[ 114  158    0]
 [  81 2484    4]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 106  144    0]
 [  83 2509    1]
 [   0    3    0]]


### Sentence Transformer Better No PCA

In [33]:
train, dev, test = load_sent_trans_better_no_pca()

In [34]:
linear_discriminant_analysis = LinearDiscriminantAnalysis().fit(train, train_labels)

In [35]:
train_preds = linear_discriminant_analysis.predict(train)
dev_preds = linear_discriminant_analysis.predict(dev)
test_preds = linear_discriminant_analysis.predict(test)

In [36]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9329584395044372
Accuracy Dev:  0.9257826239887443
Accuracy Test:  0.9314827828531272
F1 Train:  0.734891346582057
F1 Dev:  0.5134893380460697
F1 Test:  0.5132810757818648
Precision Train:  0.7382744935583387
Precision Dev:  0.529818197739428
Precision Test:  0.5319932414045608
Recall Train:  0.7341808612091841
Recall Dev:  0.5003897335500959
Recall Test:  0.49861576038051164
Confusion Matrix Train: 
[[ 1082   880     0]
 [  630 20139     9]
 [    0     7    15]]
Confusion Matrix Dev: 
[[ 145  127    0]
 [  82 2487    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 131  119    0]
 [  73 2520    0]
 [   0    3    0]]


C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Sentence Transformer Better PCA

In [37]:
train, dev, test = load_sent_trans_better_pca()

In [38]:
linear_discriminant_analysis = LinearDiscriminantAnalysis().fit(train, train_labels)

In [39]:
train_preds = linear_discriminant_analysis.predict(train)
dev_preds = linear_discriminant_analysis.predict(dev)
test_preds = linear_discriminant_analysis.predict(test)

In [40]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9285212195764871
Accuracy Dev:  0.9205065072106929
Accuracy Test:  0.9272663387210119
F1 Train:  0.6345459293052274
F1 Dev:  0.49916287013549726
F1 Test:  0.5058152534206223
Precision Train:  0.6412278162653225
Precision Dev:  0.519019019019019
Precision Test:  0.5229137990681378
Recall Train:  0.6314396346677315
Recall Dev:  0.4841988566543784
Recall Test:  0.49225401722586454
Confusion Matrix Train: 
[[ 1015   947     0]
 [  651 20111    16]
 [    0    13     9]]
Confusion Matrix Dev: 
[[ 132  140    0]
 [  84 2485    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 127  123    0]
 [  79 2512    2]
 [   0    3    0]]


C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
