In [3]:
from embeddings_loader import *
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import roc_auc_score

In [4]:
train_labels, dev_labels, test_labels = load_labels()

In [5]:
def computeAllScores(y_pred_train, y_pred_dev, y_pred_test):
    print("Accuracy Train: ", accuracy_score(train_labels, y_pred_train))
    print("Accuracy Dev: ", accuracy_score(dev_labels, y_pred_dev))
    print("Accuracy Test: ", accuracy_score(test_labels, y_pred_test))
    print("F1 Train: ", f1_score(train_labels, y_pred_train, average='macro'))
    print("F1 Dev: ", f1_score(dev_labels, y_pred_dev, average='macro'))
    print("F1 Test: ", f1_score(test_labels, y_pred_test, average='macro'))
    print("Precision Train: ", precision_score(train_labels, y_pred_train, average='macro'))
    print("Precision Dev: ", precision_score(dev_labels, y_pred_dev, average='macro'))
    print("Precision Test: ", precision_score(test_labels, y_pred_test, average='macro'))
    print("Recall Train: ", recall_score(train_labels, y_pred_train, average='macro'))
    print("Recall Dev: ", recall_score(dev_labels, y_pred_dev, average='macro'))
    print("Recall Test: ", recall_score(test_labels, y_pred_test, average='macro'))
    # Confusion Matrix
    print("Confusion Matrix Train: ")
    print(confusion_matrix(train_labels, y_pred_train))
    print("Confusion Matrix Dev: ")
    print(confusion_matrix(dev_labels, y_pred_dev))
    print("Confusion Matrix Test: ")
    print(confusion_matrix(test_labels, y_pred_test))

In [6]:
label_replacement = {
    'Hope_speech': 0,
    'Non_hope_speech': 1,
    'not-English': 2,
}

In [7]:
# Replace labels with numbers
train_labels = [label_replacement[label] for label in train_labels]
dev_labels = [label_replacement[label] for label in dev_labels]
test_labels = [label_replacement[label] for label in test_labels]

In [8]:
logistic_reg = LogisticRegression()
grid = {"penalty" : ['l1', 'l2'], "C" : np.logspace(-3,3,7), "solver" : ['lbfgs', 'liblinear'], "max_iter":[1000]}
gridsearch = GridSearchCV(logistic_reg, param_grid = grid, scoring = "f1_micro", n_jobs=-1)

### Glove Twitter 25

In [7]:
gt25_train, gt25_dev, gt25_test = load_glove_twitter_25()

In [8]:
# Set all NaN values to 0
gt25_train = np.nan_to_num(gt25_train)
gt25_dev = np.nan_to_num(gt25_dev)
gt25_test = np.nan_to_num(gt25_test)

In [9]:
grid_results = gridsearch.fit(gt25_train, train_labels)
best_params = grid_results.best_params_
logistic_reg = grid_results.best_estimator_


c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
35 fits failed out of a total of 140.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
35 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "c:\Users\diksh\AppData\Local\Programs\Python

In [10]:
print(best_params)

{'C': 0.01, 'max_iter': 1000, 'penalty': 'l2', 'solver': 'liblinear'}


In [11]:

logistic_reg = logistic_reg.fit(gt25_train, train_labels)

In [12]:
train_preds = logistic_reg.predict(gt25_train)
dev_preds = logistic_reg.predict(gt25_dev)
test_preds = logistic_reg.predict(gt25_test)

In [13]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9128811176522273
Accuracy Dev:  0.9036229335209286
Accuracy Test:  0.9111033028812369
F1 Train:  0.3184911585290693
F1 Dev:  0.31645725548164577
F1 Test:  0.31782803211374644
Precision Train:  0.6376257633671631
Precision Dev:  0.3012076445069762
Precision Test:  0.3037011009604123
Recall Train:  0.3335032279986408
Recall Dev:  0.3333333333333333
Recall Test:  0.3333333333333333
Confusion Matrix Train: 
[[    1  1961     0]
 [    0 20778     0]
 [    0    22     0]]
Confusion Matrix Dev: 
[[   0  272    0]
 [   0 2569    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[   0  250    0]
 [   0 2593    0]
 [   0    3    0]]


c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### FastText 300

In [14]:
ft300_train, ft300_dev, ft300_test = load_fasttext_300()

In [15]:
# Set all NaN values to 0
ft300_train = np.nan_to_num(ft300_train)
ft300_dev = np.nan_to_num(ft300_dev)
ft300_test = np.nan_to_num(ft300_test)

In [16]:
grid_results = gridsearch.fit(ft300_train, train_labels)
best_params = grid_results.best_params_
logistic_reg = grid_results.best_estimator_

c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
35 fits failed out of a total of 140.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
35 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "c:\Users\diksh\AppData\Local\Programs\Python

In [21]:
print(best_params)

{'C': 1.0, 'max_iter': 1000, 'penalty': 'l2', 'solver': 'lbfgs'}


In [22]:
logistic_reg = logistic_reg.fit(ft300_train, train_labels)

In [23]:
train_preds = logistic_reg.predict(ft300_train)
dev_preds = logistic_reg.predict(ft300_dev)
test_preds = logistic_reg.predict(ft300_test)

In [24]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9142869695105879
Accuracy Dev:  0.9064368624692226
Accuracy Test:  0.9125087842586086
F1 Train:  0.34563763231027994
F1 Dev:  0.3529130466769665
F1 Test:  0.3407610668900991
Precision Train:  0.5116027056355181
Precision Dev:  0.5250482834732568
Precision Test:  0.5188996502555825
Recall Train:  0.3470940162637715
Recall Dev:  0.35190315908379705
Recall Test:  0.34469057719501217
Confusion Matrix Train: 
[[   86  1876     0]
 [   53 20725     0]
 [    0    22     0]]
Confusion Matrix Dev: 
[[  16  256    0]
 [   8 2561    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[   9  241    0]
 [   5 2588    0]
 [   0    3    0]]


c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Word2Vec 300

In [25]:
w2v300_train, w2v300_dev, w2v300_test = load_word2vec_300()

In [26]:
# Set all NaN values to 0
w2v300_train = np.nan_to_num(w2v300_train)
w2v300_dev = np.nan_to_num(w2v300_dev)
w2v300_test = np.nan_to_num(w2v300_test)

In [28]:
grid_results = gridsearch.fit(w2v300_train, train_labels)
best_params = grid_results.best_params_
logistic_reg = grid_results.best_estimator_

c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
35 fits failed out of a total of 140.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
35 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "c:\Users\diksh\AppData\Local\Programs\Python

In [29]:
logistic_reg = logistic_reg.fit(w2v300_train, train_labels)

In [30]:
print(best_params)

{'C': 0.1, 'max_iter': 1000, 'penalty': 'l2', 'solver': 'lbfgs'}


In [31]:
train_preds = logistic_reg.predict(w2v300_train)
dev_preds = logistic_reg.predict(w2v300_dev)
test_preds = logistic_reg.predict(w2v300_test)

In [32]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.914243036640014
Accuracy Dev:  0.9064368624692226
Accuracy Test:  0.9104005621925509
F1 Train:  0.3470623060519927
F1 Dev:  0.35490221977435915
F1 Test:  0.3398700047159173
Precision Train:  0.5076500186724847
Precision Dev:  0.520871448986465
Precision Test:  0.45455296060391603
Recall Train:  0.3478472339352893
Recall Dev:  0.35299889710652654
Recall Test:  0.3439192698290268
Confusion Matrix Train: 
[[   91  1871     0]
 [   59 20719     0]
 [    0    22     0]]
Confusion Matrix Dev: 
[[  17  255    0]
 [   9 2560    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[   9  241    0]
 [  11 2582    0]
 [   0    3    0]]


c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### TF-IDF PCA (1000 Dims)

In [33]:
tfidf_pca_train, tfidf_pca_dev, tfidf_pca_test = load_tfidf_pca()

In [34]:
grid_results = gridsearch.fit(tfidf_pca_train, train_labels)
best_params = grid_results.best_params_
logistic_reg = grid_results.best_estimator_

c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
35 fits failed out of a total of 140.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
35 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "c:\Users\diksh\AppData\Local\Programs\Python

In [35]:
print(best_params)

{'C': 10.0, 'max_iter': 1000, 'penalty': 'l2', 'solver': 'liblinear'}


In [36]:

logistic_reg = logistic_reg.fit(tfidf_pca_train, train_labels)

In [37]:
train_preds = logistic_reg.predict(tfidf_pca_train)
dev_preds = logistic_reg.predict(tfidf_pca_dev)
test_preds = logistic_reg.predict(tfidf_pca_test)

In [38]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9358140760917318
Accuracy Dev:  0.9162856137882518
Accuracy Test:  0.9226985242445538
F1 Train:  0.4944128742208025
F1 Dev:  0.466049692708707
F1 Test:  0.46496183555007087
Precision Train:  0.5667914146063164
Precision Dev:  0.5171771401748518
Precision Test:  0.5199612005956529
Recall Train:  0.4604974052674116
Recall Dev:  0.44100378571046944
Recall Test:  0.4387772207224579
Confusion Matrix Train: 
[[  772  1190     0]
 [  249 20529     0]
 [    0    22     0]]
Confusion Matrix Dev: 
[[  94  178    0]
 [  58 2511    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  84  166    0]
 [  51 2542    0]
 [   0    3    0]]


c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Seentence Transformer Faster No PCA

In [39]:
train, dev, test = load_sent_trans_fast_no_pca()

In [40]:
grid_results = gridsearch.fit(train, train_labels)
best_params = grid_results.best_params_
logistic_reg = grid_results.best_estimator_

c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
35 fits failed out of a total of 140.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
35 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "c:\Users\diksh\AppData\Local\Programs\Python

In [41]:
print(best_params)

{'C': 1.0, 'max_iter': 1000, 'penalty': 'l2', 'solver': 'liblinear'}


In [42]:

logistic_reg = logistic_reg.fit(train, train_labels)

In [43]:
train_preds = logistic_reg.predict(train)
dev_preds = logistic_reg.predict(dev)
test_preds = logistic_reg.predict(test)

In [44]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9288726825410772
Accuracy Dev:  0.9176925782623989
Accuracy Test:  0.9248067463106114
F1 Train:  0.4641122403976934
F1 Dev:  0.44951195604016525
F1 Test:  0.45951751150945497
Precision Train:  0.5513348721347111
Precision Dev:  0.536334808014281
Precision Test:  0.5359341253573985
Recall Train:  0.4319616755313121
Recall Dev:  0.4207037719720041
Recall Test:  0.4299102712430904
Confusion Matrix Train: 
[[  603  1359     0]
 [  238 20540     0]
 [    0    22     0]]
Confusion Matrix Dev: 
[[  75  197    0]
 [  35 2534    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  76  174    0]
 [  37 2556    0]
 [   0    3    0]]


c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Sentence Transformer Faster PCA

In [45]:
train, dev, test = load_sent_trans_fast_pca()

In [46]:
grid_results = gridsearch.fit(train, train_labels)
best_params = grid_results.best_params_
logistic_reg = grid_results.best_estimator_

c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
35 fits failed out of a total of 140.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
35 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "c:\Users\diksh\AppData\Local\Programs\Python

In [47]:
print(best_params)

{'C': 1.0, 'max_iter': 1000, 'penalty': 'l1', 'solver': 'liblinear'}


In [48]:

logistic_reg = logistic_reg.fit(train, train_labels)

In [49]:
train_preds = logistic_reg.predict(train)
dev_preds =logistic_reg.predict(dev)
test_preds = logistic_reg.predict(test)

In [50]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9272032334592742
Accuracy Dev:  0.9162856137882518
Accuracy Test:  0.9251581166549543
F1 Train:  0.46161651290490496
F1 Dev:  0.4520082267407457
F1 Test:  0.463105918850385
Precision Train:  0.5412229829840284
Precision Dev:  0.5252920514998705
Precision Test:  0.5352361780737942
Recall Train:  0.43104435227057863
Recall Dev:  0.4245677153695266
Recall Test:  0.4336531687877619
Confusion Matrix Train: 
[[  601  1361     0]
 [  274 20504     0]
 [    0    22     0]]
Confusion Matrix Dev: 
[[  79  193    0]
 [  43 2526    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  79  171    0]
 [  39 2554    0]
 [   0    3    0]]


c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Sentence Transformer Better No PCA

In [9]:
train, dev, test = load_sent_trans_better_no_pca()

In [10]:
grid_results = gridsearch.fit(train, train_labels)
best_params = grid_results.best_params_
logistic_reg = grid_results.best_estimator_

c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
35 fits failed out of a total of 140.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
35 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "c:\Users\diksh\AppData\Local\Programs\Python

In [11]:
print(best_params)

{'C': 1.0, 'max_iter': 1000, 'penalty': 'l2', 'solver': 'lbfgs'}


In [12]:

logistic_reg = logistic_reg.fit(train, train_labels)

In [13]:
train_preds = logistic_reg.predict(train)
dev_preds =logistic_reg.predict(dev)
test_preds = logistic_reg.predict(test)

In [14]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9352868816448466
Accuracy Dev:  0.9240239183960605
Accuracy Test:  0.9311314125087843
F1 Train:  0.49553253878259124
F1 Dev:  0.4839473214912968
F1 Test:  0.48895830301854454
Precision Train:  0.5613225408376444
Precision Dev:  0.543402236250361
Precision Test:  0.5492590043222164
Recall Train:  0.46307423096784817
Recall Dev:  0.4548157137514406
Recall Test:  0.4587293996657668
Confusion Matrix Train: 
[[  790  1172     0]
 [  279 20499     0]
 [    0    22     0]]
Confusion Matrix Dev: 
[[ 104  168    0]
 [  46 2523    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  98  152    0]
 [  41 2552    0]
 [   0    3    0]]


c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Sentence Transformer Better PCA

In [15]:
train, dev, test = load_sent_trans_better_pca()

In [16]:
grid_results = gridsearch.fit(train, train_labels)
best_params = grid_results.best_params_
logistic_reg = grid_results.best_estimator_

c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
35 fits failed out of a total of 140.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
35 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "c:\Users\diksh\AppData\Local\Programs\Python

In [17]:
print(best_params)

{'C': 1.0, 'max_iter': 1000, 'penalty': 'l2', 'solver': 'lbfgs'}


In [18]:

logistic_reg = logistic_reg.fit(train, train_labels)

In [19]:
train_preds = logistic_reg.predict(train)
dev_preds =logistic_reg.predict(dev)
test_preds = logistic_reg.predict(test)

In [20]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9336174325630436
Accuracy Dev:  0.9236721772775237
Accuracy Test:  0.9311314125087843
F1 Train:  0.4904077199598218
F1 Dev:  0.48188597793477134
F1 Test:  0.4872493519552343
Precision Train:  0.5558614258697098
Precision Dev:  0.5433597771452795
Precision Test:  0.5510663005314426
Recall Train:  0.45861831041595097
Recall Dev:  0.45249448553263266
Recall Test:  0.4563198354544286
Confusion Matrix Train: 
[[  765  1197     0]
 [  292 20486     0]
 [    0    22     0]]
Confusion Matrix Dev: 
[[ 102  170    0]
 [  45 2524    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  96  154    0]
 [  39 2554    0]
 [   0    3    0]]


c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
