In [1]:
from embeddings_loader import *
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import roc_auc_score
from utils import *

In [2]:
train_labels, dev_labels, test_labels = load_labels()

In [4]:
label_replacement = {
    'Hope_speech': 0,
    'Non_hope_speech': 1,
    'not-English': 2,
}

In [5]:
# Replace labels with numbers
train_labels = [label_replacement[label] for label in train_labels]
dev_labels = [label_replacement[label] for label in dev_labels]
test_labels = [label_replacement[label] for label in test_labels]

In [6]:
mlp = MLPClassifier()
gridsearch = GridSearchCV(mlp, param_grid = {
    "activation": ["relu", "logistic", "tanh"],
    "early_stopping": [True],
    "learning_rate_init": [0.0001, 0.001, 0.01],
    "max_iter": [1000, 5000],
    "hidden_layer_sizes": [(150, 150)]
}, scoring = "f1_micro", verbose = 4)

### Glove Twitter 25

In [7]:
gt25_train, gt25_dev, gt25_test = load_glove_twitter_25()

In [8]:
# Set all NaN values to 0
gt25_train = np.nan_to_num(gt25_train)
gt25_dev = np.nan_to_num(gt25_dev)
gt25_test = np.nan_to_num(gt25_test)

In [9]:
grid_results = gridsearch.fit(gt25_train, train_labels)
best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

Fitting 5 folds for each of 18 candidates, totalling 90 fits
[CV 1/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.913 total time=   6.0s
[CV 2/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.913 total time=   2.8s
[CV 3/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.913 total time=   2.6s
[CV 4/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.913 total time=   3.4s
[CV 5/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.913 total time=   2.6s
[CV 1/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=5000;, score=0.913 total time=   2.6s
[CV

In [10]:
best_params

{'activation': 'relu',
 'early_stopping': True,
 'hidden_layer_sizes': (150, 150),
 'learning_rate_init': 0.001,
 'max_iter': 1000}

In [11]:
mlp = mlp.fit(gt25_train, train_labels)
save_model(mlp, "mlp_gt25.joblib")

In [12]:
train_preds = mlp.predict(gt25_train)
dev_preds = mlp.predict(gt25_dev)
test_preds = mlp.predict(gt25_test)

In [13]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9246551269659959
Accuracy Dev:  0.9124164614843475
Accuracy Test:  0.9209416725228391
F1 Train:  0.5473182873975259
F1 Dev:  0.413843004548206
F1 Test:  0.4242921082001541
Precision Train:  0.8343517905142366
Precision Dev:  0.5285806037251124
Precision Test:  0.5387725387725387
Recall Train:  0.4760977968158993
Recall Dev:  0.3913640388035324
Recall Test:  0.39837665509705616
Confusion Matrix Train: 
[[  408  1554     0]
 [  143 20634     1]
 [    0    17     5]]
Confusion Matrix Dev: 
[[  50  222    0]
 [  25 2544    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  51  199    0]
 [  23 2570    0]
 [   0    3    0]]


c:\Kyode\clg\ml\ML_Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Kyode\clg\ml\ML_Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### FastText 300 

In [14]:
ft300_train, ft300_dev, ft300_test = load_fasttext_300()

In [15]:
# Set all NaN values to 0
ft300_train = np.nan_to_num(ft300_train)
ft300_dev = np.nan_to_num(ft300_dev)
ft300_test = np.nan_to_num(ft300_test)

In [16]:
grid_results = gridsearch.fit(ft300_train, train_labels)
best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

Fitting 5 folds for each of 18 candidates, totalling 90 fits


c:\Kyode\clg\ml\ML_Project\venv\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:709: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")


[CV 1/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.913 total time=   3.8s
[CV 2/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.913 total time=   4.0s
[CV 3/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.913 total time=   3.6s
[CV 4/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.913 total time=   4.0s
[CV 5/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.913 total time=   3.9s
[CV 1/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=5000;, score=0.913 total time=   3.7s
[CV 2/5] END activation=relu, early_stopping=True, hidden_layer_

In [17]:
best_params

In [18]:
mlp = mlp.fit(ft300_train, train_labels)
save_model(mlp, "mlp_ft300.joblib")

In [19]:
train_preds = mlp.predict(ft300_train)
dev_preds = mlp.predict(ft300_dev)
test_preds = mlp.predict(ft300_test)

In [20]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9386257798084526
Accuracy Dev:  0.9148786493141048
Accuracy Test:  0.9255094869992972
F1 Train:  0.6167268204357556
F1 Dev:  0.4409317033156042
F1 Test:  0.45935081292102825
Precision Train:  0.9254397215869212
Precision Dev:  0.5245198275667501
Precision Test:  0.5410128949864749
Recall Train:  0.5301243003836873
Recall Dev:  0.4141870644715652
Recall Test:  0.42896259159274974
Confusion Matrix Train: 
[[  726  1236     0]
 [  144 20634     0]
 [    1    16     5]]
Confusion Matrix Dev: 
[[  70  202    0]
 [  38 2531    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  75  175    0]
 [  34 2559    0]
 [   0    3    0]]


c:\Kyode\clg\ml\ML_Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Kyode\clg\ml\ML_Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Word2Vec 300

In [21]:
w2v300_train, w2v300_dev, w2v300_test = load_word2vec_300()

In [22]:
# Set all NaN values to 0
w2v300_train = np.nan_to_num(w2v300_train)
w2v300_dev = np.nan_to_num(w2v300_dev)
w2v300_test = np.nan_to_num(w2v300_test)

In [23]:
grid_results = gridsearch.fit(w2v300_train, train_labels)
best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

Fitting 5 folds for each of 18 candidates, totalling 90 fits
[CV 1/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.925 total time=  14.2s
[CV 2/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.916 total time=   6.5s
[CV 3/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.922 total time=  14.8s
[CV 4/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.927 total time=  16.6s
[CV 5/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.924 total time=  17.7s
[CV 1/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=5000;, score=0.925 total time=  15.9s
[CV

In [24]:
best_params

{'activation': 'relu',
 'early_stopping': True,
 'hidden_layer_sizes': (150, 150),
 'learning_rate_init': 0.001,
 'max_iter': 1000}

In [25]:
mlp = mlp.fit(w2v300_train, train_labels)
save_model(mlp, "mlp_w2v300.joblib")

In [26]:
train_preds = mlp.predict(w2v300_train)
dev_preds = mlp.predict(w2v300_dev)
test_preds = mlp.predict(w2v300_test)

In [27]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9346278885862402
Accuracy Dev:  0.9222652128033767
Accuracy Test:  0.9279690794096979
F1 Train:  0.5990972724109318
F1 Dev:  0.4669930166113372
F1 Test:  0.46680671100824983
Precision Train:  0.8556462312736784
Precision Dev:  0.5501029262635034
Precision Test:  0.551528442317916
Recall Train:  0.5192794475248306
Recall Dev:  0.4355394064982942
Recall Test:  0.4346815786090757
Confusion Matrix Train: 
[[  665  1297     0]
 [  173 20604     1]
 [    0    17     5]]
Confusion Matrix Dev: 
[[  87  185    0]
 [  34 2535    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  79  171    0]
 [  31 2562    0]
 [   0    3    0]]


c:\Kyode\clg\ml\ML_Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Kyode\clg\ml\ML_Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### TF-IDF PCA (1000 Dims)

In [28]:
tfidf_pca_train, tfidf_pca_dev, tfidf_pca_test = load_tfidf_pca()

In [29]:
grid_results = gridsearch.fit(tfidf_pca_train, train_labels)
best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

Fitting 5 folds for each of 18 candidates, totalling 90 fits
[CV 1/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.923 total time=  26.1s
[CV 2/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.926 total time=  21.4s
[CV 3/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.930 total time=  26.4s
[CV 4/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.926 total time=  24.6s
[CV 5/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.921 total time=  39.1s
[CV 1/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=5000;, score=0.922 total time=  32.2s
[CV

In [30]:
best_params

{'activation': 'relu',
 'early_stopping': True,
 'hidden_layer_sizes': (150, 150),
 'learning_rate_init': 0.001,
 'max_iter': 5000}

In [31]:
mlp = mlp.fit(tfidf_pca_train, train_labels)
save_model(mlp, "mlp_tfidf_pca.joblib")

In [32]:
train_preds = mlp.predict(tfidf_pca_train)
dev_preds = mlp.predict(tfidf_pca_dev)
test_preds = mlp.predict(tfidf_pca_test)

In [33]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9599771549073016
Accuracy Dev:  0.92191347168484
Accuracy Test:  0.9244553759662685
F1 Train:  0.5707153328751269
F1 Dev:  0.4866373984806554
F1 Test:  0.4815646822965633
Precision Train:  0.6180409792981062
Precision Dev:  0.530653668126435
Precision Test:  0.5200931598927956
Recall Train:  0.539015821741199
Recall Dev:  0.4617073668704539
Recall Test:  0.45869649055148476
Confusion Matrix Train: 
[[ 1225   737     0]
 [  152 20626     0]
 [    0    22     0]]
Confusion Matrix Dev: 
[[ 111  161    0]
 [  59 2510    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 100  150    0]
 [  62 2531    0]
 [   0    3    0]]


c:\Kyode\clg\ml\ML_Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Kyode\clg\ml\ML_Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Kyode\clg\ml\ML_Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Sentence Transformer Faster No PCA

In [34]:
train, dev, test = load_sent_trans_fast_no_pca()

In [35]:
grid_results = gridsearch.fit(train, train_labels)
best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

Fitting 5 folds for each of 18 candidates, totalling 90 fits
[CV 1/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.927 total time=   9.7s
[CV 2/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.931 total time=   8.8s
[CV 3/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.922 total time=   6.3s
[CV 4/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.931 total time=  13.5s
[CV 5/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.923 total time=   9.5s
[CV 1/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=5000;, score=0.926 total time=   6.4s
[CV

In [36]:
best_params

{'activation': 'logistic',
 'early_stopping': True,
 'hidden_layer_sizes': (150, 150),
 'learning_rate_init': 0.01,
 'max_iter': 5000}

In [37]:
mlp = mlp.fit(train, train_labels)
save_model(mlp, "mlp_faster_no_pca.joblib")

In [38]:
train_preds = mlp.predict(train)
dev_preds = mlp.predict(dev)
test_preds = mlp.predict(test)

In [39]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9404270275019769
Accuracy Dev:  0.9257826239887443
Accuracy Test:  0.926563598032326
F1 Train:  0.5040795208272808
F1 Dev:  0.47962118805453396
F1 Test:  0.4737836786410388
Precision Train:  0.5904085760656408
Precision Dev:  0.5595333984564674
Precision Test:  0.5352902644722836
Recall Train:  0.4658743285775582
Recall Dev:  0.4466985704363489
Recall Test:  0.44501041264944075
Confusion Matrix Train: 
[[  796  1166     0]
 [  168 20610     0]
 [    0    22     0]]
Confusion Matrix Dev: 
[[  96  176    0]
 [  33 2536    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  88  162    0]
 [  44 2549    0]
 [   0    3    0]]


c:\Kyode\clg\ml\ML_Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Kyode\clg\ml\ML_Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Kyode\clg\ml\ML_Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Sentence Transformer Faster PCA

In [40]:
train, dev, test = load_sent_trans_fast_pca()

In [41]:
grid_results = gridsearch.fit(train, train_labels)
best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

Fitting 5 folds for each of 18 candidates, totalling 90 fits
[CV 1/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.925 total time=   5.7s
[CV 2/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.925 total time=  11.6s
[CV 3/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.924 total time=   6.9s
[CV 4/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.927 total time=   6.3s
[CV 5/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.926 total time=   5.4s
[CV 1/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=5000;, score=0.921 total time=   4.6s
[CV

In [42]:
best_params

{'activation': 'relu',
 'early_stopping': True,
 'hidden_layer_sizes': (150, 150),
 'learning_rate_init': 0.001,
 'max_iter': 5000}

In [43]:
mlp = mlp.fit(train, train_labels)
save_model(mlp, "mlp_faster_pca.joblib")

In [44]:
train_preds = mlp.predict(train)
dev_preds = mlp.predict(dev)
test_preds = mlp.predict(test)

In [45]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9414814163957473
Accuracy Dev:  0.92191347168484
Accuracy Test:  0.9272663387210119
F1 Train:  0.5121928790750737
F1 Dev:  0.47549126554159143
F1 Test:  0.47748936063498454
Precision Train:  0.5843008864401824
Precision Dev:  0.5391891022799763
Precision Test:  0.5364463497576152
Recall Train:  0.4762597348465782
Recall Dev:  0.4463670345522405
Recall Test:  0.4488818614217766
Confusion Matrix Train: 
[[  861  1101     0]
 [  209 20569     0]
 [    0    22     0]]
Confusion Matrix Dev: 
[[  97  175    0]
 [  45 2524    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  91  159    0]
 [  45 2548    0]
 [   0    3    0]]


c:\Kyode\clg\ml\ML_Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Kyode\clg\ml\ML_Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Kyode\clg\ml\ML_Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Sentence Transformer Better No PCA

In [46]:
train, dev, test = load_sent_trans_better_no_pca()

In [47]:
grid_results = gridsearch.fit(train, train_labels)
best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

Fitting 5 folds for each of 18 candidates, totalling 90 fits
[CV 1/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.929 total time=   6.2s
[CV 2/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.930 total time=   7.3s
[CV 3/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.926 total time=   4.5s
[CV 4/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.932 total time=  10.9s
[CV 5/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.927 total time=   7.2s
[CV 1/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=5000;, score=0.926 total time=  18.5s
[CV

In [48]:
best_params

{'activation': 'logistic',
 'early_stopping': True,
 'hidden_layer_sizes': (150, 150),
 'learning_rate_init': 0.01,
 'max_iter': 5000}

In [49]:
mlp = mlp.fit(train, train_labels)
save_model(mlp, "mlp_better_no_pca.joblib")

In [50]:
train_preds = mlp.predict(train)
dev_preds = mlp.predict(dev)
test_preds = mlp.predict(test)

In [51]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9399876987962393
Accuracy Dev:  0.9215617305663032
Accuracy Test:  0.9339423752635277
F1 Train:  0.5060234036457886
F1 Dev:  0.4783846641110247
F1 Test:  0.49300581963803136
Precision Train:  0.5825699641489116
Precision Dev:  0.5348698949384817
Precision Test:  0.5636671212142512
Recall Train:  0.46971405594543514
Recall Dev:  0.45062023446980976
Recall Test:  0.4597578094870806
Confusion Matrix Train: 
[[  822  1140     0]
 [  204 20574     0]
 [    0    22     0]]
Confusion Matrix Dev: 
[[ 101  171    0]
 [  50 2519    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  98  152    0]
 [  33 2560    0]
 [   0    3    0]]


c:\Kyode\clg\ml\ML_Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Kyode\clg\ml\ML_Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Kyode\clg\ml\ML_Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Sentence Transformer Better PCA

In [52]:
train, dev, test = load_sent_trans_better_pca()

In [53]:
grid_results = gridsearch.fit(train, train_labels)
best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

Fitting 5 folds for each of 18 candidates, totalling 90 fits
[CV 1/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.931 total time=   5.6s
[CV 2/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.931 total time=  12.3s
[CV 3/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.932 total time=   7.6s
[CV 4/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.933 total time=   6.3s
[CV 5/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=1000;, score=0.926 total time=   9.8s
[CV 1/5] END activation=relu, early_stopping=True, hidden_layer_sizes=(150, 150), learning_rate_init=0.0001, max_iter=5000;, score=0.930 total time=   6.7s
[CV

In [54]:
best_params

{'activation': 'relu',
 'early_stopping': True,
 'hidden_layer_sizes': (150, 150),
 'learning_rate_init': 0.0001,
 'max_iter': 5000}

In [55]:
mlp = mlp.fit(train, train_labels)
save_model(mlp, "mlp_better_pca.joblib")

In [56]:
train_preds = mlp.predict(train)
dev_preds = mlp.predict(dev)
test_preds = mlp.predict(test)

In [57]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9349354186802565
Accuracy Dev:  0.9222652128033767
Accuracy Test:  0.9283204497540407
F1 Train:  0.49202119499173574
F1 Dev:  0.4767819046159967
F1 Test:  0.4789162604562482
Precision Train:  0.5633733213602462
Precision Dev:  0.5400431667098333
Precision Test:  0.5414993436410783
Recall Train:  0.45863803252263696
Recall Dev:  0.44759252474831895
Recall Test:  0.4492675151047692
Confusion Matrix Train: 
[[  762  1200     0]
 [  259 20519     0]
 [    0    22     0]]
Confusion Matrix Dev: 
[[  98  174    0]
 [  45 2524    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  91  159    0]
 [  42 2551    0]
 [   0    3    0]]


c:\Kyode\clg\ml\ML_Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Kyode\clg\ml\ML_Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Kyode\clg\ml\ML_Project\venv\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
