In [1]:
from embeddings_loader import *
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import roc_auc_score
from utils import *

--ip=127.0.0.1


In [6]:
train_labels, dev_labels, test_labels = load_labels()
train_augmented_labels, dev_augmented_labels, test_augmented_labels = load_augmented_labels()

In [7]:
label_replacement = {
    'Hope_speech': 0,
    'Non_hope_speech': 1,
    'not-English': 2,
}

In [8]:
# Replace labels with numbers
train_labels = [label_replacement[label] for label in train_labels]
dev_labels = [label_replacement[label] for label in dev_labels]
test_labels = [label_replacement[label] for label in test_labels]
train_augmented_labels = [label_replacement[label] for label in train_augmented_labels]

In [9]:
gaussian_nb = GaussianNB()
gridsearch = GridSearchCV(gaussian_nb, param_grid = {'var_smoothing': np.logspace(0,-9, num=100)}, scoring = "f1_micro")

### Glove Twitter 25

In [23]:
gt25_train, gt25_dev, gt25_test = load_glove_twitter_25()

In [24]:
# Set all NaN values to 0
gt25_train = np.nan_to_num(gt25_train)
gt25_dev = np.nan_to_num(gt25_dev)
gt25_test = np.nan_to_num(gt25_test)

In [25]:
grid_results = gridsearch.fit(gt25_train, train_labels)
best_params = grid_results.best_params_
gaussian_nb = grid_results.best_estimator_

In [26]:
print(best_params)

{'var_smoothing': 1.0}


In [27]:

gaussian_nb = gaussian_nb.fit(gt25_train, train_labels)
save_model(gaussian_nb, "gaussian_nb_gt25.joblib")

In [28]:
train_preds = gaussian_nb.predict(gt25_train)
dev_preds = gaussian_nb.predict(gt25_dev)
test_preds = gaussian_nb.predict(gt25_test)

In [29]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9121342588524735
Accuracy Dev:  0.9032711924023918
Accuracy Test:  0.910049191848208
Weighted F1 Train:  0.8710825211224449
Weighted F1 Dev:  0.8578571879045266
Weighted F1 Test:  0.8681963040700529
Macro F1 Train:  0.38745703809246573
Macro F1 Dev:  0.3164510166358595
Macro F1 Test:  0.31763551631101306
Micro F1 Train:  0.9121342588524736
Micro F1 Dev:  0.9032711924023918
Micro F1 Test:  0.910049191848208
Weighted Recall Train:  0.9121342588524735
Weighted Recall Dev:  0.9032711924023918
Weighted Recall Test:  0.910049191848208
Macro Recall Train:  0.40875401429833996
Macro Recall Dev:  0.33320358115998444
Macro Recall Test:  0.33294767965034067
Micro Recall Train:  0.9121342588524735
Micro Recall Dev:  0.9032711924023918
Micro Recall Test:  0.910049191848208
Confusion Matrix Train: 
[[    0  1962     0]
 [    0 20757    21]
 [    0    17     5]]
Confusion Matrix Dev: 
[[   0  271    1]
 [   0 2568    1]
 [   0    2    0]]
Confusion Matrix Test: 
[[   0  250    0]
 

### FastText 300

In [30]:
ft300_train, ft300_dev, ft300_test = load_fasttext_300()

In [31]:
# Set all NaN values to 0
ft300_train = np.nan_to_num(ft300_train)
ft300_dev = np.nan_to_num(ft300_dev)
ft300_test = np.nan_to_num(ft300_test)

In [32]:
grid_results = gridsearch.fit(ft300_train, train_labels)
best_params = grid_results.best_params_
gaussian_nb = grid_results.best_estimator_

In [33]:
print(best_params)

{'var_smoothing': 1.0}


In [34]:
gaussian_nb = gaussian_nb.fit(ft300_train, train_labels)
save_model(gaussian_nb, "gaussian_nb_ft300.joblib")

In [35]:
train_preds = gaussian_nb.predict(ft300_train)
dev_preds = gaussian_nb.predict(ft300_dev)
test_preds = gaussian_nb.predict(ft300_test)

In [36]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9130568491345225
Accuracy Dev:  0.9036229335209286
Accuracy Test:  0.9111033028812369
Weighted F1 Train:  0.8717660081924135
Weighted F1 Dev:  0.85787410059692
Weighted F1 Test:  0.8687225094212346
Macro F1 Train:  0.37475414135020296
Macro F1 Dev:  0.31645725548164577
Macro F1 Test:  0.31782803211374644
Micro F1 Train:  0.9130568491345225
Micro F1 Dev:  0.9036229335209286
Micro F1 Test:  0.9111033028812369
Weighted Recall Train:  0.9130568491345225
Weighted Recall Dev:  0.9036229335209286
Weighted Recall Test:  0.9111033028812369
Macro Recall Train:  0.36414604763228614
Macro Recall Dev:  0.3333333333333333
Macro Recall Test:  0.3333333333333333
Micro Recall Train:  0.9130568491345225
Micro Recall Dev:  0.9036229335209286
Micro Recall Test:  0.9111033028812369
Confusion Matrix Train: 
[[    3  1959     0]
 [    0 20778     0]
 [    0    20     2]]
Confusion Matrix Dev: 
[[   0  272    0]
 [   0 2569    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[   0  250    0]


### Word2Vec 300

In [37]:
w2v300_train, w2v300_dev, w2v300_test = load_word2vec_300()

In [38]:
# Set all NaN values to 0
w2v300_train = np.nan_to_num(w2v300_train)
w2v300_dev = np.nan_to_num(w2v300_dev)
w2v300_test = np.nan_to_num(w2v300_test)

In [39]:
grid_results = gridsearch.fit(w2v300_train, train_labels)
best_params = grid_results.best_params_
gaussian_nb = grid_results.best_estimator_

In [40]:
print(best_params)

{'var_smoothing': 2.848035868435799e-05}


In [41]:
gaussian_nb = gaussian_nb.fit(w2v300_train, train_labels)
save_model(gaussian_nb, "gaussian_nb_w2v300.joblib")

In [42]:
train_preds = gaussian_nb.predict(w2v300_train)
dev_preds = gaussian_nb.predict(w2v300_dev)
test_preds = gaussian_nb.predict(w2v300_test)

In [43]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.4608558123187769
Accuracy Dev:  0.46289131199437217
Accuracy Test:  0.4631061138439916
Weighted F1 Train:  0.5622747686382187
Weighted F1 Dev:  0.558758675347762
Weighted F1 Test:  0.5614503893269573
Macro F1 Train:  0.2770942452599117
Macro F1 Dev:  0.28169345948247493
Macro F1 Test:  0.28309328315380894
Micro F1 Train:  0.4608558123187769
Micro F1 Dev:  0.46289131199437217
Micro F1 Test:  0.4631061138439916
Weighted Recall Train:  0.4608558123187769
Weighted Recall Dev:  0.46289131199437217
Weighted Recall Test:  0.4631061138439916
Macro Recall Train:  0.5272260293202522
Macro Recall Dev:  0.5652042833482166
Macro Recall Test:  0.5358268843467455
Micro Recall Train:  0.4608558123187769
Micro Recall Dev:  0.46289131199437217
Micro Recall Test:  0.4631061138439916
Confusion Matrix Train: 
[[ 1546   347    69]
 [10010  8936  1832]
 [    6     8     8]]
Confusion Matrix Dev: 
[[ 208   60    4]
 [1221 1107  241]
 [   0    1    1]]
Confusion Matrix Test: 
[[ 212   33    

### TF-IDF PCA (1000 Dims)

In [44]:
tfidf_pca_train, tfidf_pca_dev, tfidf_pca_test = load_tfidf_pca()

In [45]:
grid_results = gridsearch.fit(tfidf_pca_train, train_labels)
best_params = grid_results.best_params_
gaussian_nb = grid_results.best_estimator_

In [46]:
print(best_params)

{'var_smoothing': 1.0}


In [47]:

gaussian_nb = gaussian_nb.fit(tfidf_pca_train, train_labels)
save_model(gaussian_nb, "gaussian_nb_tfidf_pca.joblib")

In [48]:
train_preds = gaussian_nb.predict(tfidf_pca_train)
dev_preds = gaussian_nb.predict(tfidf_pca_dev)
test_preds = gaussian_nb.predict(tfidf_pca_test)

In [49]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9001405851858361
Accuracy Dev:  0.8906085121350686
Accuracy Test:  0.8952916373858046
Weighted F1 Train:  0.8670924046649676
Weighted F1 Dev:  0.8565049384533437
Weighted F1 Test:  0.8649236676142507
Macro F1 Train:  0.36174683265238466
Macro F1 Dev:  0.3304907643065604
Macro F1 Test:  0.32997507762137473
Micro F1 Train:  0.9001405851858361
Micro F1 Dev:  0.8906085121350686
Micro F1 Test:  0.8952916373858046
Weighted Recall Train:  0.9001405851858361
Weighted Recall Dev:  0.8906085121350686
Weighted Recall Test:  0.8952916373858046
Macro Recall Train:  0.6199634469350762
Macro Recall Dev:  0.33620266907853064
Macro Recall Test:  0.3347772207224579
Micro Recall Train:  0.9001405851858361
Micro Recall Dev:  0.8906085121350686
Micro Recall Test:  0.8952916373858046
Confusion Matrix Train: 
[[   24  1929     9]
 [   49 20446   283]
 [    0     3    19]]
Confusion Matrix Dev: 
[[   7  261    4]
 [   8 2525   36]
 [   0    2    0]]
Confusion Matrix Test: 
[[   6  242    2]

### Seentence Transformer Faster No PCA

In [50]:
train, dev, test = load_sent_trans_fast_no_pca()

In [51]:
grid_results = gridsearch.fit(train, train_labels)
best_params = grid_results.best_params_
gaussian_nb = grid_results.best_estimator_

In [52]:
print(best_params)

{'var_smoothing': 6.579332246575683e-05}


In [53]:

gaussian_nb = gaussian_nb.fit(train, train_labels)
save_model(gaussian_nb, "gaussian_nb_sent_trans_fast_no_pca.joblib")

In [54]:
train_preds = gaussian_nb.predict(train)
dev_preds = gaussian_nb.predict(dev)
test_preds = gaussian_nb.predict(test)

In [55]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.8321325015376505
Accuracy Dev:  0.8315160042208934
Accuracy Test:  0.8271257905832747
Weighted F1 Train:  0.8611642258440492
Weighted F1 Dev:  0.8570703533077054
Weighted F1 Test:  0.8571867967809591
Macro F1 Train:  0.5451696314647192
Macro F1 Dev:  0.45129085966270077
Macro F1 Test:  0.48578249509654664
Micro F1 Train:  0.8321325015376505
Micro F1 Dev:  0.8315160042208934
Micro F1 Test:  0.8271257905832747
Weighted Recall Train:  0.8321325015376505
Weighted Recall Dev:  0.8315160042208934
Weighted Recall Test:  0.8271257905832747
Macro Recall Train:  0.7884055804231608
Macro Recall Dev:  0.5225945282745251
Macro Recall Test:  0.6412959677764922
Micro Recall Train:  0.8321325015376505
Micro Recall Dev:  0.8315160042208934
Micro Recall Test:  0.8271257905832747
Confusion Matrix Train: 
[[ 1477   480     5]
 [ 3259 17447    72]
 [    1     4    17]]
Confusion Matrix Dev: 
[[ 197   75    0]
 [ 400 2167    2]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 189   60    1]


### Sentence Transformer Faster PCA

In [56]:
train, dev, test = load_sent_trans_fast_pca()

In [57]:
grid_results = gridsearch.fit(train, train_labels)
best_params = grid_results.best_params_
gaussian_nb = grid_results.best_estimator_

In [58]:
print(best_params)

{'var_smoothing': 0.533669923120631}


In [59]:

gaussian_nb = gaussian_nb.fit(train, train_labels)
save_model(gaussian_nb, "gaussian_nb_sent_trans_fast_pca.joblib")

In [60]:
train_preds = gaussian_nb.predict(train)
dev_preds =gaussian_nb.predict(dev)
test_preds = gaussian_nb.predict(test)

In [61]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9204815042614884
Accuracy Dev:  0.9092507914175167
Accuracy Test:  0.9216444132115249
Weighted F1 Train:  0.8980950428133775
Weighted F1 Dev:  0.8852250360925764
Weighted F1 Test:  0.9021281749511217
Macro F1 Train:  0.41076493057881597
Macro F1 Dev:  0.4053389971680826
Macro F1 Test:  0.4292238585508407
Micro F1 Train:  0.9204815042614884
Micro F1 Dev:  0.9092507914175166
Micro F1 Test:  0.921644413211525
Weighted Recall Train:  0.9204815042614884
Weighted Recall Dev:  0.9092507914175167
Weighted Recall Test:  0.9216444132115249
Macro Recall Train:  0.3881267423033988
Macro Recall Dev:  0.3858133171524741
Macro Recall Test:  0.40224810386939197
Micro Recall Train:  0.9204815042614884
Micro Recall Dev:  0.9092507914175167
Micro Recall Test:  0.9216444132115249
Confusion Matrix Train: 
[[  338  1624     0]
 [  164 20614     0]
 [    0    22     0]]
Confusion Matrix Dev: 
[[  46  226    0]
 [  30 2539    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  54  196    0]
 

### Sentence Transformer Better No PCA

In [62]:
train, dev, test = load_sent_trans_better_no_pca()

In [63]:
grid_results = gridsearch.fit(train, train_labels)
best_params = grid_results.best_params_
gaussian_nb = grid_results.best_estimator_

In [64]:
print(best_params)

{'var_smoothing': 1e-09}


In [66]:

gaussian_nb = gaussian_nb.fit(train, train_labels)
save_model(gaussian_nb, "gaussian_nb_sent_trans_best_no_pca.joblib")

In [67]:
train_preds = gaussian_nb.predict(train)
dev_preds =gaussian_nb.predict(dev)
test_preds = gaussian_nb.predict(test)

In [68]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.8271241542922415
Accuracy Dev:  0.8244811818501583
Accuracy Test:  0.8292340126493324
Weighted F1 Train:  0.8597424051409676
Weighted F1 Dev:  0.8557072631314984
Weighted F1 Test:  0.8609914710911621
Macro F1 Train:  0.48678019210796036
Macro F1 Dev:  0.45967762821155755
Macro F1 Test:  0.45720102585245287
Micro F1 Train:  0.8271241542922416
Micro F1 Dev:  0.8244811818501583
Micro F1 Test:  0.8292340126493324
Weighted Recall Train:  0.8271241542922415
Weighted Recall Dev:  0.8244811818501583
Weighted Recall Test:  0.8292340126493324
Macro Recall Train:  0.8266941996552797
Macro Recall Dev:  0.540818507239408
Macro Recall Test:  0.5431325363157219
Micro Recall Train:  0.8271241542922415
Micro Recall Dev:  0.8244811818501583
Micro Recall Test:  0.8292340126493324
Confusion Matrix Train: 
[[ 1541   393    28]
 [ 3211 17267   300]
 [    1     2    19]]
Confusion Matrix Dev: 
[[ 216   53    3]
 [ 405 2128   36]
 [   1    1    0]]
Confusion Matrix Test: 
[[ 199   48    3]


### Sentence Transformer Better PCA

In [69]:
train, dev, test = load_sent_trans_better_pca()

In [70]:
grid_results = gridsearch.fit(train, train_labels)
best_params = grid_results.best_params_
gaussian_nb = grid_results.best_estimator_

In [71]:
print(best_params)

{'var_smoothing': 0.533669923120631}


In [72]:

gaussian_nb = gaussian_nb.fit(train, train_labels)
save_model(gaussian_nb, "gaussian_nb_sent_trans_best_pca.joblib")

In [73]:
train_preds = gaussian_nb.predict(train)
dev_preds =gaussian_nb.predict(dev)
test_preds = gaussian_nb.predict(test)

In [74]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9236886038133731
Accuracy Dev:  0.9113612381287373
Accuracy Test:  0.9251581166549543
Weighted F1 Train:  0.9020793698020264
Weighted F1 Dev:  0.8875093483404506
Weighted F1 Test:  0.9068331479453273
Macro F1 Train:  0.4207356744122493
Macro F1 Dev:  0.41008265166822966
Macro F1 Test:  0.44129671410880594
Micro F1 Train:  0.9236886038133731
Micro F1 Dev:  0.9113612381287373
Micro F1 Test:  0.9251581166549543
Weighted Recall Train:  0.9236886038133731
Weighted Recall Dev:  0.9113612381287373
Weighted Recall Test:  0.9251581166549543
Macro Recall Train:  0.3945288226814824
Macro Recall Dev:  0.38878330623802654
Macro Recall Test:  0.4107623087800489
Micro Recall Train:  0.9236886038133731
Micro Recall Dev:  0.9113612381287373
Micro Recall Test:  0.9251581166549543
Confusion Matrix Train: 
[[  372  1590     0]
 [  125 20653     0]
 [    0    22     0]]
Confusion Matrix Dev: 
[[  48  224    0]
 [  26 2543    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  60  190    0]

### Augmented Data Sentence Transformer Better

In [10]:
train_aug, dev, test = load_sent_trans_augmented_no_pca()

In [11]:
grid_results = gridsearch.fit(train_aug, train_augmented_labels)
best_params = grid_results.best_params_
gaussian_nb = grid_results.best_estimator_

In [12]:
print(best_params)

{'var_smoothing': 0.0006579332246575676}


In [13]:
gaussian_nb = gaussian_nb.fit(train_aug, train_augmented_labels)
save_model(gaussian_nb, "gaussian_nb_sent_trans_augmented_no_pca.joblib")

In [14]:
train_preds = gaussian_nb.predict(train_aug)
dev_preds = gaussian_nb.predict(dev)
test_preds = gaussian_nb.predict(test)

In [15]:
computeAllScores(train_preds, dev_preds, test_preds, aug=True)

Accuracy Train:  0.7885894955405597
Accuracy Dev:  0.8121702427013718
Accuracy Test:  0.7969079409697821
Weighted F1 Train:  0.7943162086909704
Weighted F1 Dev:  0.8452544573003199
Weighted F1 Test:  0.8351981229701504
Macro F1 Train:  0.5467917411549181
Macro F1 Dev:  0.4436665799677379
Macro F1 Test:  0.4214869589727905
Micro F1 Train:  0.7885894955405597
Micro F1 Dev:  0.8121702427013717
Micro F1 Test:  0.7969079409697821
Weighted Recall Train:  0.7885894955405597
Weighted Recall Dev:  0.8121702427013718
Weighted Recall Test:  0.7969079409697821
Macro Recall Train:  0.7987953708692211
Macro Recall Dev:  0.5143624207176059
Macro Recall Test:  0.4939575780948708
Micro Recall Train:  0.7885894955405597
Micro Recall Dev:  0.8121702427013718
Micro Recall Test:  0.7969079409697821
Confusion Matrix Train: 
[[16430  4786   366]
 [ 3502 16974   302]
 [    1     3    18]]
Confusion Matrix Dev: 
[[ 196   72    4]
 [ 418 2113   38]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 168   79    3]
 [

### Only 2 Class Augmented Data Sentence Transformer Better

In [16]:
train, dev, test, train_labels, dev_labels, test_labels = load_only_2_class("sent_trans_augmented_no_pca", True)

In [17]:
train_labels = [label_replacement[label] for label in train_labels]
dev_labels = [label_replacement[label] for label in dev_labels]
test_labels = [label_replacement[label] for label in test_labels]

In [18]:
grid_results = gridsearch.fit(train, train_labels)
best_params = grid_results.best_params_
gaussian_nb = grid_results.best_estimator_

In [19]:
print(best_params)

{'var_smoothing': 0.0006579332246575676}


In [20]:
gaussian_nb = gaussian_nb.fit(train_aug, train_labels)
save_model(gaussian_nb, "gaussian_nb_sent_trans_augmented_no_pca_2_class.joblib")

In [21]:
train_preds = gaussian_nb.predict(train)
dev_preds = gaussian_nb.predict(dev)
test_preds = gaussian_nb.predict(test)

In [22]:
computeAllScores(train_preds, dev_preds, test_preds, aug=True)

Accuracy Train:  0.7885894955405597
Accuracy Dev:  0.8121702427013718
Accuracy Test:  0.7969079409697821
Weighted F1 Train:  0.7943162086909704
Weighted F1 Dev:  0.8452544573003199
Weighted F1 Test:  0.8351981229701504
Macro F1 Train:  0.5467917411549181
Macro F1 Dev:  0.4436665799677379
Macro F1 Test:  0.4214869589727905
Micro F1 Train:  0.7885894955405597
Micro F1 Dev:  0.8121702427013717
Micro F1 Test:  0.7969079409697821
Weighted Recall Train:  0.7885894955405597
Weighted Recall Dev:  0.8121702427013718
Weighted Recall Test:  0.7969079409697821
Macro Recall Train:  0.7987953708692211
Macro Recall Dev:  0.5143624207176059
Macro Recall Test:  0.4939575780948708
Micro Recall Train:  0.7885894955405597
Micro Recall Dev:  0.8121702427013718
Micro Recall Test:  0.7969079409697821
Confusion Matrix Train: 
[[16430  4786   366]
 [ 3502 16974   302]
 [    1     3    18]]
Confusion Matrix Dev: 
[[ 196   72    4]
 [ 418 2113   38]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 168   79    3]
 [