In [55]:
from embeddings_loader import *
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import roc_auc_score

In [56]:
train_labels, dev_labels, test_labels = load_labels()

In [57]:
def computeAllScores(y_pred_train, y_pred_dev, y_pred_test):
    print("Accuracy Train: ", accuracy_score(train_labels, y_pred_train))
    print("Accuracy Dev: ", accuracy_score(dev_labels, y_pred_dev))
    print("Accuracy Test: ", accuracy_score(test_labels, y_pred_test))
    print("F1 Train: ", f1_score(train_labels, y_pred_train, average='macro'))
    print("F1 Dev: ", f1_score(dev_labels, y_pred_dev, average='macro'))
    print("F1 Test: ", f1_score(test_labels, y_pred_test, average='macro'))
    print("Precision Train: ", precision_score(train_labels, y_pred_train, average='macro'))
    print("Precision Dev: ", precision_score(dev_labels, y_pred_dev, average='macro'))
    print("Precision Test: ", precision_score(test_labels, y_pred_test, average='macro'))
    print("Recall Train: ", recall_score(train_labels, y_pred_train, average='macro'))
    print("Recall Dev: ", recall_score(dev_labels, y_pred_dev, average='macro'))
    print("Recall Test: ", recall_score(test_labels, y_pred_test, average='macro'))
    # Confusion Matrix
    print("Confusion Matrix Train: ")
    print(confusion_matrix(train_labels, y_pred_train))
    print("Confusion Matrix Dev: ")
    print(confusion_matrix(dev_labels, y_pred_dev))
    print("Confusion Matrix Test: ")
    print(confusion_matrix(test_labels, y_pred_test))

In [58]:
label_replacement = {
    'Hope_speech': 0,
    'Non_hope_speech': 1,
    'not-English': 2,
}

In [59]:
# Replace labels with numbers
train_labels = [label_replacement[label] for label in train_labels]
dev_labels = [label_replacement[label] for label in dev_labels]
test_labels = [label_replacement[label] for label in test_labels]

In [60]:
gaussian_nb = GaussianNB()
gridsearch = GridSearchCV(gaussian_nb, param_grid = {'var_smoothing': np.logspace(0,-9, num=100)}, scoring = "f1_micro")

### Glove Twitter 25

In [61]:
gt25_train, gt25_dev, gt25_test = load_glove_twitter_25()

In [62]:
# Set all NaN values to 0
gt25_train = np.nan_to_num(gt25_train)
gt25_dev = np.nan_to_num(gt25_dev)
gt25_test = np.nan_to_num(gt25_test)

In [63]:
grid_results = gridsearch.fit(gt25_train, train_labels)
best_params = grid_results.best_params_
gaussian_nb = grid_results.best_estimator_

In [64]:

gaussian_nb.fit(gt25_train, train_labels)

GaussianNB(var_smoothing=1.0)

In [65]:
train_preds = gaussian_nb.predict(gt25_train)
dev_preds = gaussian_nb.predict(gt25_dev)
test_preds = gaussian_nb.predict(gt25_test)

In [66]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9121342588524735
Accuracy Dev:  0.9032711924023918
Accuracy Test:  0.910049191848208
F1 Train:  0.38745703809246573
F1 Dev:  0.3164510166358595
F1 Test:  0.31763551631101306
Precision Train:  0.3684217055522474
Precision Dev:  0.3013023583245336
Precision Test:  0.3036698323367335
Recall Train:  0.40875401429833996
Recall Dev:  0.33320358115998444
Recall Test:  0.33294767965034067
Confusion Matrix Train: 
[[    0  1962     0]
 [    0 20757    21]
 [    0    17     5]]
Confusion Matrix Dev: 
[[   0  271    1]
 [   0 2568    1]
 [   0    2    0]]
Confusion Matrix Test: 
[[   0  250    0]
 [   0 2590    3]
 [   0    3    0]]


c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### FastText 300

In [67]:
ft300_train, ft300_dev, ft300_test = load_fasttext_300()

In [68]:
# Set all NaN values to 0
ft300_train = np.nan_to_num(ft300_train)
ft300_dev = np.nan_to_num(ft300_dev)
ft300_test = np.nan_to_num(ft300_test)

In [69]:
grid_results = gridsearch.fit(ft300_train, train_labels)
best_params = grid_results.best_params_
gaussian_nb = grid_results.best_estimator_

In [70]:
gaussian_nb = gaussian_nb.fit(ft300_train, train_labels)

In [71]:
train_preds = gaussian_nb.predict(ft300_train)
dev_preds = gaussian_nb.predict(ft300_dev)
test_preds = gaussian_nb.predict(ft300_test)

In [73]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9130568491345225
Accuracy Dev:  0.9036229335209286
Accuracy Test:  0.9111033028812369
F1 Train:  0.37475414135020296
F1 Dev:  0.31645725548164577
F1 Test:  0.31782803211374644
Precision Train:  0.9710125822091372
Precision Dev:  0.3012076445069762
Precision Test:  0.3037011009604123
Recall Train:  0.36414604763228614
Recall Dev:  0.3333333333333333
Recall Test:  0.3333333333333333
Confusion Matrix Train: 
[[    3  1959     0]
 [    0 20778     0]
 [    0    20     2]]
Confusion Matrix Dev: 
[[   0  272    0]
 [   0 2569    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[   0  250    0]
 [   0 2593    0]
 [   0    3    0]]


c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Word2Vec 300

In [74]:
w2v300_train, w2v300_dev, w2v300_test = load_word2vec_300()

In [75]:
# Set all NaN values to 0
w2v300_train = np.nan_to_num(w2v300_train)
w2v300_dev = np.nan_to_num(w2v300_dev)
w2v300_test = np.nan_to_num(w2v300_test)

In [76]:
grid_results = gridsearch.fit(w2v300_train, train_labels)
best_params = grid_results.best_params_
gaussian_nb = grid_results.best_estimator_

In [77]:
gaussian_nb = gaussian_nb.fit(w2v300_train, train_labels)

In [78]:
train_preds = gaussian_nb.predict(w2v300_train)
dev_preds = gaussian_nb.predict(w2v300_dev)
test_preds = gaussian_nb.predict(w2v300_test)

In [79]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.4608558123187769
Accuracy Dev:  0.46289131199437217
Accuracy Test:  0.4631061138439916
F1 Train:  0.2770942452599117
F1 Dev:  0.28169345948247493
F1 Test:  0.28309328315380894
Precision Train:  0.3665651821985461
Precision Dev:  0.36579844878440543
Precision Test:  0.3734157336222417
Recall Train:  0.5272260293202522
Recall Dev:  0.5652042833482166
Recall Test:  0.5358268843467455
Confusion Matrix Train: 
[[ 1546   347    69]
 [10010  8936  1832]
 [    6     8     8]]
Confusion Matrix Dev: 
[[ 208   60    4]
 [1221 1107  241]
 [   0    1    1]]
Confusion Matrix Test: 
[[ 212   33    5]
 [1237 1105  251]
 [   1    1    1]]


### TF-IDF PCA (1000 Dims)

In [80]:
tfidf_pca_train, tfidf_pca_dev, tfidf_pca_test = load_tfidf_pca()

In [81]:
grid_results = gridsearch.fit(tfidf_pca_train, train_labels)
best_params = grid_results.best_params_
gaussian_nb = grid_results.best_estimator_

In [82]:

gaussian_nb.fit(tfidf_pca_train, train_labels)

GaussianNB(var_smoothing=1.0)

In [83]:
train_preds = gaussian_nb.predict(tfidf_pca_train)
dev_preds = gaussian_nb.predict(tfidf_pca_dev)
test_preds = gaussian_nb.predict(tfidf_pca_test)

In [84]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9001405851858361
Accuracy Dev:  0.8906085121350686
Accuracy Test:  0.8952916373858046
F1 Train:  0.36174683265238466
F1 Dev:  0.3304907643065604
F1 Test:  0.32997507762137473
Precision Train:  0.4345085259252431
Precision Dev:  0.4574446038578033
Precision Test:  0.42167767717061705
Recall Train:  0.6199634469350762
Recall Dev:  0.33620266907853064
Recall Test:  0.3347772207224579
Confusion Matrix Train: 
[[   24  1929     9]
 [   49 20446   283]
 [    0     3    19]]
Confusion Matrix Dev: 
[[   7  261    4]
 [   8 2525   36]
 [   0    2    0]]
Confusion Matrix Test: 
[[   6  242    2]
 [  11 2542   40]
 [   0    3    0]]


### Seentence Transformer Faster No PCA

In [85]:
train, dev, test = load_sent_trans_fast_no_pca()

In [86]:
grid_results = gridsearch.fit(train, train_labels)
best_params = grid_results.best_params_
gaussian_nb = grid_results.best_estimator_

In [87]:

gaussian_nb.fit(train, train_labels)

GaussianNB(var_smoothing=6.579332246575683e-05)

In [88]:
train_preds = gaussian_nb.predict(train)
dev_preds = gaussian_nb.predict(dev)
test_preds = gaussian_nb.predict(test)

In [89]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.8321325015376505
Accuracy Dev:  0.8315160042208934
Accuracy Test:  0.8271257905832747
F1 Train:  0.5451696314647192
F1 Dev:  0.45129085966270077
F1 Test:  0.48578249509654664
Precision Train:  0.4885531406609828
Precision Dev:  0.43188984136368114
Precision Test:  0.4518190363510744
Recall Train:  0.7884055804231608
Recall Dev:  0.5225945282745251
Recall Test:  0.6412959677764922
Confusion Matrix Train: 
[[ 1477   480     5]
 [ 3259 17447    72]
 [    1     4    17]]
Confusion Matrix Dev: 
[[ 197   75    0]
 [ 400 2167    2]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 189   60    1]
 [ 417 2164   12]
 [   0    2    1]]


### Sentence Transformer Faster PCA

In [90]:
train, dev, test = load_sent_trans_fast_pca()

In [91]:
grid_results = gridsearch.fit(train, train_labels)
best_params = grid_results.best_params_
gaussian_nb = grid_results.best_estimator_

In [92]:

gaussian_nb.fit(train, train_labels)

GaussianNB(var_smoothing=0.533669923120631)

In [93]:
train_preds = gaussian_nb.predict(train)
dev_preds =gaussian_nb.predict(dev)
test_preds = gaussian_nb.predict(test)

In [94]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9204815042614884
Accuracy Dev:  0.9092507914175167
Accuracy Test:  0.9216444132115249
F1 Train:  0.41076493057881597
F1 Dev:  0.4053389971680826
F1 Test:  0.4292238585508407
Precision Train:  0.533120826069785
Precision Dev:  0.5076211490055098
Precision Test:  0.5401382095746258
Recall Train:  0.3881267423033988
Recall Dev:  0.3858133171524741
Recall Test:  0.40224810386939197
Confusion Matrix Train: 
[[  338  1624     0]
 [  164 20614     0]
 [    0    22     0]]
Confusion Matrix Dev: 
[[  46  226    0]
 [  30 2539    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  54  196    0]
 [  24 2569    0]
 [   0    3    0]]


c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Sentence Transformer Better No PCA

In [95]:
train, dev, test = load_sent_trans_better_no_pca()

In [96]:
grid_results = gridsearch.fit(train, train_labels)
best_params = grid_results.best_params_
gaussian_nb = grid_results.best_estimator_

In [97]:

gaussian_nb.fit(train, train_labels)

GaussianNB()

In [98]:
train_preds = gaussian_nb.predict(train)
dev_preds =gaussian_nb.predict(dev)
test_preds = gaussian_nb.predict(test)

In [99]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.8271241542922415
Accuracy Dev:  0.8244811818501583
Accuracy Test:  0.8292340126493324
F1 Train:  0.48678019210796036
F1 Dev:  0.45967762821155755
F1 Test:  0.45720102585245287
Precision Train:  0.4522023098455617
Precision Dev:  0.4408396477856928
Precision Test:  0.43750857655163156
Recall Train:  0.8266941996552797
Recall Dev:  0.540818507239408
Recall Test:  0.5431325363157219
Confusion Matrix Train: 
[[ 1541   393    28]
 [ 3211 17267   300]
 [    1     2    19]]
Confusion Matrix Dev: 
[[ 216   53    3]
 [ 405 2128   36]
 [   1    1    0]]
Confusion Matrix Test: 
[[ 199   48    3]
 [ 394 2161   38]
 [   0    3    0]]


### Sentence Transformer Better PCA

In [100]:
train, dev, test = load_sent_trans_better_pca()

In [101]:
grid_results = gridsearch.fit(train, train_labels)
best_params = grid_results.best_params_
gaussian_nb = grid_results.best_estimator_

In [102]:

gaussian_nb.fit(train, train_labels)

GaussianNB(var_smoothing=0.533669923120631)

In [103]:
train_preds = gaussian_nb.predict(train)
dev_preds =gaussian_nb.predict(dev)
test_preds = gaussian_nb.predict(test)

In [104]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9236886038133731
Accuracy Dev:  0.9113612381287373
Accuracy Test:  0.9251581166549543
F1 Train:  0.4207356744122493
F1 Dev:  0.41008265166822966
F1 Test:  0.44129671410880594
Precision Train:  0.5586967722948214
Precision Dev:  0.5223435786816069
Precision Test:  0.5600747167992287
Recall Train:  0.3945288226814824
Recall Dev:  0.38878330623802654
Recall Test:  0.4107623087800489
Confusion Matrix Train: 
[[  372  1590     0]
 [  125 20653     0]
 [    0    22     0]]
Confusion Matrix Dev: 
[[  48  224    0]
 [  26 2543    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  60  190    0]
 [  20 2573    0]
 [   0    3    0]]


c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\diksh\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
