In [1]:
from embeddings_loader import *
from sklearn.neighbors import NearestCentroid
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import roc_auc_score
from utils import *


In [2]:
train_labels, dev_labels, test_labels = load_labels()

In [3]:
label_replacement = {
    'Hope_speech': 0,
    'Non_hope_speech': 1,
    'not-English': 2,
}

In [4]:
# Replace labels with numbers
train_labels = [label_replacement[label] for label in train_labels]
dev_labels = [label_replacement[label] for label in dev_labels]
test_labels = [label_replacement[label] for label in test_labels]

### Glove Twitter 25

In [5]:
gt25_train, gt25_dev, gt25_test = load_glove_twitter_25()

In [6]:
# Set all NaN values to 0
gt25_train = np.nan_to_num(gt25_train)
gt25_dev = np.nan_to_num(gt25_dev)
gt25_test = np.nan_to_num(gt25_test)

In [7]:
nearest_centroid = NearestCentroid().fit(gt25_train, train_labels)
save_model(nearest_centroid, 'nearest_centroid_gt25.joblib')

In [8]:
train_preds = nearest_centroid.predict(gt25_train)
dev_preds = nearest_centroid.predict(gt25_dev)
test_preds = nearest_centroid.predict(gt25_test)

In [9]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.47970301379492136
Accuracy Dev:  0.48997537812170244
Accuracy Test:  0.4764581869290232
Weighted F1 Train:  0.583247066494068
Weighted F1 Dev:  0.5876366518381572
Weighted F1 Test:  0.5783478786382882
Macro F1 Train:  0.28734117594971553
Macro F1 Dev:  0.2980994632664367
Macro F1 Test:  0.28793564454140674
Micro F1 Train:  0.47970301379492136
Micro F1 Dev:  0.48997537812170244
Micro F1 Test:  0.4764581869290232
Weighted Recall Train:  0.47970301379492136
Weighted Recall Dev:  0.48997537812170244
Weighted Recall Test:  0.4764581869290232
Macro Recall Train:  0.5636679644990306
Macro Recall Dev:  0.7329662110075638
Macro Recall Test:  0.5130018425675965
Micro Recall Train:  0.47970301379492136
Micro Recall Dev:  0.48997537812170244
Micro Recall Test:  0.4764581869290232
Confusion Matrix Train: 
[[1443  455   64]
 [8757 9465 2556]
 [   5    6   11]]
Confusion Matrix Dev: 
[[ 200   64    8]
 [1074 1191  304]
 [   0    0    2]]
Confusion Matrix Test: 
[[ 189   57    4]
 [

### FastText 300 

In [10]:
ft300_train, ft300_dev, ft300_test = load_fasttext_300()

In [11]:
# Set all NaN values to 0
ft300_train = np.nan_to_num(ft300_train)
ft300_dev = np.nan_to_num(ft300_dev)
ft300_test = np.nan_to_num(ft300_test)

In [12]:
nearest_centroid = NearestCentroid().fit(ft300_train, train_labels)
save_model(nearest_centroid, 'nearest_centroid_ft300.joblib')

In [13]:
train_preds = nearest_centroid.predict(ft300_train)
dev_preds = nearest_centroid.predict(ft300_dev)
test_preds = nearest_centroid.predict(ft300_test)

In [14]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.6240664265003075
Accuracy Dev:  0.6215265564544495
Accuracy Test:  0.6289529163738581
Weighted F1 Train:  0.7074486902121332
Weighted F1 Dev:  0.7012000167438953
Weighted F1 Test:  0.7107550586740382
Macro F1 Train:  0.3472252050771638
Macro F1 Dev:  0.35197322985265717
Macro F1 Test:  0.35126624153239455
Micro F1 Train:  0.6240664265003075
Micro F1 Dev:  0.6215265564544495
Micro F1 Test:  0.6289529163738581
Weighted Recall Train:  0.6240664265003075
Weighted Recall Dev:  0.6215265564544494
Weighted Recall Test:  0.6289529163738581
Macro Recall Train:  0.5981714645664077
Macro Recall Dev:  0.6160523473694655
Macro Recall Test:  0.5663835111625316
Micro Recall Train:  0.6240664265003075
Micro Recall Dev:  0.6215265564544495
Micro Recall Test:  0.6289529163738581
Confusion Matrix Train: 
[[ 1423   524    15]
 [ 7154 12772   852]
 [    4     8    10]]
Confusion Matrix Dev: 
[[ 201   68    3]
 [ 895 1565  109]
 [   1    0    1]]
Confusion Matrix Test: 
[[ 187   61    2]


### Word2Vec 300

In [15]:
w2v300_train, w2v300_dev, w2v300_test = load_word2vec_300()

In [16]:
# Set all NaN values to 0
w2v300_train = np.nan_to_num(w2v300_train)
w2v300_dev = np.nan_to_num(w2v300_dev)
w2v300_test = np.nan_to_num(w2v300_test)

In [17]:
nearest_centroid = NearestCentroid().fit(w2v300_train, train_labels)
save_model(nearest_centroid, 'nearest_centroid_w2v300.joblib')

In [18]:
train_preds = nearest_centroid.predict(w2v300_train)
dev_preds = nearest_centroid.predict(w2v300_dev)
test_preds = nearest_centroid.predict(w2v300_test)

In [19]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.6600913803707934
Accuracy Dev:  0.6630320084417869
Accuracy Test:  0.6654954321855235
Weighted F1 Train:  0.7359802599574455
Weighted F1 Dev:  0.7340949852415108
Weighted F1 Test:  0.7393737823335733
Macro F1 Train:  0.36425988909189205
Macro F1 Dev:  0.3729726712182186
Macro F1 Test:  0.37511734210431696
Micro F1 Train:  0.6600913803707934
Micro F1 Dev:  0.6630320084417869
Micro F1 Test:  0.6654954321855235
Weighted Recall Train:  0.6600913803707934
Weighted Recall Dev:  0.6630320084417869
Weighted Recall Test:  0.6654954321855235
Macro Recall Train:  0.5980371562170766
Macro Recall Dev:  0.6335545798700952
Macro Recall Test:  0.6026436988473239
Micro Recall Train:  0.6600913803707934
Micro Recall Dev:  0.6630320084417869
Micro Recall Test:  0.6654954321855235
Confusion Matrix Train: 
[[ 1435   511    16]
 [ 6446 13581   751]
 [    2    11     9]]
Confusion Matrix Dev: 
[[ 203   68    1]
 [ 791 1681   97]
 [   0    1    1]]
Confusion Matrix Test: 
[[ 206   44    0]


### TF-IDF PCA (1000 Dims)

In [20]:
tfidf_pca_train, tfidf_pca_dev, tfidf_pca_test = load_tfidf_pca()

In [21]:
nearest_centroid = NearestCentroid().fit(tfidf_pca_train, train_labels)
save_model(nearest_centroid, 'nearest_centroid_tfidf_pca.joblib')

In [22]:
train_preds = nearest_centroid.predict(tfidf_pca_train)
dev_preds = nearest_centroid.predict(tfidf_pca_dev)
test_preds = nearest_centroid.predict(tfidf_pca_test)

In [23]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.7730867234865126
Accuracy Dev:  0.7583538515652479
Accuracy Test:  0.7614195361911454
Weighted F1 Train:  0.8204982041442979
Weighted F1 Dev:  0.807263960044715
Weighted F1 Test:  0.8119314906718668
Macro F1 Train:  0.42529839422773147
Macro F1 Dev:  0.4121132839539076
Macro F1 Test:  0.4092289643846722
Micro F1 Train:  0.7730867234865126
Micro F1 Dev:  0.758353851565248
Micro F1 Test:  0.7614195361911453
Weighted Recall Train:  0.7730867234865126
Weighted Recall Dev:  0.7583538515652479
Weighted Recall Test:  0.7614195361911454
Macro Recall Train:  0.7393047956501185
Macro Recall Dev:  0.4846486959906578
Macro Recall Test:  0.48699781462912967
Micro Recall Train:  0.7730867234865126
Micro Recall Dev:  0.7583538515652479
Micro Recall Test:  0.7614195361911454
Confusion Matrix Train: 
[[ 1298   635    29]
 [ 3737 16282   759]
 [    0     5    17]]
Confusion Matrix Dev: 
[[ 187   78    7]
 [ 516 1969   84]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 173   73    4]
 [

### Sentence Transformer Faster No PCA

In [24]:
train, dev, test = load_sent_trans_fast_no_pca()

In [25]:
nearest_centroid = NearestCentroid().fit(train, train_labels)
save_model(nearest_centroid, 'nearest_centroid_sent_trans_fast_no_pca.joblib')

In [26]:
train_preds = nearest_centroid.predict(train)
dev_preds = nearest_centroid.predict(dev)
test_preds = nearest_centroid.predict(test)

In [27]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.7556014409981548
Accuracy Dev:  0.7530777347871966
Accuracy Test:  0.7484188334504568
Weighted F1 Train:  0.812075214434259
Weighted F1 Dev:  0.807743227588967
Weighted F1 Test:  0.8057508702566876
Macro F1 Train:  0.43042788904055795
Macro F1 Dev:  0.42970491901065877
Macro F1 Test:  0.4228869061367528
Micro F1 Train:  0.7556014409981548
Micro F1 Dev:  0.7530777347871966
Micro F1 Test:  0.7484188334504568
Weighted Recall Train:  0.7556014409981548
Weighted Recall Dev:  0.7530777347871966
Weighted Recall Test:  0.7484188334504568
Macro Recall Train:  0.7840566908790092
Macro Recall Dev:  0.6667711362474145
Macro Recall Test:  0.623343531730728
Micro Recall Train:  0.7556014409981548
Micro Recall Dev:  0.7530777347871966
Micro Recall Test:  0.7484188334504568
Confusion Matrix Train: 
[[ 1532   367    63]
 [ 3918 15649  1211]
 [    1     3    18]]
Confusion Matrix Dev: 
[[ 203   59   10]
 [ 471 1937  161]
 [   0    1    1]]
Confusion Matrix Test: 
[[ 198   46    6]
 [ 

### Sentence Transformer Faster PCA

In [28]:
train, dev, test = load_sent_trans_fast_pca()

In [29]:
nearest_centroid = NearestCentroid().fit(train, train_labels)
save_model(nearest_centroid, 'nearest_centroid_sent_trans_fast_pca')

In [30]:
train_preds = nearest_centroid.predict(train)
dev_preds = nearest_centroid.predict(dev)
test_preds = nearest_centroid.predict(test)

In [31]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.7510763553290573
Accuracy Dev:  0.748153359127682
Accuracy Test:  0.7452565003513704
Weighted F1 Train:  0.809300439167791
Weighted F1 Dev:  0.8046939212673693
Weighted F1 Test:  0.8037866815469658
Macro F1 Train:  0.42866522750059516
Macro F1 Dev:  0.42754941404575364
Macro F1 Test:  0.4222541821900796
Micro F1 Train:  0.7510763553290573
Micro F1 Dev:  0.748153359127682
Micro F1 Test:  0.7452565003513704
Weighted Recall Train:  0.7510763553290573
Weighted Recall Dev:  0.748153359127682
Weighted Recall Test:  0.7452565003513704
Macro Recall Train:  0.781942745966091
Macro Recall Dev:  0.6638588677978003
Macro Recall Test:  0.62218657068175
Micro Recall Train:  0.7510763553290573
Micro Recall Dev:  0.748153359127682
Micro Recall Test:  0.7452565003513704
Confusion Matrix Train: 
[[ 1529   363    70]
 [ 3906 15549  1323]
 [    1     3    18]]
Confusion Matrix Dev: 
[[ 202   58   12]
 [ 473 1924  172]
 [   0    1    1]]
Confusion Matrix Test: 
[[ 198   46    6]
 [ 512 1

### Sentence Transformer Better No PCA

In [32]:
train, dev, test = load_sent_trans_better_no_pca()

In [33]:
nearest_centroid = NearestCentroid().fit(train, train_labels)
save_model(nearest_centroid, 'nearest_centroid_sent_trans_better_no_pca')

In [34]:
train_preds = nearest_centroid.predict(train)
dev_preds = nearest_centroid.predict(dev)
test_preds = nearest_centroid.predict(test)

In [35]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.7425094455671734
Accuracy Dev:  0.7463946535349982
Accuracy Test:  0.7371749824314828
Weighted F1 Train:  0.8064137240141829
Weighted F1 Dev:  0.8063800598601126
Weighted F1 Test:  0.8021729271164183
Macro F1 Train:  0.43146778920882695
Macro F1 Dev:  0.4350685830431395
Macro F1 Test:  0.43059630707966057
Micro F1 Train:  0.7425094455671735
Micro F1 Dev:  0.7463946535349982
Micro F1 Test:  0.7371749824314829
Weighted Recall Train:  0.7425094455671734
Weighted Recall Dev:  0.7463946535349982
Weighted Recall Test:  0.7371749824314828
Macro Recall Train:  0.7491589003178095
Macro Recall Dev:  0.5098220487104924
Macro Recall Test:  0.621639456656811
Micro Recall Train:  0.7425094455671734
Micro Recall Dev:  0.7463946535349982
Micro Recall Test:  0.7371749824314828
Confusion Matrix Train: 
[[ 1533   324   105]
 [ 3526 15352  1900]
 [    2     4    16]]
Confusion Matrix Dev: 
[[ 214   45   13]
 [ 441 1908  220]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 200   39   11]
 

### Sentence Transformer Better PCA

In [36]:
train, dev, test = load_sent_trans_better_pca()

In [37]:
nearest_centroid = NearestCentroid().fit(train, train_labels)
save_model(nearest_centroid, 'nearest_centroid_sent_trans_better_pca')

In [38]:
train_preds = nearest_centroid.predict(train)
dev_preds = nearest_centroid.predict(dev)
test_preds = nearest_centroid.predict(test)

In [39]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.7367981723925842
Accuracy Dev:  0.7390080900457263
Accuracy Test:  0.7340126493323963
Weighted F1 Train:  0.8027191846367847
Weighted F1 Dev:  0.80162821539565
Weighted F1 Test:  0.8001902054828377
Macro F1 Train:  0.42968197136857356
Macro F1 Dev:  0.43296881250700076
Macro F1 Test:  0.4294071270047755
Micro F1 Train:  0.7367981723925843
Micro F1 Dev:  0.7390080900457263
Micro F1 Test:  0.7340126493323963
Weighted Recall Train:  0.7367981723925842
Weighted Recall Dev:  0.7390080900457263
Weighted Recall Test:  0.7340126493323963
Macro Recall Train:  0.7467656570134403
Macro Recall Dev:  0.5060015150474358
Macro Recall Test:  0.619277713502164
Micro Recall Train:  0.7367981723925842
Micro Recall Dev:  0.7390080900457263
Micro Recall Test:  0.7340126493323963
Confusion Matrix Train: 
[[ 1531   321   110]
 [ 3525 15224  2029]
 [    2     4    16]]
Confusion Matrix Dev: 
[[ 213   45   14]
 [ 440 1888  241]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 199   39   12]
 [ 