In [1]:
from embeddings_loader import *
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import roc_auc_score


In [2]:
train_labels, dev_labels, test_labels = load_labels()

In [3]:
def computeAllScores(y_pred_train, y_pred_dev, y_pred_test):
    print("Accuracy Train: ", accuracy_score(train_labels, y_pred_train))
    print("Accuracy Dev: ", accuracy_score(dev_labels, y_pred_dev))
    print("Accuracy Test: ", accuracy_score(test_labels, y_pred_test))
    print("F1 Train: ", f1_score(train_labels, y_pred_train, average='macro'))
    print("F1 Dev: ", f1_score(dev_labels, y_pred_dev, average='macro'))
    print("F1 Test: ", f1_score(test_labels, y_pred_test, average='macro'))
    print("Precision Train: ", precision_score(train_labels, y_pred_train, average='macro'))
    print("Precision Dev: ", precision_score(dev_labels, y_pred_dev, average='macro'))
    print("Precision Test: ", precision_score(test_labels, y_pred_test, average='macro'))
    print("Recall Train: ", recall_score(train_labels, y_pred_train, average='macro'))
    print("Recall Dev: ", recall_score(dev_labels, y_pred_dev, average='macro'))
    print("Recall Test: ", recall_score(test_labels, y_pred_test, average='macro'))
    # Confusion Matrix
    print("Confusion Matrix Train: ")
    print(confusion_matrix(train_labels, y_pred_train))
    print("Confusion Matrix Dev: ")
    print(confusion_matrix(dev_labels, y_pred_dev))
    print("Confusion Matrix Test: ")
    print(confusion_matrix(test_labels, y_pred_test))

In [4]:
label_replacement = {
    'Hope_speech': 0,
    'Non_hope_speech': 1,
    'not-English': 2,
}

In [5]:
# Replace labels with numbers
train_labels = [label_replacement[label] for label in train_labels]
dev_labels = [label_replacement[label] for label in dev_labels]
test_labels = [label_replacement[label] for label in test_labels]

### Glove Twitter 25

In [6]:
gt25_train, gt25_dev, gt25_test = load_glove_twitter_25()

In [7]:
# Set all NaN values to 0
gt25_train = np.nan_to_num(gt25_train)
gt25_dev = np.nan_to_num(gt25_dev)
gt25_test = np.nan_to_num(gt25_test)

In [8]:
quadratic_discriminant_analysis = QuadraticDiscriminantAnalysis().fit(gt25_train, train_labels)

C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\discriminant_analysis.py:887: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


In [9]:
train_preds = quadratic_discriminant_analysis.predict(gt25_train)
dev_preds = quadratic_discriminant_analysis.predict(gt25_dev)
test_preds = quadratic_discriminant_analysis.predict(gt25_test)

In [10]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.7539759247869255
Accuracy Dev:  0.7544846992613436
Accuracy Test:  0.7477160927617709
F1 Train:  0.6744216725831986
F1 Dev:  0.40317686012469395
F1 Test:  0.3896183335950176
Precision Train:  0.6685008146974999
Precision Dev:  0.4009355348284987
Precision Test:  0.3906476722926912
Recall Train:  0.7744438140684701
Recall Dev:  0.49417880231111516
Recall Test:  0.47957475253888676
Confusion Matrix Train: 
[[ 1375   587     0]
 [ 5006 15768     4]
 [    0     3    19]]
Confusion Matrix Dev: 
[[ 197   75    0]
 [ 621 1948    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 171   79    0]
 [ 635 1957    1]
 [   0    3    0]]


C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### FastText 300 

In [11]:
ft300_train, ft300_dev, ft300_test = load_fasttext_300()

In [12]:
# Set all NaN values to 0
ft300_train = np.nan_to_num(ft300_train)
ft300_dev = np.nan_to_num(ft300_dev)
ft300_test = np.nan_to_num(ft300_test)

In [13]:
quadratic_discriminant_analysis = QuadraticDiscriminantAnalysis().fit(ft300_train, train_labels)

C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\discriminant_analysis.py:887: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


In [14]:
train_preds = quadratic_discriminant_analysis.predict(ft300_train)
dev_preds = quadratic_discriminant_analysis.predict(ft300_dev)
test_preds = quadratic_discriminant_analysis.predict(ft300_test)

In [15]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.7192250241630788
Accuracy Dev:  0.7073513893774183
Accuracy Test:  0.7041461700632466
F1 Train:  0.5135054305552197
F1 Dev:  0.3831116903688154
F1 Test:  0.37618064195981277
Precision Train:  0.6828990676842497
Precision Dev:  0.3938298991094022
Precision Test:  0.3893723195132053
Recall Train:  0.6183216596034141
Recall Dev:  0.4921323434005755
Recall Test:  0.49254917084458155
Confusion Matrix Train: 
[[ 1820   142     0]
 [ 6231 14546     1]
 [    3    14     5]]
Confusion Matrix Dev: 
[[ 211   61    0]
 [ 769 1800    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 195   55    0]
 [ 784 1809    0]
 [   0    3    0]]


C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Word2Vec 300

In [16]:
w2v300_train, w2v300_dev, w2v300_test = load_word2vec_300()

In [17]:
# Set all NaN values to 0
w2v300_train = np.nan_to_num(w2v300_train)
w2v300_dev = np.nan_to_num(w2v300_dev)
w2v300_test = np.nan_to_num(w2v300_test)

In [18]:
quadratic_discriminant_analysis = QuadraticDiscriminantAnalysis().fit(w2v300_train, train_labels)

C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\discriminant_analysis.py:887: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


In [19]:
train_preds = quadratic_discriminant_analysis.predict(w2v300_train)
dev_preds = quadratic_discriminant_analysis.predict(w2v300_dev)
test_preds = quadratic_discriminant_analysis.predict(w2v300_test)

In [20]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.7210702047271769
Accuracy Dev:  0.7059444249032711
Accuracy Test:  0.7097680955727337
F1 Train:  0.5140102376131676
F1 Dev:  0.3817181050891236
F1 Test:  0.3772495249220289
Precision Train:  0.6827656315338543
Precision Dev:  0.392892088967139
Precision Test:  0.38869663403415355
Recall Train:  0.6171492245149015
Recall Dev:  0.4894218586617208
Recall Test:  0.4885820799588636
Confusion Matrix Train: 
[[ 1808   154     0]
 [ 6177 14600     1]
 [    3    14     5]]
Confusion Matrix Dev: 
[[ 209   63    0]
 [ 771 1798    0]
 [   1    1    0]]
Confusion Matrix Test: 
[[ 190   60    0]
 [ 763 1830    0]
 [   0    3    0]]


C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### TF-IDF PCA (1000 Dims)

In [21]:
tfidf_pca_train, tfidf_pca_dev, tfidf_pca_test = load_tfidf_pca()

In [22]:
quadratic_discriminant_analysis = QuadraticDiscriminantAnalysis().fit(tfidf_pca_train, train_labels)

C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\discriminant_analysis.py:887: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


In [23]:
train_preds = quadratic_discriminant_analysis.predict(tfidf_pca_train)
dev_preds = quadratic_discriminant_analysis.predict(tfidf_pca_dev)
test_preds = quadratic_discriminant_analysis.predict(tfidf_pca_test)

In [24]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.842808189087075
Accuracy Dev:  0.798804080196975
Accuracy Test:  0.780744905130007
F1 Train:  0.475424310117472
F1 Dev:  0.40571322585412933
F1 Test:  0.3852103279623214
Precision Train:  0.45023520257597244
Precision Dev:  0.3960450687357195
Precision Test:  0.3808664290409934
Recall Train:  0.6046958826619035
Recall Dev:  0.4524534609484121
Recall Test:  0.43503380897287575
Confusion Matrix Train: 
[[ 1930    32     0]
 [ 3524 17254     0]
 [    6    16     0]]
Confusion Matrix Dev: 
[[ 144  128    0]
 [ 442 2127    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 124  126    0]
 [ 495 2098    0]
 [   2    1    0]]


C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision

### Sentence Transformer Faster No PCA

In [25]:
train, dev, test = load_sent_trans_fast_no_pca()

In [26]:
quadratic_discriminant_analysis = QuadraticDiscriminantAnalysis().fit(train, train_labels)

C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\discriminant_analysis.py:887: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


In [27]:
train_preds = quadratic_discriminant_analysis.predict(train)
dev_preds = quadratic_discriminant_analysis.predict(dev)
test_preds = quadratic_discriminant_analysis.predict(test)

In [28]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9198664440734557
Accuracy Dev:  0.9078438269433696
Accuracy Test:  0.9068868587491216
F1 Train:  0.4592698309444445
F1 Dev:  0.4376954218634636
F1 Test:  0.4152862631054917
Precision Train:  0.5025400620612072
Precision Dev:  0.4900783734254692
Precision Test:  0.4593774824871813
Recall Train:  0.43667324757062403
Recall Dev:  0.4159749730955052
Recall Test:  0.39805373441316366
Confusion Matrix Train: 
[[  655  1307     0]
 [  495 20283     0]
 [    1    21     0]]
Confusion Matrix Dev: 
[[  74  198    0]
 [  62 2507    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[  55  195    0]
 [  67 2526    0]
 [   0    3    0]]


C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision

### Sentence Transformer Faster PCA

In [29]:
train, dev, test = load_sent_trans_fast_pca()

In [30]:
quadratic_discriminant_analysis = QuadraticDiscriminantAnalysis().fit(train, train_labels)

C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\discriminant_analysis.py:887: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


In [31]:
train_preds = quadratic_discriminant_analysis.predict(train)
dev_preds = quadratic_discriminant_analysis.predict(dev)
test_preds = quadratic_discriminant_analysis.predict(test)

In [32]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.8861259994728056
Accuracy Dev:  0.8607105170594442
Accuracy Test:  0.865425158116655
F1 Train:  0.503509673166497
F1 Dev:  0.46967280439711284
F1 Test:  0.46504811311613486
Precision Train:  0.47107545318132926
Precision Dev:  0.4472405747617015
Precision Test:  0.4422564892423049
Recall Train:  0.5925128210864448
Recall Dev:  0.5245980544806478
Recall Test:  0.5214346317007328
Confusion Matrix Train: 
[[ 1748   214     0]
 [ 2356 18422     0]
 [    1    21     0]]
Confusion Matrix Dev: 
[[ 189   83    0]
 [ 311 2258    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 170   80    0]
 [ 300 2293    0]
 [   0    3    0]]


C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision

### Sentence Transformer Better No PCA

In [33]:
train, dev, test = load_sent_trans_better_no_pca()

In [34]:
quadratic_discriminant_analysis = QuadraticDiscriminantAnalysis().fit(train, train_labels)

C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\discriminant_analysis.py:887: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


In [35]:
train_preds = quadratic_discriminant_analysis.predict(train)
dev_preds = quadratic_discriminant_analysis.predict(dev)
test_preds = quadratic_discriminant_analysis.predict(test)

In [36]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.8807661892628065
Accuracy Dev:  0.8445304256067534
Accuracy Test:  0.8489107519325368
F1 Train:  0.4581842209848508
F1 Dev:  0.38136066923376094
F1 Test:  0.3893906492133005
Precision Train:  0.4419771408345648
Precision Dev:  0.37927905321278055
Precision Test:  0.38420529903457634
Recall Train:  0.4851669643134857
Recall Dev:  0.38385367771086637
Recall Test:  0.39732407764494154
Confusion Matrix Train: 
[[ 1063   899     0]
 [ 1793 18985     0]
 [    0    22     0]]
Confusion Matrix Dev: 
[[  66  206    0]
 [ 234 2335    0]
 [   1    1    0]]
Confusion Matrix Test: 
[[  72  178    0]
 [ 249 2344    0]
 [   0    3    0]]


C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision

### Sentence Transformer Better PCA

In [37]:
train, dev, test = load_sent_trans_better_pca()

In [38]:
quadratic_discriminant_analysis = QuadraticDiscriminantAnalysis().fit(train, train_labels)

C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\discriminant_analysis.py:887: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


In [39]:
train_preds = quadratic_discriminant_analysis.predict(train)
dev_preds = quadratic_discriminant_analysis.predict(dev)
test_preds = quadratic_discriminant_analysis.predict(test)

In [40]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9039188120551797
Accuracy Dev:  0.8797045374604291
Accuracy Test:  0.8805340829234013
F1 Train:  0.5243740172499892
F1 Dev:  0.48798658968150493
F1 Test:  0.4827967694269703
Precision Train:  0.48850212988240016
Precision Dev:  0.4639745747555595
Precision Test:  0.457418406065913
Recall Train:  0.6116259464035562
Recall Dev:  0.5370833619551363
Recall Test:  0.5390101555469854
Confusion Matrix Train: 
[[ 1830   132     0]
 [ 2033 18745     0]
 [    1    21     0]]
Confusion Matrix Dev: 
[[ 194   78    0]
 [ 262 2307    0]
 [   0    2    0]]
Confusion Matrix Test: 
[[ 180   70    0]
 [ 267 2326    0]
 [   0    3    0]]


C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision